require.config({
    paths: {
        'vo-libs-angular': '../shared/components.ng',
        'vo-libs': '../shared/components',
        'angular': '../assets/js/angular.js/1.5.6/angular',
        'jquery': '../assets/js/jquery/2.2.4/jquery',
        'angularAMD': '../assets/js/angularAMD/custom/angularAMD.min',
        'underscore': '../assets/js/underscore.js/1.8.3/underscore',
        'filestyle': '../assets/js/bootstrap-filestyle/1.2.1/bootstrap-filestyle',
        'notify': '../assets/js/notify/0.4.0/notify',
        'angular-block-ui': '../assets/js/angular-block-ui/0.2.1/angular-block-ui',
        'angular-cookies': '../assets/js/angular.js/1.5.6/angular-cookies',
        'angular-sanitize': '../assets/js/angular.js/1.5.6/angular-sanitize',
        'angular-route': '../assets/js/angular.js/1.5.6/angular-route',
        'angular-translate': '../assets/js/angular-translate/2.8.1/angular-translate',
        'angular-ui-bootstrap': '../assets/js/angular-ui-bootstrap/1.3.3/ui-bootstrap-tpls.min',
        'chosen': '../assets/js/chosen/1.4.2/chosen.jquery',
        'angular-chosen': '../assets/js/angular-chosen/1.2.0/angular-chosen',
        'angular-animate': '../assets/js/angular.js/1.5.6/angular-animate',
        'ngStorage': '../assets/js/ngstorage/0.3.10/ngStorage',
        'angular-file-upload': '../assets/js/angular-file-upload/2.2.0/angular-file-upload',
        'md5': '../assets/js/angular-md5/0.1.8/angular-md5',
        'vms': 'vms.module'
    },
    shim: {
        'vo-libs': ['jquery'],
        'vo-libs-angular': ['angular'],
        'angular-sanitize': ['angular'],
        'angular-route': ['angular'],
        'angular-animate': ['angular'],
        'angular-cookies': ['angular'],
        'angular-translate': ['angular'],
        'angular-block-ui': ['angular'],
        'angular-ui-bootstrap': ['angular'],
        'ngStorage': ['angular'],
        'angular-file-upload': ['angular'],
        'angular': {exports: 'angular', deps: ['jquery']},
        'jquery': {exports: 'jQuery'},
        'filestyle': ['jquery'],
        'angularAMD': ['angular'],
        'chosen': ['jquery'],
        'angular-chosen': ['angular', 'chosen'],
        'md5': ['angular'],
        'vms': [
            'angularAMD',
            'underscore',
            'angular-sanitize',
            'angular-route',
            'angular-animate',
            'angular-cookies',
            'angular-translate',
            'angular-block-ui',
            'angular-ui-bootstrap',
            'angular-chosen',
            'ngStorage',
            'vo-libs-angular',
            'md5'
        ]
    },
    deps: ['vms']
});