/*
 * ComMtValueChannelModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.openapi.oauth;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * 
 */
public class ComOpenApiClientModel extends BaseModel {
    /**
     * 用户账号
     */
    protected String userAccount;

    /**
     * openapi client Id
     */
    protected String clientId;

    /**
     * openapi client secret
     */
    protected String clientSecret;

    /**
     * 删除标识:1,激活;0,禁用;2,锁定
     */
    protected Integer active;

    public String getUserAccount() {
        return userAccount;
    }

    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    public Integer getActive() {
        return active;
    }

    public void setActive(Integer active) {
        this.active = active;
    }
}