/*
 * TmSmsConfigModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.com;

/**
 * 
 */
public class TmSmsConfigModel extends AdminBaseModel {
    protected Integer seq;

    protected String orderChannelId;

    protected String smsType;

    protected String smsCode1;

    protected String smsCode2;

    protected String content;

    protected String describe;

    protected String delFlg;
    
    protected Boolean active;

    public Integer getSeq() {
        return seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public String getOrderChannelId() {
        return orderChannelId;
    }

    public void setOrderChannelId(String orderChannelId) {
        this.orderChannelId = orderChannelId == null ? null : orderChannelId.trim();
    }

    public String getSmsType() {
        return smsType;
    }

    public void setSmsType(String smsType) {
        this.smsType = smsType == null ? null : smsType.trim();
    }

    public String getSmsCode1() {
        return smsCode1;
    }

    public void setSmsCode1(String smsCode1) {
        this.smsCode1 = smsCode1 == null ? null : smsCode1.trim();
    }

    public String getSmsCode2() {
        return smsCode2;
    }

    public void setSmsCode2(String smsCode2) {
        this.smsCode2 = smsCode2 == null ? null : smsCode2.trim();
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    public String getDelFlg() {
        return delFlg;
    }

    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg == null ? null : delFlg.trim();
    }

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}
    
}