/*
 * CmsBtTaskTejiabaoDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtTaskTejiabaoModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtTaskTejiabaoDao {
    List<CmsBtTaskTejiabaoModel> selectList(Map<String, Object> map);

    CmsBtTaskTejiabaoModel selectOne(Map<String, Object> map);

    CmsBtTaskTejiabaoModel select(Integer id);

    int insert(CmsBtTaskTejiabaoModel record);

    int update(CmsBtTaskTejiabaoModel record);

    int delete(Integer id);
}