/*
 * CmsBtPromotionDao.java
 * Copyright(C) 20xx-2015 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtPromotionModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtPromotionDao {
    List<CmsBtPromotionModel> selectList(Map<String, Object> map);

    CmsBtPromotionModel selectOne(Map<String, Object> map);

    CmsBtPromotionModel select(Integer id);

    int insert(CmsBtPromotionModel record);

    int update(CmsBtPromotionModel record);

    int delete(Integer id);
}