/*
 * CmsBtSxCnProductSellercatDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtSxCnProductSellercatModel;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CmsBtSxCnProductSellercatDao {

    List<CmsBtSxCnProductSellercatModel> selectList(Object map);

    CmsBtSxCnProductSellercatModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtSxCnProductSellercatModel select(Integer id);

    int insert(CmsBtSxCnProductSellercatModel record);

    int update(CmsBtSxCnProductSellercatModel record);

    int delete(Integer id);

}