/*
 * CmsBtTagJmModuleExtensionDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtTagJmModuleExtensionModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtTagJmModuleExtensionDao {
    List<CmsBtTagJmModuleExtensionModel> selectList(Object map);

    CmsBtTagJmModuleExtensionModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtTagJmModuleExtensionModel select(Integer tagId);

    int insert(CmsBtTagJmModuleExtensionModel record);

    int update(CmsBtTagJmModuleExtensionModel record);

    int delete(Integer tagId);
}