/*
 * CmsBtShelvesDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtShelvesModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtShelvesDao {
    List<CmsBtShelvesModel> selectList(Object map);

    CmsBtShelvesModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtShelvesModel select(Integer id);

    int insert(CmsBtShelvesModel record);

    int update(CmsBtShelvesModel record);

    int delete(Integer id);
}