/*
 * CmsBtSxWorkloadDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtSxWorkloadModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtSxWorkloadDao {
    List<CmsBtSxWorkloadModel> selectList(Map<String, Object> map);

    CmsBtSxWorkloadModel selectOne(Map<String, Object> map);

    CmsBtSxWorkloadModel select(Integer id);

    int insert(CmsBtSxWorkloadModel record);

    int update(CmsBtSxWorkloadModel record);

    int delete(Integer id);
}