/*
 * CmsBtJmPromotionExportTaskDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtJmPromotionExportTaskModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtJmPromotionExportTaskDao {
    List<CmsBtJmPromotionExportTaskModel> selectList(Map<String, Object> map);

    CmsBtJmPromotionExportTaskModel selectOne(Map<String, Object> map);

    CmsBtJmPromotionExportTaskModel select(Integer id);

    int insert(CmsBtJmPromotionExportTaskModel record);

    int update(CmsBtJmPromotionExportTaskModel record);

    int delete(Integer id);
}