/*
 * CmsBtJmPromotionDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtJmPromotionModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtJmPromotionDao {
    List<CmsBtJmPromotionModel> selectList(Object map);

    CmsBtJmPromotionModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtJmPromotionModel select(Integer id);

    int insert(CmsBtJmPromotionModel record);

    int update(CmsBtJmPromotionModel record);

    int delete(Integer id);
}