/*
 * CmsBtRefreshProductTaskDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtRefreshProductTaskExample;
import com.voyageone.service.model.cms.CmsBtRefreshProductTaskModel;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtRefreshProductTaskDao {
    List<CmsBtRefreshProductTaskModel> selectList(Object map);

    CmsBtRefreshProductTaskModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtRefreshProductTaskModel select(Integer id);

    int insert(CmsBtRefreshProductTaskModel record);

    int update(CmsBtRefreshProductTaskModel record);

    int countByExample(CmsBtRefreshProductTaskExample example);

    int deleteByExample(CmsBtRefreshProductTaskExample example);

    int delete(Integer id);

    List<CmsBtRefreshProductTaskModel> selectByExample(CmsBtRefreshProductTaskExample example);

    int updateByExampleSelective(@Param("record") CmsBtRefreshProductTaskModel record, @Param("example") CmsBtRefreshProductTaskExample example);

    int updateByExample(@Param("record") CmsBtRefreshProductTaskModel record, @Param("example") CmsBtRefreshProductTaskExample example);
}