/*
 * CmsBtStoreOperationHistoryDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtStoreOperationHistoryModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtStoreOperationHistoryDao {
    List<CmsBtStoreOperationHistoryModel> selectList(Map<String, Object> map);

    CmsBtStoreOperationHistoryModel selectOne(Map<String, Object> map);

    CmsBtStoreOperationHistoryModel select(Integer id);

    int insert(CmsBtStoreOperationHistoryModel record);

    int update(CmsBtStoreOperationHistoryModel record);

    int delete(Integer id);
}