/*
 * CmsBtJmPromotionProductDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtJmPromotionProductModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtJmPromotionProductDao {
    List<CmsBtJmPromotionProductModel> selectList(Map<String, Object> map);

    CmsBtJmPromotionProductModel selectOne(Map<String, Object> map);

    CmsBtJmPromotionProductModel select(Integer id);

    int insert(CmsBtJmPromotionProductModel record);

    int update(CmsBtJmPromotionProductModel record);

    int delete(Integer id);
}