/*
 * CmsBtJmMasterBrandDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtJmMasterBrandModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtJmMasterBrandDao {
    List<CmsBtJmMasterBrandModel> selectList(Map<String, Object> map);

    CmsBtJmMasterBrandModel selectOne(Map<String, Object> map);

    CmsBtJmMasterBrandModel select(Integer id);

    int insert(CmsBtJmMasterBrandModel record);

    int update(CmsBtJmMasterBrandModel record);

    int delete(Integer id);
}