/*
 * CmsBtPlatformImagesDao.java
 * Copyright(C) 20xx-2015 Voyageonone Group Inc.
 * All rights reserved.
 * This class is generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtPlatformImagesModel;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface CmsBtPlatformImagesDao {
    List<CmsBtPlatformImagesModel> selectList(Map<String, Object> map);

    CmsBtPlatformImagesModel selectOne(Map<String, Object> map);

    CmsBtPlatformImagesModel select(Integer id);

    int insert(CmsBtPlatformImagesModel record);

    int update(CmsBtPlatformImagesModel record);

    int delete(Integer id);
}