/*
 * CmsBtKlSkuDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtKlSkuModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtKlSkuDao {
    List<CmsBtKlSkuModel> selectList(Object map);

    CmsBtKlSkuModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtKlSkuModel select(Integer id);

    int insert(CmsBtKlSkuModel record);

    int update(CmsBtKlSkuModel record);

    int delete(Integer id);
}