/*
 * CmsBtPromotionCodesTagDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtPromotionCodesTagModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtPromotionCodesTagDao {
    List<CmsBtPromotionCodesTagModel> selectList(Object map);

    CmsBtPromotionCodesTagModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtPromotionCodesTagModel select(Integer id);

    int insert(CmsBtPromotionCodesTagModel record);

    int update(CmsBtPromotionCodesTagModel record);

    int delete(Integer id);
}