/*
 * CmsBtJmPromotionImportTaskDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtJmPromotionImportTaskModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtJmPromotionImportTaskDao {
    List<CmsBtJmPromotionImportTaskModel> selectList(Object map);

    CmsBtJmPromotionImportTaskModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtJmPromotionImportTaskModel select(Integer id);

    int insert(CmsBtJmPromotionImportTaskModel record);

    int update(CmsBtJmPromotionImportTaskModel record);

    int delete(Integer id);
}