/*
 * CmsBtTaskJiagepiluDao.java
 * Copyright(C) 20xx-2015 Voyageonone Group Inc.
 * All rights reserved.
 * This class is generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtTaskJiagepiluModel;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface CmsBtTaskJiagepiluDao {
    List<CmsBtTaskJiagepiluModel> selectList(Map<String, Object> map);

    CmsBtTaskJiagepiluModel selectOne(Map<String, Object> map);

    CmsBtTaskJiagepiluModel select(Integer id);

    int insert(CmsBtTaskJiagepiluModel record);

    int update(CmsBtTaskJiagepiluModel record);

    int delete(Integer id);
}