/*
 * CmsBtSxProductDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtSxProductModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtSxProductDao {
    List<CmsBtSxProductModel> selectList(Object map);

    CmsBtSxProductModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtSxProductModel select(Integer id);

    int insert(CmsBtSxProductModel record);

    int update(CmsBtSxProductModel record);

    int delete(Integer id);
}