/*
 * CmsBtPromotionSkusDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtPromotionSkusModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtPromotionSkusDao {
    List<CmsBtPromotionSkusModel> selectList(Map<String, Object> map);

    CmsBtPromotionSkusModel selectOne(Map<String, Object> map);

    CmsBtPromotionSkusModel select(Integer id);

    int insert(CmsBtPromotionSkusModel record);

    int update(CmsBtPromotionSkusModel record);

    int delete(Integer id);
}