/*
 * CmsBtSizeChartImageGroupDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtSizeChartImageGroupModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtSizeChartImageGroupDao {
    List<CmsBtSizeChartImageGroupModel> selectList(Object map);

    CmsBtSizeChartImageGroupModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtSizeChartImageGroupModel select(Integer id);

    int insert(CmsBtSizeChartImageGroupModel record);

    int update(CmsBtSizeChartImageGroupModel record);

    int delete(Integer id);
}