/*
 * CmsBtJmPromotionTagProductDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import org.springframework.stereotype.Repository;

import java.util.Map;

@Repository
public interface CmsBtJmPromotionSpecialExtensionDao {

    /**
     * 查询聚美活动扩展信息
     *
     * @param jmPromotionId 聚美活动ID
     * @return
     */
    Map<String, Object> selectOne(Integer jmPromotionId);

    int insert(Map<String, Object> record);

    int update(Map<String, Object> record);

    int delete(Integer id);
}