/*
 * CmsBtProductStatusHistoryDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtProductStatusHistoryModel_Mysql;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository("cmsBtProductStatusHistoryDaoMysql")
public interface CmsBtProductStatusHistoryDao {
    List<CmsBtProductStatusHistoryModel_Mysql> selectList(Object map);

    CmsBtProductStatusHistoryModel_Mysql selectOne(Object map);

    int selectCount(Object map);

    CmsBtProductStatusHistoryModel_Mysql select(Integer id);

    int insert(CmsBtProductStatusHistoryModel_Mysql record);

    int update(CmsBtProductStatusHistoryModel_Mysql record);

    int delete(Integer id);
}