/*
 * CmsBtSxCnProductSellercatDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import org.springframework.stereotype.Repository;

import java.util.Map;

@Repository
public interface CmsBtSxCnProductSellercatDao {

    Map select(Integer id);

    int insert(Map record);

    int update(Map record);

}