/*
 * CmsBtTagDao.java
 * Copyright(C) 20xx-2015 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtTagModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtTagDao {
    List<CmsBtTagModel> selectList(Map<String, Object> map);

    CmsBtTagModel selectOne(Map<String, Object> map);

    CmsBtTagModel select(Integer id);

    int insert(CmsBtTagModel record);

    int update(CmsBtTagModel record);

    int delete(Integer id);
}