/*
 * CmsBtRefreshProductTaskItemDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtRefreshProductTaskItemExample;
import com.voyageone.service.model.cms.CmsBtRefreshProductTaskItemModel;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtRefreshProductTaskItemDao {
    List<CmsBtRefreshProductTaskItemModel> selectList(Object map);

    CmsBtRefreshProductTaskItemModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtRefreshProductTaskItemModel select(Integer id);

    int insert(CmsBtRefreshProductTaskItemModel record);

    int update(CmsBtRefreshProductTaskItemModel record);

    int countByExample(CmsBtRefreshProductTaskItemExample example);

    int deleteByExample(CmsBtRefreshProductTaskItemExample example);

    int delete(Integer id);

    List<CmsBtRefreshProductTaskItemModel> selectByExample(CmsBtRefreshProductTaskItemExample example);

    int updateByExampleSelective(@Param("record") CmsBtRefreshProductTaskItemModel record, @Param("example") CmsBtRefreshProductTaskItemExample example);

    int updateByExample(@Param("record") CmsBtRefreshProductTaskItemModel record, @Param("example") CmsBtRefreshProductTaskItemExample example);
}