/*
 * CmsBtPromotionCodesDao.java
 * Copyright(C) 20xx-2015 Voyageonone Group Inc.
 * All rights reserved.
 * This class is generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtPromotionCodesModel;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface CmsBtPromotionCodesDao {
    List<CmsBtPromotionCodesModel> selectList(Map<String, Object> map);

    CmsBtPromotionCodesModel selectOne(Map<String, Object> map);

    CmsBtPromotionCodesModel select(Integer id);

    int insert(CmsBtPromotionCodesModel record);

    int update(CmsBtPromotionCodesModel record);

    int delete(Integer id);
}