/*
 * CmsBtTasksDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtTasksModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtTasksDao {
    List<CmsBtTasksModel> selectList(Map<String, Object> map);

    CmsBtTasksModel selectOne(Map<String, Object> map);

    CmsBtTasksModel select(Integer id);

    int insert(CmsBtTasksModel record);

    int update(CmsBtTasksModel record);

    int delete(Integer id);
}