/*
 * CmsBtBusinessLogDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtBusinessLogModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtBusinessLogDao {
    List<CmsBtBusinessLogModel> selectList(Map<String, Object> map);

    CmsBtBusinessLogModel selectOne(Map<String, Object> map);

    CmsBtBusinessLogModel select(Integer id);

    int insert(CmsBtBusinessLogModel record);

    int update(CmsBtBusinessLogModel record);

    int delete(Integer id);
}