/*
 * CmsBtSxCspuDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsBtSxCspuModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsBtSxCspuDao {
    List<CmsBtSxCspuModel> selectList(Object map);

    CmsBtSxCspuModel selectOne(Object map);

    int selectCount(Object map);

    CmsBtSxCspuModel select(Integer id);

    int insert(CmsBtSxCspuModel record);

    int update(CmsBtSxCspuModel record);

    int delete(Integer id);
}