/*
 * CmsMtCustomWordDao.java
 * Copyright(C) 20xx-2015 Voyageonone Group Inc.
 * All rights reserved.
 * This class is generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtCustomWordModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsMtCustomWordDao {
    List<CmsMtCustomWordModel> selectList(Map<String, Object> map);

    CmsMtCustomWordModel selectOne(Map<String, Object> map);

    CmsMtCustomWordModel select(Integer id);

    int insert(CmsMtCustomWordModel record);

    int update(CmsMtCustomWordModel record);

    int delete(Integer id);
}