/*
 * CmsMtChannelConfigKeyDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtChannelConfigKeyModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsMtChannelConfigKeyDao {
    List<CmsMtChannelConfigKeyModel> selectList(Object map);

    CmsMtChannelConfigKeyModel selectOne(Object map);

    int selectCount(Object map);

    CmsMtChannelConfigKeyModel select(Integer id);

    int insert(CmsMtChannelConfigKeyModel record);

    int update(CmsMtChannelConfigKeyModel record);

    int delete(Integer id);
}