/*
 * CmsMtImageCreateTaskDetailDao.java
 * Copyright(C) 20xx-2015 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtImageCreateTaskDetailModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsMtImageCreateTaskDetailDao {
    List<CmsMtImageCreateTaskDetailModel> selectList(Map<String, Object> map);

    CmsMtImageCreateTaskDetailModel selectOne(Map<String, Object> map);

    CmsMtImageCreateTaskDetailModel select(Integer id);

    int insert(CmsMtImageCreateTaskDetailModel record);

    int update(CmsMtImageCreateTaskDetailModel record);

    int delete(Integer id);
}