/*
 * CmsMtFeeTaxDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtFeeTaxModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsMtFeeTaxDao {
    List<CmsMtFeeTaxModel> selectList(Map<String, Object> map);

    CmsMtFeeTaxModel selectOne(Map<String, Object> map);

    int selectCount(Map<String, Object> map);

    CmsMtFeeTaxModel select(Integer id);

    int insert(CmsMtFeeTaxModel record);

    int update(CmsMtFeeTaxModel record);

    int delete(Integer id);
}