/*
 * CmsMtFeeCommissionDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtFeeCommissionModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsMtFeeCommissionDao {
    List<CmsMtFeeCommissionModel> selectList(Map<String, Object> map);

    CmsMtFeeCommissionModel selectOne(Map<String, Object> map);

    int selectCount(Map<String, Object> map);

    CmsMtFeeCommissionModel select(Integer id);

    int insert(CmsMtFeeCommissionModel record);

    int update(CmsMtFeeCommissionModel record);

    int delete(Integer id);
}