/*
 * CmsMtCommonPropDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtCommonPropModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsMtCommonPropDao {
    List<CmsMtCommonPropModel> selectList(Map<String, Object> map);

    CmsMtCommonPropModel selectOne(Map<String, Object> map);

    CmsMtCommonPropModel select(Integer id);

    int insert(CmsMtCommonPropModel record);

    int update(CmsMtCommonPropModel record);

    int delete(Integer id);
}