/*
 * CmsMtMasterInfoDao.java
 * Copyright(C) 20xx-2015 Voyageonone Group Inc.
 * All rights reserved.
 * This class is generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtMasterInfoModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsMtMasterInfoDao {
    List<CmsMtMasterInfoModel> selectList(Map<String, Object> map);

    CmsMtMasterInfoModel selectOne(Map<String, Object> map);

    CmsMtMasterInfoModel select(Integer id);

    int insert(CmsMtMasterInfoModel record);

    int update(CmsMtMasterInfoModel record);

    int delete(Integer id);
}