/*
 * CmsMtImageCreateTemplateDao.java
 * Copyright(C) 20xx-2015 Voyageonone Group Inc.
 * All rights reserved.
 * This class is generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtImageCreateTemplateModel;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface CmsMtImageCreateTemplateDao {
    List<CmsMtImageCreateTemplateModel> selectList(Map<String, Object> map);

    CmsMtImageCreateTemplateModel selectOne(Map<String, Object> map);

    CmsMtImageCreateTemplateModel select(Integer id);

    int insert(CmsMtImageCreateTemplateModel record);

    int update(CmsMtImageCreateTemplateModel record);

    int delete(Integer id);
}