/*
 * CmsMtFeedCustomOptionDao.java
 * Copyright(C) 20xx-2015 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtFeedCustomOptionModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsMtFeedCustomOptionDao {
    List<CmsMtFeedCustomOptionModel> selectList(Map<String, Object> map);

    CmsMtFeedCustomOptionModel selectOne(Map<String, Object> map);

    CmsMtFeedCustomOptionModel select(Integer id);

    int insert(CmsMtFeedCustomOptionModel record);

    int update(CmsMtFeedCustomOptionModel record);

    int delete(Integer id);
}