/*
 * CmsMtPlatformPropSkuDao.java
 * Copyright(C) 20xx-2015 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 * 2016-05-06 Created
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtPlatformPropSkuModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsMtPlatformPropSkuDao {
    List<CmsMtPlatformPropSkuModel> selectList(Map<String, Object> map);

    CmsMtPlatformPropSkuModel selectOne(Map<String, Object> map);

    CmsMtPlatformPropSkuModel select(Integer seq);

    int insert(CmsMtPlatformPropSkuModel record);

    int update(CmsMtPlatformPropSkuModel record);

    int delete(Integer seq);
}