/*
 * CmsMtChannelConditionMappingConfigDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtChannelConditionMappingConfigModel;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CmsMtChannelConditionMappingConfigDao {
    List<CmsMtChannelConditionMappingConfigModel> selectList(Object map);

    CmsMtChannelConditionMappingConfigModel selectOne(Object map);

    int selectCount(Object map);

    CmsMtChannelConditionMappingConfigModel select(Integer id);

    int insert(CmsMtChannelConditionMappingConfigModel record);

    int update(CmsMtChannelConditionMappingConfigModel record);

    int delete(Integer id);
}