/*
 * CmsMtPlatformPropMappingCustomDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsMtPlatformPropMappingCustomModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsMtPlatformPropMappingCustomDao {
    List<CmsMtPlatformPropMappingCustomModel> selectList(Map<String, Object> map);

    CmsMtPlatformPropMappingCustomModel selectOne(Map<String, Object> map);

    CmsMtPlatformPropMappingCustomModel select(Integer seq);

    int insert(CmsMtPlatformPropMappingCustomModel record);

    int update(CmsMtPlatformPropMappingCustomModel record);

    int delete(Integer seq);
}