/*
 * CmsZzFeedGiltInventoryDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.cms;

import com.voyageone.service.model.cms.CmsZzFeedGiltInventoryModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsZzFeedGiltInventoryDao {
    List<CmsZzFeedGiltInventoryModel> selectList(Object map);

    CmsZzFeedGiltInventoryModel selectOne(Object map);

    int selectCount(Object map);

    CmsZzFeedGiltInventoryModel select(String sku);

    int insert(CmsZzFeedGiltInventoryModel record);

    int update(CmsZzFeedGiltInventoryModel record);

    int delete(String sku);
}