/*
 * ComMtThirdPartyConfigModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.admin;

/**
 * 
 */
public class ComMtThirdPartyConfigModel extends AdminBaseModel {
    protected Integer seq;

    protected String channelId;

    protected String propName;

    protected String propVal1;

    protected String propVal2;

    protected String propVal3;

    protected String propVal4;

    protected String propVal5;

    protected String propVal6;

    protected String comment;

    public Integer getSeq() {
        return seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    public String getPropName() {
        return propName;
    }

    public void setPropName(String propName) {
        this.propName = propName == null ? null : propName.trim();
    }

    public String getPropVal1() {
        return propVal1;
    }

    public void setPropVal1(String propVal1) {
        this.propVal1 = propVal1 == null ? null : propVal1.trim();
    }

    public String getPropVal2() {
        return propVal2;
    }

    public void setPropVal2(String propVal2) {
        this.propVal2 = propVal2 == null ? null : propVal2.trim();
    }

    public String getPropVal3() {
        return propVal3;
    }

    public void setPropVal3(String propVal3) {
        this.propVal3 = propVal3 == null ? null : propVal3.trim();
    }

    public String getPropVal4() {
        return propVal4;
    }

    public void setPropVal4(String propVal4) {
        this.propVal4 = propVal4 == null ? null : propVal4.trim();
    }

    public String getPropVal5() {
        return propVal5;
    }

    public void setPropVal5(String propVal5) {
        this.propVal5 = propVal5 == null ? null : propVal5.trim();
    }

    public String getPropVal6() {
        return propVal6;
    }

    public void setPropVal6(String propVal6) {
        this.propVal6 = propVal6 == null ? null : propVal6.trim();
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}