/*
 * TmOrderChannelModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.admin;

/**
 * 
 */
public class TmOrderChannelModel extends AdminBaseModel {
    protected String orderChannelId;

    protected Integer companyId;

    protected String name;

    protected String fullName;

    protected String imgUrl;

    protected String sendName;

    protected String sendAddress;

    protected String sendTel;

    protected String sendZip;

    protected String screctKey;

    protected String sessionKey;

    protected Integer isUsjoi;

    /**
     * sub_channel在usjoi下有那几个cart   逗号分隔
     */
    protected String cartIds;

    protected Integer active;

    public String getOrderChannelId() {
        return orderChannelId;
    }

    public void setOrderChannelId(String orderChannelId) {
        this.orderChannelId = orderChannelId == null ? null : orderChannelId.trim();
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    public String getSendName() {
        return sendName;
    }

    public void setSendName(String sendName) {
        this.sendName = sendName == null ? null : sendName.trim();
    }

    public String getSendAddress() {
        return sendAddress;
    }

    public void setSendAddress(String sendAddress) {
        this.sendAddress = sendAddress == null ? null : sendAddress.trim();
    }

    public String getSendTel() {
        return sendTel;
    }

    public void setSendTel(String sendTel) {
        this.sendTel = sendTel == null ? null : sendTel.trim();
    }

    public String getSendZip() {
        return sendZip;
    }

    public void setSendZip(String sendZip) {
        this.sendZip = sendZip == null ? null : sendZip.trim();
    }

    public String getScrectKey() {
        return screctKey;
    }

    public void setScrectKey(String screctKey) {
        this.screctKey = screctKey == null ? null : screctKey.trim();
    }

    public String getSessionKey() {
        return sessionKey;
    }

    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }

    public Integer getIsUsjoi() {
        return isUsjoi;
    }

    public void setIsUsjoi(Integer isUsjoi) {
        this.isUsjoi = isUsjoi;
    }

    public String getCartIds() {
        return cartIds;
    }

    public void setCartIds(String cartIds) {
        this.cartIds = cartIds == null ? null : cartIds.trim();
    }

    public Integer getActive() {
        return active;
    }

    public void setActive(Integer active) {
        this.active = active;
    }
}