// Generated by CoffeeScript 1.9.3

/*
  @Name: DictCustomController
  @Date: 2015-09-15 16:06:34

  @User: Jonas
  @Version: 0.0.1
 */

define([
  'cms'
], function (cms) {


  cms.controller('popDictValueController', function ($scope) {
//, $propChangeService, $translate, $modalInstance, notify
    //$scope.vm = {
    //  propertyInfo: {
    //    property: {},
    //    productIds: productIds
    //  },
    //  properties: []
    //};
    //
    //$scope.initialize = initialize;
    //$scope.save = save;
    //
    //function initialize() {
    //  $propChangeService.getPopOptions().then(function (res) {
    //    $scope.vm.properties = res.data;
    //  });
    //}
    //
    //function save () {
    //  $propChangeService.setProductFields($scope.vm.propertyInfo).then(function () {
    //    notify.success ($translate.instant('TXT_COM_UPDATE_SUCCESS'));
    //    //$scope.$close();
    //    $modalInstance.close('');
    //  });
    //}
  });
});