# 创建 bcbg 数据表

DROP TABLE voyageone_cms.cms_zz_worktable_bcbg_superfeed;

CREATE TABLE voyageone_cms.cms_zz_worktable_bcbg_superfeed
(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  MATNR VARCHAR(18) NOT NULL,
  EAN11 VARCHAR(18) NOT NULL,
  BRAND_ID VARCHAR(300) NOT NULL COMMENT '*需要Master 转换',
  MATKL VARCHAR(300) NOT NULL COMMENT '*需要Master 转换',
  ZZCODE1 VARCHAR(3) NOT NULL,
  ZZCODE2 VARCHAR(20) NOT NULL,
  ZZCODE3 VARCHAR(20) NOT NULL,
  MEINS VARCHAR(3) NOT NULL,
  BSTME VARCHAR(3) NOT NULL,
  COLOR VARCHAR(18) NOT NULL,
  COLOR_ATWTB VARCHAR(100) NOT NULL,
  SIZE1 VARCHAR(18) NOT NULL,
  SIZE1_ATWTB VARCHAR(100) NOT NULL,
  SIZE1_ATINN VARCHAR(10) NOT NULL,
  ATBEZ VARCHAR(100) NOT NULL,
  SAISO VARCHAR(300) NOT NULL COMMENT '*需要Master 转换',
  SAISJ VARCHAR(4) NOT NULL,
  SAITY VARCHAR(300) NOT NULL COMMENT '*需要Master 转换',
  SATNR VARCHAR(18) NOT NULL,
  MAKTX VARCHAR(40) NOT NULL,
  WLADG VARCHAR(300) NOT NULL COMMENT '*需要Master 转换',
  WHERL VARCHAR(3) NOT NULL,
  MEAN_EAN11 VARCHAR(18) NOT NULL,
  A304_DATAB DATETIME NOT NULL,
  A304_DATBI DATETIME NOT NULL,
  A304_KBETR DECIMAL(11,4) NOT NULL,
  A304_KONWA VARCHAR(5) NOT NULL,
  A073_DATAB DATETIME NOT NULL,
  A073_DATBI DATETIME NOT NULL,
  A073_KBETR DECIMAL(11,4) NOT NULL,
  A073_KONWA VARCHAR(5) NOT NULL,
  update_flg INT NOT NULL COMMENT '0 为未定, 1 为插入, 2 为更新' DEFAULT 0
);

CREATE TABLE voyageone_cms.cms_zz_worktable_bcbg_superfeed_full
(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  MATNR VARCHAR(18) NOT NULL,
  EAN11 VARCHAR(18) NOT NULL,
  BRAND_ID VARCHAR(300) NOT NULL COMMENT '该列为 Master 数据(已转换)',
  MATKL VARCHAR(300) NOT NULL COMMENT '该列为 Master 数据(已转换)',
  ZZCODE1 VARCHAR(3) NOT NULL,
  ZZCODE2 VARCHAR(20) NOT NULL,
  ZZCODE3 VARCHAR(20) NOT NULL,
  MEINS VARCHAR(3) NOT NULL,
  BSTME VARCHAR(3) NOT NULL,
  COLOR VARCHAR(18) NOT NULL,
  COLOR_ATWTB VARCHAR(100) NOT NULL,
  SIZE1 VARCHAR(18) NOT NULL,
  SIZE1_ATWTB VARCHAR(100) NOT NULL,
  SIZE1_ATINN VARCHAR(10) NOT NULL,
  ATBEZ VARCHAR(100) NOT NULL,
  SAISO VARCHAR(300) NOT NULL COMMENT '该列为 Master 数据(已转换)',
  SAISJ VARCHAR(4) NOT NULL,
  SAITY VARCHAR(300) NOT NULL COMMENT '该列为 Master 数据(已转换)',
  SATNR VARCHAR(18) NOT NULL,
  MAKTX VARCHAR(40) NOT NULL,
  WLADG VARCHAR(300) NOT NULL COMMENT '该列为 Master 数据(已转换)',
  WHERL VARCHAR(3) NOT NULL,
  MEAN_EAN11 VARCHAR(18) NOT NULL,
  A304_DATAB DATETIME NOT NULL,
  A304_DATBI DATETIME NOT NULL,
  A304_KBETR DECIMAL(11,4) NOT NULL,
  A304_KONWA VARCHAR(5) NOT NULL,
  A073_DATAB DATETIME NOT NULL,
  A073_DATBI DATETIME NOT NULL,
  A073_KBETR DECIMAL(11,4) NOT NULL,
  A073_KONWA VARCHAR(5) NOT NULL
);

CREATE TABLE voyageone_cms.cms_zz_worktable_bcbg_styles
(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  styleID VARCHAR(300) NOT NULL,
  productDesc VARCHAR(2000) NOT NULL,
  productImgURLs VARCHAR(2000) NOT NULL
);