package com.voyageone.web2.cms.views.mapping.feed;

import com.voyageone.common.configs.Enums.ChannelConfigEnums;
import com.voyageone.web2.cms.bean.setting.mapping.feed.SetMappingBean;
import com.voyageone.web2.core.bean.UserSessionBean;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Jonas, 12/10/15
 * @version 2.0.0
 * @since 2.0.0
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration("classpath*:META-INF/context-web2.xml")
public class CmsFeedMappingServiceTest {

    @Autowired
    private CmsFeedMappingService cmsFeedMappingService;

    private UserSessionBean userSessionBean = new UserSessionBean() {{
        setUserName("wms");
        setSelChannel(ChannelConfigEnums.Channel.SN);
    }};

	/**
     * 初始化jewelry店的feed->master的类目匹配
     * @throws Exception
     */
    @Test
    public void testCategoryMappingJewelry() throws Exception {

        List<String> lstFeedPath = new ArrayList<>();
        List<String> lstMasterPath = new ArrayList<>();

//        lstFeedPath.add("Bracelets");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
//        lstFeedPath.add("Bracelets-Bangles");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Agate");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Bangles-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>手饰");
        lstFeedPath.add("Bracelets-Bangles-Moonstone");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Mother－of－Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Bangles-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Bangles-Onyx");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Opal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Bangles-Peridot");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Ruby");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Bangles-Topaz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
//        lstFeedPath.add("Bracelets-Beads");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Beads-Agate");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Beads-Crystal");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Beads-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Beads-Glass");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Beads-Hematite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Beads-Moonstone");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Beads-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Beads-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Beads-Onyx");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Beads-Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Beads-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Beads-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>手饰");
//        lstFeedPath.add("Bracelets-Chains");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Chains-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Chains-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Chains-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Chains-Topaz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
//        lstFeedPath.add("Bracelets-Charm");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Charm-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Charm-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Charm-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>手饰");
        lstFeedPath.add("Bracelets-Charm-Multi");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Charm-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Charm-Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Charm-Pietersite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Charm-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>手饰");
//        lstFeedPath.add("Bracelets-Cuff");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Cuff-Agate");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Cuff-Chalcedony");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Cuff-Citrine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Cuff-Crystal");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Cuff-Cubic Zirconia");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Cuff-Garnet");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Cuff-Labradorite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Cuff-Lapis");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Cuff-Mother－of－Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Cuff-Multi");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Cuff-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Cuff-Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Cuff-Peridot");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Cuff-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Cuff-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>手饰");
        lstFeedPath.add("Bracelets-Cuff-Tiger's Eye");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手镯");
        lstFeedPath.add("Bracelets-Cuff-Topaz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Cuff-Turquoise");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
//        lstFeedPath.add("Bracelets-Links");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Agate");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Amazonite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Aquamarine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Links-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>手饰");
        lstFeedPath.add("Bracelets-Links-Jade");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Links-Onyx");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Opal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Links-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>手饰");
        lstFeedPath.add("Bracelets-Links-Tiger's Eye");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Topaz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Turquoise");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Links-Variscite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
//        lstFeedPath.add("Bracelets-NOT_APPLICABLE");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-NOT_APPLICABLE-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-NOT_APPLICABLE-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
//        lstFeedPath.add("Bracelets-Stretch");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Stretch-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Stretch-Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Stretch-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>手饰");
//        lstFeedPath.add("Bracelets-Tennis");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Tennis-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Tennis-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Tennis-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>手饰");
        lstFeedPath.add("Bracelets-Tennis-Emerald");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Tennis-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Tennis-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Tennis-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Tennis-Rhodochrosite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>手链");
        lstFeedPath.add("Bracelets-Tennis-Ruby");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Tennis-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Bracelets-Tennis-Tanzanite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
//        lstFeedPath.add("Charms");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
//        lstFeedPath.add("Charms-NOT_APPLICABLE");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Charms-NOT_APPLICABLE-Crystal");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Charms-NOT_APPLICABLE-Diamond");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Charms-NOT_APPLICABLE-Enamel");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Charms-NOT_APPLICABLE-Mother－of－Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Charms-NOT_APPLICABLE-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Charms-NOT_APPLICABLE-Onyx");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Charms-NOT_APPLICABLE-Ruby");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Charms-NOT_APPLICABLE-Sapphire");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Charms-NOT_APPLICABLE-Topaz");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
//        lstFeedPath.add("Cuff Links/Tie Bars");	lstMasterPath.add("不知如何匹配的类目");
//        lstFeedPath.add("Cuff Links/Tie Bars-NOT_APPLICABLE");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Cuff Links/Tie Bars-NOT_APPLICABLE-Diamond");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Cuff Links/Tie Bars-NOT_APPLICABLE-Hematite");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Cuff Links/Tie Bars-NOT_APPLICABLE-Jade");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Cuff Links/Tie Bars-NOT_APPLICABLE-Multi");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Cuff Links/Tie Bars-NOT_APPLICABLE-No Stone");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Cuff Links/Tie Bars-NOT_APPLICABLE-Onyx");	lstMasterPath.add("不知如何匹配的类目");
//        lstFeedPath.add("Earrings");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
//        lstFeedPath.add("Earrings-Chandelier");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Chandelier-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Chandelier-Chalcedony");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Chandelier-Crystal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Chandelier-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>耳饰");
        lstFeedPath.add("Earrings-Chandelier-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Chandelier-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳环");
        lstFeedPath.add("Earrings-Chandelier-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Chandelier-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Chandelier-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Chandelier-Turquoise");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
//        lstFeedPath.add("Earrings-Dangles");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳环");
        lstFeedPath.add("Earrings-Dangles-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>耳饰");
//        lstFeedPath.add("Earrings-Drops");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Agate");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Aquamarine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Aventurine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Carnelian");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Chalcedony");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Citrine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Color");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Coral");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Crystal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳环");
        lstFeedPath.add("Earrings-Drops-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>耳饰");
        lstFeedPath.add("Earrings-Drops-Emerald");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Enamel");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Garnet");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Glass");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳环");
        lstFeedPath.add("Earrings-Drops-Jade");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Kyanite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Labradorite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Lapis");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Malachite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Moonstone");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Morganite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Mother－of－Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>耳饰");
        lstFeedPath.add("Earrings-Drops-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳环");
        lstFeedPath.add("Earrings-Drops-Onyx");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Opal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>耳饰");
        lstFeedPath.add("Earrings-Drops-Peridot");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Pietersite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Prynite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Rhodochrosite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳环");
        lstFeedPath.add("Earrings-Drops-Rhodonite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳环");
        lstFeedPath.add("Earrings-Drops-Ruby");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Shell");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Spinel");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>耳饰");
        lstFeedPath.add("Earrings-Drops-Tiger's Eye");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Topaz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Tourmaline");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Drops-Turquoise");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
//        lstFeedPath.add("Earrings-Hoops");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Aquamarine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Citrine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Coral");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳环");
        lstFeedPath.add("Earrings-Hoops-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>耳饰");
        lstFeedPath.add("Earrings-Hoops-Emerald");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Garnet");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳环");
        lstFeedPath.add("Earrings-Hoops-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>耳饰");
        lstFeedPath.add("Earrings-Hoops-Peridot");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Ruby");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>耳饰");
        lstFeedPath.add("Earrings-Hoops-Topaz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Hoops-Turquoise");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
//        lstFeedPath.add("Earrings-Leverbacks");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Leverbacks-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Leverbacks-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>耳饰");
        lstFeedPath.add("Earrings-Leverbacks-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳环");
        lstFeedPath.add("Earrings-Leverbacks-Onyx");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Leverbacks-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>耳饰");
        lstFeedPath.add("Earrings-Leverbacks-Ruby");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Leverbacks-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Leverbacks-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>耳饰");
//        lstFeedPath.add("Earrings-Studs");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Aquamarine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Aventurine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Cameo");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳钉");
        lstFeedPath.add("Earrings-Studs-Citrine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Color");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Crystal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳钉");
        lstFeedPath.add("Earrings-Studs-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>耳饰");
        lstFeedPath.add("Earrings-Studs-Emerald");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Enamel");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳钉");
        lstFeedPath.add("Earrings-Studs-Garnet");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Marcasite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳钉");
        lstFeedPath.add("Earrings-Studs-Morganite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Mother－of－Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>耳饰");
        lstFeedPath.add("Earrings-Studs-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>耳饰>耳钉");
        lstFeedPath.add("Earrings-Studs-Onyx");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Opal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Peridot");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Ruby");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>耳饰");
        lstFeedPath.add("Earrings-Studs-Tanzanite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
        lstFeedPath.add("Earrings-Studs-Topaz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>耳饰");
//        lstFeedPath.add("Money Clips");	lstMasterPath.add("不知如何匹配的类目");
//        lstFeedPath.add("Money Clips-NOT_APPLICABLE");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Money Clips-NOT_APPLICABLE-Agate");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Money Clips-NOT_APPLICABLE-No Stone");	lstMasterPath.add("不知如何匹配的类目");
//        lstFeedPath.add("Necklaces & Pendants");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
//        lstFeedPath.add("Necklaces & Pendants-Beads");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Beads-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Beads-Turquoise");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
//        lstFeedPath.add("Necklaces & Pendants-Chains");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Chains-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项链");
//        lstFeedPath.add("Necklaces & Pendants-Lockets");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Lockets-Crystal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Lockets-Mother－of－Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Lockets-No Stone");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Lockets-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
//        lstFeedPath.add("Necklaces & Pendants-Necklaces");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Agate");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Citrine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Color");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Crystal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项链");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Emerald");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Glass");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项链");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Jasper");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Labradorite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项链");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Onyx");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Peridot");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Pietersite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Rhodolite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项链");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Rhodonite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项链");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Ruby");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Spinel");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Topaz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Necklaces-Turquoise");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
//        lstFeedPath.add("Necklaces & Pendants-NOT_APPLICABLE");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-NOT_APPLICABLE-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
//        lstFeedPath.add("Necklaces & Pendants-Pendants －");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
//        lstFeedPath.add("Necklaces & Pendants-Pendants");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Agate");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Amazonite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Aquamarine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Cameo");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Carnelian");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Chalcedony");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Citrine");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Coral");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Crystal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Emerald");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Enamel");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Garnet");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Glass");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Iolite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Jade");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Jasper");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Labradorite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Lapis");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Morganite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Mother－of－Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Onyx");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Opal");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Peridot");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Rhodonite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Ruby");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Shell");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Spinel");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Tanzanite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Tiger's Eye");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Topaz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Pendants-Turquoise");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
//        lstFeedPath.add("Necklaces & Pendants-Slides");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Slides-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
//        lstFeedPath.add("Necklaces & Pendants-Strands");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Strands-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Strands-Flurite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Strands-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>项坠/吊坠");
        lstFeedPath.add("Necklaces & Pendants-Strands-Onyx");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Strands-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Strands-Peridot");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Strands-Quartz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
        lstFeedPath.add("Necklaces & Pendants-Strands-Sapphire");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>颈饰");
//        lstFeedPath.add("NOT_APPLICABLE");	lstMasterPath.add("不知如何匹配的类目");
//        lstFeedPath.add("NOT_APPLICABLE-NOT_APPLICABLE");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("NOT_APPLICABLE-NOT_APPLICABLE-No Stone");	lstMasterPath.add("不知如何匹配的类目");
//        lstFeedPath.add("Pins/Brooches");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>胸针");
//        lstFeedPath.add("Pins/Brooches-NOT_APPLICABLE");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>胸针");
        lstFeedPath.add("Pins/Brooches-NOT_APPLICABLE-Enamel");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>胸针");
        lstFeedPath.add("Pins/Brooches-NOT_APPLICABLE-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>胸针");
        lstFeedPath.add("Pins/Brooches-NOT_APPLICABLE-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>天然珍珠（新）>胸饰");
        lstFeedPath.add("Pins/Brooches-NOT_APPLICABLE-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>胸饰");
//        lstFeedPath.add("Rings");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
//        lstFeedPath.add("Rings-Band");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Band-Amethyst");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Band-Citrine");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Band-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Band-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>手饰");
        lstFeedPath.add("Rings-Band-Emerald");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Band-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Band-Onyx");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Band-Ruby");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Band-Sapphire");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Band-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>手饰");
        lstFeedPath.add("Rings-Band-Topaz");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
//        lstFeedPath.add("Rings-Cocktail");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Agate");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Amazonite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Amethyst");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Aquamarine");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Chalcedony");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Citrine");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Crystal");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>手饰");
        lstFeedPath.add("Rings-Cocktail-Emerald");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Glass");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Hematite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Kyanite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Labradorite");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Cocktail-Lapis");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Morganite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Mother－of－Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Multi");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Onyx");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Opal");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Pietersite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Quartz");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Rhodonite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Ruby");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Sapphire");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Selenite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Shell");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Cocktail-Tiger's Eye");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Topaz");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Cocktail-Turquoise");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
//        lstFeedPath.add("Rings-Dome");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Dome-Diamond");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Dome-Moonstone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Dome-Mother－of－Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Dome-Multi");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Dome-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Dome-Sapphire");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Dome-Shell");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Dome-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>手饰");
        lstFeedPath.add("Rings-Dome-Topaz");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
//        lstFeedPath.add("Rings-Engagement");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Engagement-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Engagement-Diamond");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
//        lstFeedPath.add("Rings-Enhancer");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Enhancer-Ruby");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
//        lstFeedPath.add("Rings-Fashion");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Amethyst");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Aquamarine");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Aventurine");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Citrine");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Crystal");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Diamond");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Emerald");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Garnet");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Jade");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Morganite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Mother－of－Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Fashion-No Stone");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Onyx");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Opal");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Pearl");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Peridot");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Quartz");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Ruby");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Sapphire");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Spinel");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Swarovski");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Tanzanite");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Topaz");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Fashion-Tourmaline");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
//        lstFeedPath.add("Rings-NOT_APPLICABLE");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-NOT_APPLICABLE-Crystal");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-NOT_APPLICABLE-Diamond");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
//        lstFeedPath.add("Rings-Promise Rings");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Promise Rings-Diamond");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
//        lstFeedPath.add("Rings-Stackable");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Stackable-Cubic Zirconia");	lstMasterPath.add("饰品/流行首饰/时尚饰品新>戒指/指环");
        lstFeedPath.add("Rings-Stackable-Diamond");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Stackable-Multi");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Stackable-Pearl");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Stackable-Peridot");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
        lstFeedPath.add("Rings-Stackable-Swarovski");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>专柜swarovski水晶（新）>手饰");
        lstFeedPath.add("Rings-Stackable-Topaz");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>彩色宝石/贵重宝石>手饰");
//        lstFeedPath.add("Rings-Wedding");	lstMasterPath.add("珠宝/钻石/翡翠/黄金>钻石首饰（新）>手饰");
//        lstFeedPath.add("Sets");	lstMasterPath.add("不知如何匹配的类目");
//        lstFeedPath.add("Sets-NOT_APPLICABLE");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Sets-NOT_APPLICABLE-Amethyst");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Sets-NOT_APPLICABLE-Diamond");	lstMasterPath.add("不知如何匹配的类目");
        lstFeedPath.add("Sets-NOT_APPLICABLE-Pearl");	lstMasterPath.add("不知如何匹配的类目");

        for (int i = 0; i < lstFeedPath.size(); i++) {

            SetMappingBean mappingBean = new SetMappingBean();
            mappingBean.setFrom(lstFeedPath.get(i));
            mappingBean.setTo(lstMasterPath.get(i));

            UserSessionBean userSessionBean = new UserSessionBean();
            userSessionBean.setSelChannelId("010");
            userSessionBean.setUserName("tom");
            cmsFeedMappingService.setMapping(mappingBean, userSessionBean);

        }

    }
}