/*
 * VmsBtFinancialReportModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.bean.vms.report;

import com.voyageone.service.model.vms.VmsBtFinancialReportModel;

/**
 * 
 */
public class FinancialReportBean extends VmsBtFinancialReportModel {
    /**
     * 状态（名字）
     */
    protected String statusName;

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }
}