
package com.voyageone.ws.client.getOrderService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetOrderService", targetNamespace = "http://service.sneakerhead.com", wsdlLocation = "http://222.73.202.154:30001/MySneakerheadService/services/GetOrderService?WSDL")
public class GetOrderService
    extends Service
{

    private final static URL GETORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETORDERSERVICE_EXCEPTION;
    private final static QName GETORDERSERVICE_QNAME = new QName("http://service.sneakerhead.com", "GetOrderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://222.73.202.154:30001/MySneakerheadService/services/GetOrderService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETORDERSERVICE_WSDL_LOCATION = url;
        GETORDERSERVICE_EXCEPTION = e;
    }

    public GetOrderService() {
        super(__getWsdlLocation(), GETORDERSERVICE_QNAME);
    }

    public GetOrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETORDERSERVICE_QNAME, features);
    }

    public GetOrderService(URL wsdlLocation) {
        super(wsdlLocation, GETORDERSERVICE_QNAME);
    }

    public GetOrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETORDERSERVICE_QNAME, features);
    }

    public GetOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetOrderServicePortType
     */
    @WebEndpoint(name = "GetOrderServiceHttpPort")
    public GetOrderServicePortType getGetOrderServiceHttpPort() {
        return super.getPort(new QName("http://service.sneakerhead.com", "GetOrderServiceHttpPort"), GetOrderServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetOrderServicePortType
     */
    @WebEndpoint(name = "GetOrderServiceHttpPort")
    public GetOrderServicePortType getGetOrderServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.sneakerhead.com", "GetOrderServiceHttpPort"), GetOrderServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETORDERSERVICE_EXCEPTION!= null) {
            throw GETORDERSERVICE_EXCEPTION;
        }
        return GETORDERSERVICE_WSDL_LOCATION;
    }

}
