/*
 * CmsBtPromotionExportTaskModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import com.voyageone.base.dao.mysql.BaseModel;
import java.util.Date;

/**
 * CmsBtPromotionExportTaskModel||商品导入任务
 */
public class CmsBtPromotionExportTaskModel extends BaseModel {
    /**
     * 推广活动ID
     */
    protected Integer cmsBtPromotionId;

    /**
     * 导出模板类型:0、按上传模板导出 1、按聚划算模板导出 2、按官方活动(A类)模板导出
     */
    protected Integer templateType;

    /**
     * 导出的文件名
     */
    protected String fileName;

    /**
     * 文件路径
     */
    protected String filePath;

    /**
     * 导入开始时间
     */
    protected Date beginTime;

    /**
     * 导入结束时间
     */
    protected Date endTime;

    protected String parameter;

    /**
     * 导出任务状态：0、等待导出；1、导出成功；2：导出失败
     */
    protected Integer status;

    /**
     * 异常信息
     */
    protected String comment;

    public Integer getCmsBtPromotionId() {
        return cmsBtPromotionId;
    }

    public void setCmsBtPromotionId(Integer cmsBtPromotionId) {
        this.cmsBtPromotionId = cmsBtPromotionId;
    }

    public Integer getTemplateType() {
        return templateType;
    }

    public void setTemplateType(Integer templateType) {
        this.templateType = templateType;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    public Date getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getParameter() {
        return parameter;
    }

    public void setParameter(String parameter) {
        this.parameter = parameter == null ? null : parameter.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}