/*
 * CmsBtWorkloadHistoryModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * workload履历表
 */
public class CmsBtWorkloadHistoryModel extends BaseModel {
    /**
     * 渠道ID
     */
    protected String channelId;

    /**
     * 平台ID
     */
    protected Integer cartId;

    /**
     * 产品GroupID
     */
    protected Integer groupId;

    /**
     * 本次履历的CODE列表，以逗号分隔
     */
    protected String productCodes;

    /**
     * 平台商品ID
     */
    protected String numiid;

    /**
     * 本次履历的处理名
     */
    protected String procName;

    /**
     * 处理发起者
     */
    protected String procModifier;

    /**
     * 处理内容
     */
    protected String procContent;

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    public Integer getCartId() {
        return cartId;
    }

    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public String getProductCodes() {
        return productCodes;
    }

    public void setProductCodes(String productCodes) {
        this.productCodes = productCodes == null ? null : productCodes.trim();
    }

    public String getNumiid() {
        return numiid;
    }

    public void setNumiid(String numiid) {
        this.numiid = numiid == null ? null : numiid.trim();
    }

    public String getProcName() {
        return procName;
    }

    public void setProcName(String procName) {
        this.procName = procName == null ? null : procName.trim();
    }

    public String getProcModifier() {
        return procModifier;
    }

    public void setProcModifier(String procModifier) {
        this.procModifier = procModifier == null ? null : procModifier.trim();
    }

    public String getProcContent() {
        return procContent;
    }

    public void setProcContent(String procContent) {
        this.procContent = procContent == null ? null : procContent.trim();
    }
}