/*
 * CmsBtJmPromotionSpecialExtensionModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import com.voyageone.base.dao.mysql.BaseModel;
import java.math.BigDecimal;

/**
 * 
 */
public class CmsBtJmPromotionSpecialExtensionModel extends BaseModel {
    /**
     * 活动id(关联cms_bt_promotion.id)
     */
    protected Integer promotionId;

    /**
     * 聚美活动id(关联cms_bt_jm_promotion.id)
     */
    protected Integer jmpromotionId;

    /**
     * 活动主要商品品类（英文）
     */
    protected String promotionProductType;

    /**
     * 展示平台（多选）（以数组的JSON形式存储）
     */
    protected String displayPlatform;

    /**
     * 主频道
     */
    protected String mainChannel;

    /**
     * 专场类型
     */
    protected String sessionType;

    /**
     * 关联品类
     */
    protected String sessionCategory;

    /**
     * 预展示频道（多选）（以数组的JSON形式存储）
     */
    protected String preDisplayChannel;

    /**
     * 入口图专场导向文案
     */
    protected String enterGuide;

    /**
     * 首页主标题/专场标题
     */
    protected String mainTitle;

    /**
     * 首页副标题
     */
    protected String subtitle;

    /**
     * 营销标题
     */
    protected String marketingTitle;

    /**
     * 营销文案
     */
    protected String marketingCopywriter;

    /**
     * 促销文案
     */
    protected String promotionalCopy;

    /**
     * 同步移动专场
     */
    protected Boolean syncMobile;

    /**
     * 货架显示隐藏deal
     */
    protected Boolean showHiddenDeal;

    /**
     * 显示0库存deal
     */
    protected Boolean showSoldOutDeal;

    /**
     * 移动端显示
     */
    protected Boolean showMobile;

    /**
     * app端页面标识
     */
    protected String appPageId;

    /**
     * pc端页面标识
     */
    protected String pcPageId;

    /**
     * 分享标题
     */
    protected String shareTitle;

    /**
     * 分享内容
     */
    protected String shareContent;

    /**
     * 直邮信息
     */
    private String directmailType;

    /**
     * 是否满减
     */
    protected Boolean isPromotionFullMinus;

    /**
     * 满减活动-满金额
     */
    protected BigDecimal promotionFullAmount;

    /**
     * 满减活动-减金额
     */
    protected BigDecimal promotionMinusAmount;

    /**
     * 是否每满减
     */
    protected Boolean isPromotionEachfullMinus;

    /**
     * 每满减活动-每满金额
     */
    protected BigDecimal promotionEachfullAmount;

    /**
     * 每满减活动-减金额
     */
    protected BigDecimal promotionEachminusAmount;

    /**
     * 是否聚美承担优惠券
     */
    protected Boolean jmCoupons;

    /**
     * 聚美优惠券金额
     */
    protected BigDecimal jmCouponsMoney;

    /**
     * 是否vo承担优惠券
     */
    protected Boolean voCoupons;

    /**
     * vo优惠券金额
     */
    protected BigDecimal voCouponsMoney;

    public Integer getPromotionId() {
        return promotionId;
    }

    public void setPromotionId(Integer promotionId) {
        this.promotionId = promotionId;
    }

    public Integer getJmpromotionId() {
        return jmpromotionId;
    }

    public void setJmpromotionId(Integer jmpromotionId) {
        this.jmpromotionId = jmpromotionId;
    }

    public String getPromotionProductType() {
        return promotionProductType;
    }

    public void setPromotionProductType(String promotionProductType) {
        this.promotionProductType = promotionProductType == null ? null : promotionProductType.trim();
    }

    public String getDisplayPlatform() {
        return displayPlatform;
    }

    public void setDisplayPlatform(String displayPlatform) {
        this.displayPlatform = displayPlatform == null ? null : displayPlatform.trim();
    }

    public String getMainChannel() {
        return mainChannel;
    }

    public void setMainChannel(String mainChannel) {
        this.mainChannel = mainChannel;
    }

    public String getSessionType() {
        return sessionType;
    }

    public void setSessionType(String sessionType) {
        this.sessionType = sessionType == null ? null : sessionType.trim();
    }

    public String getSessionCategory() {
        return sessionCategory;
    }

    public void setSessionCategory(String sessionCategory) {
        this.sessionCategory = sessionCategory;
    }

    public String getPreDisplayChannel() {
        return preDisplayChannel;
    }

    public void setPreDisplayChannel(String preDisplayChannel) {
        this.preDisplayChannel = preDisplayChannel == null ? null : preDisplayChannel.trim();
    }

    public String getEnterGuide() {
        return enterGuide;
    }

    public void setEnterGuide(String enterGuide) {
        this.enterGuide = enterGuide == null ? null : enterGuide.trim();
    }

    public String getMainTitle() {
        return mainTitle;
    }

    public void setMainTitle(String mainTitle) {
        this.mainTitle = mainTitle == null ? null : mainTitle.trim();
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    public String getMarketingTitle() {
        return marketingTitle;
    }

    public void setMarketingTitle(String marketingTitle) {
        this.marketingTitle = marketingTitle == null ? null : marketingTitle.trim();
    }

    public String getMarketingCopywriter() {
        return marketingCopywriter;
    }

    public void setMarketingCopywriter(String marketingCopywriter) {
        this.marketingCopywriter = marketingCopywriter == null ? null : marketingCopywriter.trim();
    }

    public String getPromotionalCopy() {
        return promotionalCopy;
    }

    public void setPromotionalCopy(String promotionalCopy) {
        this.promotionalCopy = promotionalCopy == null ? null : promotionalCopy.trim();
    }

    public Boolean getSyncMobile() {
        return syncMobile;
    }

    public void setSyncMobile(Boolean syncMobile) {
        this.syncMobile = syncMobile;
    }

    public Boolean getShowHiddenDeal() {
        return showHiddenDeal;
    }

    public void setShowHiddenDeal(Boolean showHiddenDeal) {
        this.showHiddenDeal = showHiddenDeal;
    }

    public Boolean getShowSoldOutDeal() {
        return showSoldOutDeal;
    }

    public void setShowSoldOutDeal(Boolean showSoldOutDeal) {
        this.showSoldOutDeal = showSoldOutDeal;
    }

    public Boolean getShowMobile() {
        return showMobile;
    }

    public void setShowMobile(Boolean showMobile) {
        this.showMobile = showMobile;
    }

    public String getAppPageId() {
        return appPageId;
    }

    public void setAppPageId(String appPageId) {
        this.appPageId = appPageId == null ? null : appPageId.trim();
    }

    public String getPcPageId() {
        return pcPageId;
    }

    public void setPcPageId(String pcPageId) {
        this.pcPageId = pcPageId == null ? null : pcPageId.trim();
    }

    public String getShareTitle() {
        return shareTitle;
    }

    public void setShareTitle(String shareTitle) {
        this.shareTitle = shareTitle == null ? null : shareTitle.trim();
    }

    public String getShareContent() {
        return shareContent;
    }

    public void setShareContent(String shareContent) {
        this.shareContent = shareContent == null ? null : shareContent.trim();
    }

    public Boolean getIsPromotionFullMinus() {
        return isPromotionFullMinus;
    }

    public void setIsPromotionFullMinus(Boolean isPromotionFullMinus) {
        this.isPromotionFullMinus = isPromotionFullMinus;
    }

    public BigDecimal getPromotionFullAmount() {
        return promotionFullAmount;
    }

    public void setPromotionFullAmount(BigDecimal promotionFullAmount) {
        this.promotionFullAmount = promotionFullAmount;
    }

    public BigDecimal getPromotionMinusAmount() {
        return promotionMinusAmount;
    }

    public void setPromotionMinusAmount(BigDecimal promotionMinusAmount) {
        this.promotionMinusAmount = promotionMinusAmount;
    }

    public Boolean getIsPromotionEachfullMinus() {
        return isPromotionEachfullMinus;
    }

    public void setIsPromotionEachfullMinus(Boolean isPromotionEachfullMinus) {
        this.isPromotionEachfullMinus = isPromotionEachfullMinus;
    }

    public BigDecimal getPromotionEachfullAmount() {
        return promotionEachfullAmount;
    }

    public void setPromotionEachfullAmount(BigDecimal promotionEachfullAmount) {
        this.promotionEachfullAmount = promotionEachfullAmount;
    }

    public BigDecimal getPromotionEachminusAmount() {
        return promotionEachminusAmount;
    }

    public void setPromotionEachminusAmount(BigDecimal promotionEachminusAmount) {
        this.promotionEachminusAmount = promotionEachminusAmount;
    }

    public Boolean getJmCoupons() {
        return jmCoupons;
    }

    public void setJmCoupons(Boolean jmCoupons) {
        this.jmCoupons = jmCoupons;
    }

    public BigDecimal getJmCouponsMoney() {
        return jmCouponsMoney;
    }

    public void setJmCouponsMoney(BigDecimal jmCouponsMoney) {
        this.jmCouponsMoney = jmCouponsMoney;
    }

    public Boolean getVoCoupons() {
        return voCoupons;
    }

    public void setVoCoupons(Boolean voCoupons) {
        this.voCoupons = voCoupons;
    }

    public BigDecimal getVoCouponsMoney() {
        return voCouponsMoney;
    }

    public void setVoCouponsMoney(BigDecimal voCouponsMoney) {
        this.voCouponsMoney = voCouponsMoney;
    }

    public String getDirectmailType() {
        return directmailType;
    }

    public void setDirectmailType(String directmailType) {
        this.directmailType = directmailType;
    }
}