/*
 * CmsBtShelvesProductExample.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CmsBtShelvesProductExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public CmsBtShelvesProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShelvesIdIsNull() {
            addCriterion("`shelves_id` is null");
            return (Criteria) this;
        }

        public Criteria andShelvesIdIsNotNull() {
            addCriterion("`shelves_id` is not null");
            return (Criteria) this;
        }

        public Criteria andShelvesIdEqualTo(Integer value) {
            addCriterion("`shelves_id` =", value, "shelvesId");
            return (Criteria) this;
        }

        public Criteria andShelvesIdNotEqualTo(Integer value) {
            addCriterion("`shelves_id` <>", value, "shelvesId");
            return (Criteria) this;
        }

        public Criteria andShelvesIdGreaterThan(Integer value) {
            addCriterion("`shelves_id` >", value, "shelvesId");
            return (Criteria) this;
        }

        public Criteria andShelvesIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`shelves_id` >=", value, "shelvesId");
            return (Criteria) this;
        }

        public Criteria andShelvesIdLessThan(Integer value) {
            addCriterion("`shelves_id` <", value, "shelvesId");
            return (Criteria) this;
        }

        public Criteria andShelvesIdLessThanOrEqualTo(Integer value) {
            addCriterion("`shelves_id` <=", value, "shelvesId");
            return (Criteria) this;
        }

        public Criteria andShelvesIdIn(List<Integer> values) {
            addCriterion("`shelves_id` in", values, "shelvesId");
            return (Criteria) this;
        }

        public Criteria andShelvesIdNotIn(List<Integer> values) {
            addCriterion("`shelves_id` not in", values, "shelvesId");
            return (Criteria) this;
        }

        public Criteria andShelvesIdBetween(Integer value1, Integer value2) {
            addCriterion("`shelves_id` between", value1, value2, "shelvesId");
            return (Criteria) this;
        }

        public Criteria andShelvesIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`shelves_id` not between", value1, value2, "shelvesId");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("`product_code` is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("`product_code` is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("`product_code` =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("`product_code` <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("`product_code` >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("`product_code` >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("`product_code` <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("`product_code` <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("`product_code` like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("`product_code` not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("`product_code` in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("`product_code` not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("`product_code` between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("`product_code` not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryIsNull() {
            addCriterion("`cms_inventory` is null");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryIsNotNull() {
            addCriterion("`cms_inventory` is not null");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryEqualTo(Integer value) {
            addCriterion("`cms_inventory` =", value, "cmsInventory");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryNotEqualTo(Integer value) {
            addCriterion("`cms_inventory` <>", value, "cmsInventory");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryGreaterThan(Integer value) {
            addCriterion("`cms_inventory` >", value, "cmsInventory");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("`cms_inventory` >=", value, "cmsInventory");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryLessThan(Integer value) {
            addCriterion("`cms_inventory` <", value, "cmsInventory");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryLessThanOrEqualTo(Integer value) {
            addCriterion("`cms_inventory` <=", value, "cmsInventory");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryIn(List<Integer> values) {
            addCriterion("`cms_inventory` in", values, "cmsInventory");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryNotIn(List<Integer> values) {
            addCriterion("`cms_inventory` not in", values, "cmsInventory");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryBetween(Integer value1, Integer value2) {
            addCriterion("`cms_inventory` between", value1, value2, "cmsInventory");
            return (Criteria) this;
        }

        public Criteria andCmsInventoryNotBetween(Integer value1, Integer value2) {
            addCriterion("`cms_inventory` not between", value1, value2, "cmsInventory");
            return (Criteria) this;
        }

        public Criteria andCartInventoryIsNull() {
            addCriterion("`cart_inventory` is null");
            return (Criteria) this;
        }

        public Criteria andCartInventoryIsNotNull() {
            addCriterion("`cart_inventory` is not null");
            return (Criteria) this;
        }

        public Criteria andCartInventoryEqualTo(Integer value) {
            addCriterion("`cart_inventory` =", value, "cartInventory");
            return (Criteria) this;
        }

        public Criteria andCartInventoryNotEqualTo(Integer value) {
            addCriterion("`cart_inventory` <>", value, "cartInventory");
            return (Criteria) this;
        }

        public Criteria andCartInventoryGreaterThan(Integer value) {
            addCriterion("`cart_inventory` >", value, "cartInventory");
            return (Criteria) this;
        }

        public Criteria andCartInventoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("`cart_inventory` >=", value, "cartInventory");
            return (Criteria) this;
        }

        public Criteria andCartInventoryLessThan(Integer value) {
            addCriterion("`cart_inventory` <", value, "cartInventory");
            return (Criteria) this;
        }

        public Criteria andCartInventoryLessThanOrEqualTo(Integer value) {
            addCriterion("`cart_inventory` <=", value, "cartInventory");
            return (Criteria) this;
        }

        public Criteria andCartInventoryIn(List<Integer> values) {
            addCriterion("`cart_inventory` in", values, "cartInventory");
            return (Criteria) this;
        }

        public Criteria andCartInventoryNotIn(List<Integer> values) {
            addCriterion("`cart_inventory` not in", values, "cartInventory");
            return (Criteria) this;
        }

        public Criteria andCartInventoryBetween(Integer value1, Integer value2) {
            addCriterion("`cart_inventory` between", value1, value2, "cartInventory");
            return (Criteria) this;
        }

        public Criteria andCartInventoryNotBetween(Integer value1, Integer value2) {
            addCriterion("`cart_inventory` not between", value1, value2, "cartInventory");
            return (Criteria) this;
        }

        public Criteria andSalePriceIsNull() {
            addCriterion("`sale_price` is null");
            return (Criteria) this;
        }

        public Criteria andSalePriceIsNotNull() {
            addCriterion("`sale_price` is not null");
            return (Criteria) this;
        }

        public Criteria andSalePriceEqualTo(Double value) {
            addCriterion("`sale_price` =", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceNotEqualTo(Double value) {
            addCriterion("`sale_price` <>", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceGreaterThan(Double value) {
            addCriterion("`sale_price` >", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceGreaterThanOrEqualTo(Double value) {
            addCriterion("`sale_price` >=", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceLessThan(Double value) {
            addCriterion("`sale_price` <", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceLessThanOrEqualTo(Double value) {
            addCriterion("`sale_price` <=", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceIn(List<Double> values) {
            addCriterion("`sale_price` in", values, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceNotIn(List<Double> values) {
            addCriterion("`sale_price` not in", values, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceBetween(Double value1, Double value2) {
            addCriterion("`sale_price` between", value1, value2, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceNotBetween(Double value1, Double value2) {
            addCriterion("`sale_price` not between", value1, value2, "salePrice");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andImageIsNull() {
            addCriterion("`image` is null");
            return (Criteria) this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("`image` is not null");
            return (Criteria) this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("`image` =", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("`image` <>", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("`image` >", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("`image` >=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("`image` <", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("`image` <=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("`image` like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("`image` not like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("`image` in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("`image` not in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("`image` between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("`image` not between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andNumIidIsNull() {
            addCriterion("`num_iid` is null");
            return (Criteria) this;
        }

        public Criteria andNumIidIsNotNull() {
            addCriterion("`num_iid` is not null");
            return (Criteria) this;
        }

        public Criteria andNumIidEqualTo(String value) {
            addCriterion("`num_iid` =", value, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidNotEqualTo(String value) {
            addCriterion("`num_iid` <>", value, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidGreaterThan(String value) {
            addCriterion("`num_iid` >", value, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidGreaterThanOrEqualTo(String value) {
            addCriterion("`num_iid` >=", value, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidLessThan(String value) {
            addCriterion("`num_iid` <", value, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidLessThanOrEqualTo(String value) {
            addCriterion("`num_iid` <=", value, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidLike(String value) {
            addCriterion("`num_iid` like", value, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidNotLike(String value) {
            addCriterion("`num_iid` not like", value, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidIn(List<String> values) {
            addCriterion("`num_iid` in", values, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidNotIn(List<String> values) {
            addCriterion("`num_iid` not in", values, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidBetween(String value1, String value2) {
            addCriterion("`num_iid` between", value1, value2, "numIid");
            return (Criteria) this;
        }

        public Criteria andNumIidNotBetween(String value1, String value2) {
            addCriterion("`num_iid` not between", value1, value2, "numIid");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlIsNull() {
            addCriterion("`platform_image_url` is null");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlIsNotNull() {
            addCriterion("`platform_image_url` is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlEqualTo(String value) {
            addCriterion("`platform_image_url` =", value, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlNotEqualTo(String value) {
            addCriterion("`platform_image_url` <>", value, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlGreaterThan(String value) {
            addCriterion("`platform_image_url` >", value, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("`platform_image_url` >=", value, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlLessThan(String value) {
            addCriterion("`platform_image_url` <", value, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlLessThanOrEqualTo(String value) {
            addCriterion("`platform_image_url` <=", value, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlLike(String value) {
            addCriterion("`platform_image_url` like", value, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlNotLike(String value) {
            addCriterion("`platform_image_url` not like", value, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlIn(List<String> values) {
            addCriterion("`platform_image_url` in", values, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlNotIn(List<String> values) {
            addCriterion("`platform_image_url` not in", values, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlBetween(String value1, String value2) {
            addCriterion("`platform_image_url` between", value1, value2, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageUrlNotBetween(String value1, String value2) {
            addCriterion("`platform_image_url` not between", value1, value2, "platformImageUrl");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdIsNull() {
            addCriterion("`platform_image_id` is null");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdIsNotNull() {
            addCriterion("`platform_image_id` is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdEqualTo(String value) {
            addCriterion("`platform_image_id` =", value, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdNotEqualTo(String value) {
            addCriterion("`platform_image_id` <>", value, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdGreaterThan(String value) {
            addCriterion("`platform_image_id` >", value, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdGreaterThanOrEqualTo(String value) {
            addCriterion("`platform_image_id` >=", value, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdLessThan(String value) {
            addCriterion("`platform_image_id` <", value, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdLessThanOrEqualTo(String value) {
            addCriterion("`platform_image_id` <=", value, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdLike(String value) {
            addCriterion("`platform_image_id` like", value, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdNotLike(String value) {
            addCriterion("`platform_image_id` not like", value, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdIn(List<String> values) {
            addCriterion("`platform_image_id` in", values, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdNotIn(List<String> values) {
            addCriterion("`platform_image_id` not in", values, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdBetween(String value1, String value2) {
            addCriterion("`platform_image_id` between", value1, value2, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andPlatformImageIdNotBetween(String value1, String value2) {
            addCriterion("`platform_image_id` not between", value1, value2, "platformImageId");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("`creater` is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("`creater` is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("`creater` =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("`creater` <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("`creater` >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("`creater` >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("`creater` <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("`creater` <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("`creater` like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("`creater` not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("`creater` in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("`creater` not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("`creater` between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("`creater` not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("`created` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("`created` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("`created` =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("`created` <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("`created` >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("`created` >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("`created` <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("`created` <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("`created` in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("`created` not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("`created` between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("`created` not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("`modifier` is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("`modifier` is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("`modifier` =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("`modifier` <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("`modifier` >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("`modifier` >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("`modifier` <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("`modifier` <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("`modifier` like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("`modifier` not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("`modifier` in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("`modifier` not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("`modifier` between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("`modifier` not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("`modified` is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("`modified` is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("`modified` =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("`modified` <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("`modified` >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("`modified` >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("`modified` <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("`modified` <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("`modified` in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("`modified` not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("`modified` between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("`modified` not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("`sort` is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("`sort` is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("`sort` =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("`sort` <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("`sort` >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("`sort` >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("`sort` <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("`sort` <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("`sort` in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("`sort` not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("`sort` between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("`sort` not between", value1, value2, "sort");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}