/*
 * CmsBtJmPromotionTagProductModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * 
 */
public class CmsBtJmPromotionTagProductModel extends BaseModel {
    protected String channelId;

    protected Integer cmsBtJmPromotionProductId;

    protected Integer cmsBtTagId;

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    public Integer getCmsBtJmPromotionProductId() {
        return cmsBtJmPromotionProductId;
    }

    public void setCmsBtJmPromotionProductId(Integer cmsBtJmPromotionProductId) {
        this.cmsBtJmPromotionProductId = cmsBtJmPromotionProductId;
    }

    public Integer getCmsBtTagId() {
        return cmsBtTagId;
    }

    public void setCmsBtTagId(Integer cmsBtTagId) {
        this.cmsBtTagId = cmsBtTagId;
    }
}