/*
 * CmsBtPromotionModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import com.voyageone.base.dao.mysql.BaseModel;
import java.util.Date;

/**
 * 
 */
public class CmsBtPromotionModel extends BaseModel {
    protected String channelId;

    protected Integer cartId;

    /**
     * 1:Open 0:Close
     */
    protected Integer promotionStatus;

    protected String promotionName;

    protected String preSaleEnd;

    protected String preSaleStart;

    /**
     * 预热开始时间
     */
    protected String prePeriodStart;

    /**
     * 预热结束时间
     */
    protected String prePeriodEnd;

    /**
     * 活动开始
     */
    protected String activityStart;

    /**
     * 活动结束
     */
    protected String activityEnd;

    /**
     * 0代表不适用特价宝
     */
    protected String tejiabaoId;

    /**
     * 1:促销  2:批量刷价格 3:价格披露 4:库存隔离
     */
    protected String promotionType;

    protected Integer refTagId;

    protected Integer active;

    /**
     * 是否是全店特价宝的活动
     */
    protected Integer isAllPromotion;

    protected Integer promotionId;

    /**
     * 0:实时 1:定时
     */
    protected Integer triggerType;

    protected Date triggerTime;

    /**
     * mq的消息id
     */
    protected String mqId;

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    public Integer getCartId() {
        return cartId;
    }

    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    public Integer getPromotionStatus() {
        return promotionStatus;
    }

    public void setPromotionStatus(Integer promotionStatus) {
        this.promotionStatus = promotionStatus;
    }

    public String getPromotionName() {
        return promotionName;
    }

    public void setPromotionName(String promotionName) {
        this.promotionName = promotionName == null ? null : promotionName.trim();
    }

    public String getPreSaleEnd() {
        return preSaleEnd;
    }

    public void setPreSaleEnd(String preSaleEnd) {
        this.preSaleEnd = preSaleEnd == null ? null : preSaleEnd.trim();
    }

    public String getPreSaleStart() {
        return preSaleStart;
    }

    public void setPreSaleStart(String preSaleStart) {
        this.preSaleStart = preSaleStart == null ? null : preSaleStart.trim();
    }

    public String getPrePeriodStart() {
        return prePeriodStart;
    }

    public void setPrePeriodStart(String prePeriodStart) {
        this.prePeriodStart = prePeriodStart == null ? null : prePeriodStart.trim();
    }

    public String getPrePeriodEnd() {
        return prePeriodEnd;
    }

    public void setPrePeriodEnd(String prePeriodEnd) {
        this.prePeriodEnd = prePeriodEnd == null ? null : prePeriodEnd.trim();
    }

    public String getActivityStart() {
        return activityStart;
    }

    public void setActivityStart(String activityStart) {
        this.activityStart = activityStart == null ? null : activityStart.trim();
    }

    public String getActivityEnd() {
        return activityEnd;
    }

    public void setActivityEnd(String activityEnd) {
        this.activityEnd = activityEnd == null ? null : activityEnd.trim();
    }

    public String getTejiabaoId() {
        return tejiabaoId;
    }

    public void setTejiabaoId(String tejiabaoId) {
        this.tejiabaoId = tejiabaoId == null ? null : tejiabaoId.trim();
    }

    public String getPromotionType() {
        return promotionType;
    }

    public void setPromotionType(String promotionType) {
        this.promotionType = promotionType == null ? null : promotionType.trim();
    }

    public Integer getRefTagId() {
        return refTagId;
    }

    public void setRefTagId(Integer refTagId) {
        this.refTagId = refTagId;
    }

    public Integer getActive() {
        return active;
    }

    public void setActive(Integer active) {
        this.active = active;
    }

    public Integer getIsAllPromotion() {
        return isAllPromotion;
    }

    public void setIsAllPromotion(Integer isAllPromotion) {
        this.isAllPromotion = isAllPromotion;
    }

    public Integer getPromotionId() {
        return promotionId;
    }

    public void setPromotionId(Integer promotionId) {
        this.promotionId = promotionId;
    }

    public Integer getTriggerType() {
        return triggerType;
    }

    public void setTriggerType(Integer triggerType) {
        this.triggerType = triggerType;
    }

    public Date getTriggerTime() {
        return triggerTime;
    }

    public void setTriggerTime(Date triggerTime) {
        this.triggerTime = triggerTime;
    }

    public String getMqId() {
        return mqId;
    }

    public void setMqId(String mqId) {
        this.mqId = mqId == null ? null : mqId.trim();
    }
}