/*
 * CmsBtShelvesTemplateExample.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CmsBtShelvesTemplateExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public CmsBtShelvesTemplateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIsNull() {
            addCriterion("`template_name` is null");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIsNotNull() {
            addCriterion("`template_name` is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateNameEqualTo(String value) {
            addCriterion("`template_name` =", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotEqualTo(String value) {
            addCriterion("`template_name` <>", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameGreaterThan(String value) {
            addCriterion("`template_name` >", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameGreaterThanOrEqualTo(String value) {
            addCriterion("`template_name` >=", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLessThan(String value) {
            addCriterion("`template_name` <", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLessThanOrEqualTo(String value) {
            addCriterion("`template_name` <=", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLike(String value) {
            addCriterion("`template_name` like", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotLike(String value) {
            addCriterion("`template_name` not like", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIn(List<String> values) {
            addCriterion("`template_name` in", values, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotIn(List<String> values) {
            addCriterion("`template_name` not in", values, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameBetween(String value1, String value2) {
            addCriterion("`template_name` between", value1, value2, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotBetween(String value1, String value2) {
            addCriterion("`template_name` not between", value1, value2, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIsNull() {
            addCriterion("`template_type` is null");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIsNotNull() {
            addCriterion("`template_type` is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeEqualTo(Integer value) {
            addCriterion("`template_type` =", value, "templateType");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeNotEqualTo(Integer value) {
            addCriterion("`template_type` <>", value, "templateType");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeGreaterThan(Integer value) {
            addCriterion("`template_type` >", value, "templateType");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`template_type` >=", value, "templateType");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeLessThan(Integer value) {
            addCriterion("`template_type` <", value, "templateType");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`template_type` <=", value, "templateType");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeIn(List<Integer> values) {
            addCriterion("`template_type` in", values, "templateType");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeNotIn(List<Integer> values) {
            addCriterion("`template_type` not in", values, "templateType");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeBetween(Integer value1, Integer value2) {
            addCriterion("`template_type` between", value1, value2, "templateType");
            return (Criteria) this;
        }

        public Criteria andTemplateTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`template_type` not between", value1, value2, "templateType");
            return (Criteria) this;
        }

        public Criteria andClientTypeIsNull() {
            addCriterion("`client_type` is null");
            return (Criteria) this;
        }

        public Criteria andClientTypeIsNotNull() {
            addCriterion("`client_type` is not null");
            return (Criteria) this;
        }

        public Criteria andClientTypeEqualTo(Integer value) {
            addCriterion("`client_type` =", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotEqualTo(Integer value) {
            addCriterion("`client_type` <>", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeGreaterThan(Integer value) {
            addCriterion("`client_type` >", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`client_type` >=", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLessThan(Integer value) {
            addCriterion("`client_type` <", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLessThanOrEqualTo(Integer value) {
            addCriterion("`client_type` <=", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeIn(List<Integer> values) {
            addCriterion("`client_type` in", values, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotIn(List<Integer> values) {
            addCriterion("`client_type` not in", values, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeBetween(Integer value1, Integer value2) {
            addCriterion("`client_type` between", value1, value2, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("`client_type` not between", value1, value2, "clientType");
            return (Criteria) this;
        }

        public Criteria andCartIdIsNull() {
            addCriterion("`cart_id` is null");
            return (Criteria) this;
        }

        public Criteria andCartIdIsNotNull() {
            addCriterion("`cart_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCartIdEqualTo(Integer value) {
            addCriterion("`cart_id` =", value, "cartId");
            return (Criteria) this;
        }

        public Criteria andCartIdNotEqualTo(Integer value) {
            addCriterion("`cart_id` <>", value, "cartId");
            return (Criteria) this;
        }

        public Criteria andCartIdGreaterThan(Integer value) {
            addCriterion("`cart_id` >", value, "cartId");
            return (Criteria) this;
        }

        public Criteria andCartIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`cart_id` >=", value, "cartId");
            return (Criteria) this;
        }

        public Criteria andCartIdLessThan(Integer value) {
            addCriterion("`cart_id` <", value, "cartId");
            return (Criteria) this;
        }

        public Criteria andCartIdLessThanOrEqualTo(Integer value) {
            addCriterion("`cart_id` <=", value, "cartId");
            return (Criteria) this;
        }

        public Criteria andCartIdIn(List<Integer> values) {
            addCriterion("`cart_id` in", values, "cartId");
            return (Criteria) this;
        }

        public Criteria andCartIdNotIn(List<Integer> values) {
            addCriterion("`cart_id` not in", values, "cartId");
            return (Criteria) this;
        }

        public Criteria andCartIdBetween(Integer value1, Integer value2) {
            addCriterion("`cart_id` between", value1, value2, "cartId");
            return (Criteria) this;
        }

        public Criteria andCartIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`cart_id` not between", value1, value2, "cartId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("`channel_id` is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("`channel_id` is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(String value) {
            addCriterion("`channel_id` =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(String value) {
            addCriterion("`channel_id` <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(String value) {
            addCriterion("`channel_id` >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(String value) {
            addCriterion("`channel_id` >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(String value) {
            addCriterion("`channel_id` <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(String value) {
            addCriterion("`channel_id` <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLike(String value) {
            addCriterion("`channel_id` like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotLike(String value) {
            addCriterion("`channel_id` not like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<String> values) {
            addCriterion("`channel_id` in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<String> values) {
            addCriterion("`channel_id` not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(String value1, String value2) {
            addCriterion("`channel_id` between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(String value1, String value2) {
            addCriterion("`channel_id` not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("`remark` is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("`remark` is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("`remark` =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("`remark` <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("`remark` >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("`remark` >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("`remark` <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("`remark` <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("`remark` like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("`remark` not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("`remark` in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("`remark` not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("`remark` between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("`remark` not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andNumPerLineIsNull() {
            addCriterion("`num_per_line` is null");
            return (Criteria) this;
        }

        public Criteria andNumPerLineIsNotNull() {
            addCriterion("`num_per_line` is not null");
            return (Criteria) this;
        }

        public Criteria andNumPerLineEqualTo(Integer value) {
            addCriterion("`num_per_line` =", value, "numPerLine");
            return (Criteria) this;
        }

        public Criteria andNumPerLineNotEqualTo(Integer value) {
            addCriterion("`num_per_line` <>", value, "numPerLine");
            return (Criteria) this;
        }

        public Criteria andNumPerLineGreaterThan(Integer value) {
            addCriterion("`num_per_line` >", value, "numPerLine");
            return (Criteria) this;
        }

        public Criteria andNumPerLineGreaterThanOrEqualTo(Integer value) {
            addCriterion("`num_per_line` >=", value, "numPerLine");
            return (Criteria) this;
        }

        public Criteria andNumPerLineLessThan(Integer value) {
            addCriterion("`num_per_line` <", value, "numPerLine");
            return (Criteria) this;
        }

        public Criteria andNumPerLineLessThanOrEqualTo(Integer value) {
            addCriterion("`num_per_line` <=", value, "numPerLine");
            return (Criteria) this;
        }

        public Criteria andNumPerLineIn(List<Integer> values) {
            addCriterion("`num_per_line` in", values, "numPerLine");
            return (Criteria) this;
        }

        public Criteria andNumPerLineNotIn(List<Integer> values) {
            addCriterion("`num_per_line` not in", values, "numPerLine");
            return (Criteria) this;
        }

        public Criteria andNumPerLineBetween(Integer value1, Integer value2) {
            addCriterion("`num_per_line` between", value1, value2, "numPerLine");
            return (Criteria) this;
        }

        public Criteria andNumPerLineNotBetween(Integer value1, Integer value2) {
            addCriterion("`num_per_line` not between", value1, value2, "numPerLine");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadIsNull() {
            addCriterion("`html_head` is null");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadIsNotNull() {
            addCriterion("`html_head` is not null");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadEqualTo(String value) {
            addCriterion("`html_head` =", value, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadNotEqualTo(String value) {
            addCriterion("`html_head` <>", value, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadGreaterThan(String value) {
            addCriterion("`html_head` >", value, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadGreaterThanOrEqualTo(String value) {
            addCriterion("`html_head` >=", value, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadLessThan(String value) {
            addCriterion("`html_head` <", value, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadLessThanOrEqualTo(String value) {
            addCriterion("`html_head` <=", value, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadLike(String value) {
            addCriterion("`html_head` like", value, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadNotLike(String value) {
            addCriterion("`html_head` not like", value, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadIn(List<String> values) {
            addCriterion("`html_head` in", values, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadNotIn(List<String> values) {
            addCriterion("`html_head` not in", values, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadBetween(String value1, String value2) {
            addCriterion("`html_head` between", value1, value2, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlHeadNotBetween(String value1, String value2) {
            addCriterion("`html_head` not between", value1, value2, "htmlHead");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleIsNull() {
            addCriterion("`html_module_title` is null");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleIsNotNull() {
            addCriterion("`html_module_title` is not null");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleEqualTo(String value) {
            addCriterion("`html_module_title` =", value, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleNotEqualTo(String value) {
            addCriterion("`html_module_title` <>", value, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleGreaterThan(String value) {
            addCriterion("`html_module_title` >", value, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleGreaterThanOrEqualTo(String value) {
            addCriterion("`html_module_title` >=", value, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleLessThan(String value) {
            addCriterion("`html_module_title` <", value, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleLessThanOrEqualTo(String value) {
            addCriterion("`html_module_title` <=", value, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleLike(String value) {
            addCriterion("`html_module_title` like", value, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleNotLike(String value) {
            addCriterion("`html_module_title` not like", value, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleIn(List<String> values) {
            addCriterion("`html_module_title` in", values, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleNotIn(List<String> values) {
            addCriterion("`html_module_title` not in", values, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleBetween(String value1, String value2) {
            addCriterion("`html_module_title` between", value1, value2, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleTitleNotBetween(String value1, String value2) {
            addCriterion("`html_module_title` not between", value1, value2, "htmlModuleTitle");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchIsNull() {
            addCriterion("`html_module_search` is null");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchIsNotNull() {
            addCriterion("`html_module_search` is not null");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchEqualTo(String value) {
            addCriterion("`html_module_search` =", value, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchNotEqualTo(String value) {
            addCriterion("`html_module_search` <>", value, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchGreaterThan(String value) {
            addCriterion("`html_module_search` >", value, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchGreaterThanOrEqualTo(String value) {
            addCriterion("`html_module_search` >=", value, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchLessThan(String value) {
            addCriterion("`html_module_search` <", value, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchLessThanOrEqualTo(String value) {
            addCriterion("`html_module_search` <=", value, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchLike(String value) {
            addCriterion("`html_module_search` like", value, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchNotLike(String value) {
            addCriterion("`html_module_search` not like", value, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchIn(List<String> values) {
            addCriterion("`html_module_search` in", values, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchNotIn(List<String> values) {
            addCriterion("`html_module_search` not in", values, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchBetween(String value1, String value2) {
            addCriterion("`html_module_search` between", value1, value2, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlModuleSearchNotBetween(String value1, String value2) {
            addCriterion("`html_module_search` not between", value1, value2, "htmlModuleSearch");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageIsNull() {
            addCriterion("`html_big_image` is null");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageIsNotNull() {
            addCriterion("`html_big_image` is not null");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageEqualTo(String value) {
            addCriterion("`html_big_image` =", value, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageNotEqualTo(String value) {
            addCriterion("`html_big_image` <>", value, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageGreaterThan(String value) {
            addCriterion("`html_big_image` >", value, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageGreaterThanOrEqualTo(String value) {
            addCriterion("`html_big_image` >=", value, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageLessThan(String value) {
            addCriterion("`html_big_image` <", value, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageLessThanOrEqualTo(String value) {
            addCriterion("`html_big_image` <=", value, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageLike(String value) {
            addCriterion("`html_big_image` like", value, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageNotLike(String value) {
            addCriterion("`html_big_image` not like", value, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageIn(List<String> values) {
            addCriterion("`html_big_image` in", values, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageNotIn(List<String> values) {
            addCriterion("`html_big_image` not in", values, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageBetween(String value1, String value2) {
            addCriterion("`html_big_image` between", value1, value2, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlBigImageNotBetween(String value1, String value2) {
            addCriterion("`html_big_image` not between", value1, value2, "htmlBigImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageIsNull() {
            addCriterion("`html_small_image` is null");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageIsNotNull() {
            addCriterion("`html_small_image` is not null");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageEqualTo(String value) {
            addCriterion("`html_small_image` =", value, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageNotEqualTo(String value) {
            addCriterion("`html_small_image` <>", value, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageGreaterThan(String value) {
            addCriterion("`html_small_image` >", value, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageGreaterThanOrEqualTo(String value) {
            addCriterion("`html_small_image` >=", value, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageLessThan(String value) {
            addCriterion("`html_small_image` <", value, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageLessThanOrEqualTo(String value) {
            addCriterion("`html_small_image` <=", value, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageLike(String value) {
            addCriterion("`html_small_image` like", value, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageNotLike(String value) {
            addCriterion("`html_small_image` not like", value, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageIn(List<String> values) {
            addCriterion("`html_small_image` in", values, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageNotIn(List<String> values) {
            addCriterion("`html_small_image` not in", values, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageBetween(String value1, String value2) {
            addCriterion("`html_small_image` between", value1, value2, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlSmallImageNotBetween(String value1, String value2) {
            addCriterion("`html_small_image` not between", value1, value2, "htmlSmallImage");
            return (Criteria) this;
        }

        public Criteria andHtmlFootIsNull() {
            addCriterion("`html_foot` is null");
            return (Criteria) this;
        }

        public Criteria andHtmlFootIsNotNull() {
            addCriterion("`html_foot` is not null");
            return (Criteria) this;
        }

        public Criteria andHtmlFootEqualTo(String value) {
            addCriterion("`html_foot` =", value, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootNotEqualTo(String value) {
            addCriterion("`html_foot` <>", value, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootGreaterThan(String value) {
            addCriterion("`html_foot` >", value, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootGreaterThanOrEqualTo(String value) {
            addCriterion("`html_foot` >=", value, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootLessThan(String value) {
            addCriterion("`html_foot` <", value, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootLessThanOrEqualTo(String value) {
            addCriterion("`html_foot` <=", value, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootLike(String value) {
            addCriterion("`html_foot` like", value, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootNotLike(String value) {
            addCriterion("`html_foot` not like", value, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootIn(List<String> values) {
            addCriterion("`html_foot` in", values, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootNotIn(List<String> values) {
            addCriterion("`html_foot` not in", values, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootBetween(String value1, String value2) {
            addCriterion("`html_foot` between", value1, value2, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlFootNotBetween(String value1, String value2) {
            addCriterion("`html_foot` not between", value1, value2, "htmlFoot");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1IsNull() {
            addCriterion("`html_clearfix1` is null");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1IsNotNull() {
            addCriterion("`html_clearfix1` is not null");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1EqualTo(String value) {
            addCriterion("`html_clearfix1` =", value, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1NotEqualTo(String value) {
            addCriterion("`html_clearfix1` <>", value, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1GreaterThan(String value) {
            addCriterion("`html_clearfix1` >", value, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1GreaterThanOrEqualTo(String value) {
            addCriterion("`html_clearfix1` >=", value, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1LessThan(String value) {
            addCriterion("`html_clearfix1` <", value, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1LessThanOrEqualTo(String value) {
            addCriterion("`html_clearfix1` <=", value, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1Like(String value) {
            addCriterion("`html_clearfix1` like", value, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1NotLike(String value) {
            addCriterion("`html_clearfix1` not like", value, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1In(List<String> values) {
            addCriterion("`html_clearfix1` in", values, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1NotIn(List<String> values) {
            addCriterion("`html_clearfix1` not in", values, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1Between(String value1, String value2) {
            addCriterion("`html_clearfix1` between", value1, value2, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix1NotBetween(String value1, String value2) {
            addCriterion("`html_clearfix1` not between", value1, value2, "htmlClearfix1");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2IsNull() {
            addCriterion("`html_clearfix2` is null");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2IsNotNull() {
            addCriterion("`html_clearfix2` is not null");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2EqualTo(String value) {
            addCriterion("`html_clearfix2` =", value, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2NotEqualTo(String value) {
            addCriterion("`html_clearfix2` <>", value, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2GreaterThan(String value) {
            addCriterion("`html_clearfix2` >", value, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2GreaterThanOrEqualTo(String value) {
            addCriterion("`html_clearfix2` >=", value, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2LessThan(String value) {
            addCriterion("`html_clearfix2` <", value, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2LessThanOrEqualTo(String value) {
            addCriterion("`html_clearfix2` <=", value, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2Like(String value) {
            addCriterion("`html_clearfix2` like", value, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2NotLike(String value) {
            addCriterion("`html_clearfix2` not like", value, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2In(List<String> values) {
            addCriterion("`html_clearfix2` in", values, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2NotIn(List<String> values) {
            addCriterion("`html_clearfix2` not in", values, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2Between(String value1, String value2) {
            addCriterion("`html_clearfix2` between", value1, value2, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlClearfix2NotBetween(String value1, String value2) {
            addCriterion("`html_clearfix2` not between", value1, value2, "htmlClearfix2");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageIsNull() {
            addCriterion("`html_last_image` is null");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageIsNotNull() {
            addCriterion("`html_last_image` is not null");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageEqualTo(String value) {
            addCriterion("`html_last_image` =", value, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageNotEqualTo(String value) {
            addCriterion("`html_last_image` <>", value, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageGreaterThan(String value) {
            addCriterion("`html_last_image` >", value, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageGreaterThanOrEqualTo(String value) {
            addCriterion("`html_last_image` >=", value, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageLessThan(String value) {
            addCriterion("`html_last_image` <", value, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageLessThanOrEqualTo(String value) {
            addCriterion("`html_last_image` <=", value, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageLike(String value) {
            addCriterion("`html_last_image` like", value, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageNotLike(String value) {
            addCriterion("`html_last_image` not like", value, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageIn(List<String> values) {
            addCriterion("`html_last_image` in", values, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageNotIn(List<String> values) {
            addCriterion("`html_last_image` not in", values, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageBetween(String value1, String value2) {
            addCriterion("`html_last_image` between", value1, value2, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlLastImageNotBetween(String value1, String value2) {
            addCriterion("`html_last_image` not between", value1, value2, "htmlLastImage");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateIsNull() {
            addCriterion("`html_image_template` is null");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateIsNotNull() {
            addCriterion("`html_image_template` is not null");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateEqualTo(String value) {
            addCriterion("`html_image_template` =", value, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateNotEqualTo(String value) {
            addCriterion("`html_image_template` <>", value, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateGreaterThan(String value) {
            addCriterion("`html_image_template` >", value, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateGreaterThanOrEqualTo(String value) {
            addCriterion("`html_image_template` >=", value, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateLessThan(String value) {
            addCriterion("`html_image_template` <", value, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateLessThanOrEqualTo(String value) {
            addCriterion("`html_image_template` <=", value, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateLike(String value) {
            addCriterion("`html_image_template` like", value, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateNotLike(String value) {
            addCriterion("`html_image_template` not like", value, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateIn(List<String> values) {
            addCriterion("`html_image_template` in", values, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateNotIn(List<String> values) {
            addCriterion("`html_image_template` not in", values, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateBetween(String value1, String value2) {
            addCriterion("`html_image_template` between", value1, value2, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andHtmlImageTemplateNotBetween(String value1, String value2) {
            addCriterion("`html_image_template` not between", value1, value2, "htmlImageTemplate");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("`creater` is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("`creater` is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("`creater` =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("`creater` <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("`creater` >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("`creater` >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("`creater` <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("`creater` <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("`creater` like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("`creater` not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("`creater` in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("`creater` not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("`creater` between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("`creater` not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("`created` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("`created` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("`created` =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("`created` <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("`created` >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("`created` >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("`created` <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("`created` <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("`created` in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("`created` not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("`created` between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("`created` not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("`modifier` is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("`modifier` is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("`modifier` =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("`modifier` <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("`modifier` >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("`modifier` >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("`modifier` <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("`modifier` <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("`modifier` like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("`modifier` not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("`modifier` in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("`modifier` not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("`modifier` between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("`modifier` not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("`modified` is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("`modified` is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("`modified` =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("`modified` <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("`modified` >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("`modified` >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("`modified` <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("`modified` <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("`modified` in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("`modified` not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("`modified` between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("`modified` not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andActiveIsNull() {
            addCriterion("`active` is null");
            return (Criteria) this;
        }

        public Criteria andActiveIsNotNull() {
            addCriterion("`active` is not null");
            return (Criteria) this;
        }

        public Criteria andActiveEqualTo(Integer value) {
            addCriterion("`active` =", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotEqualTo(Integer value) {
            addCriterion("`active` <>", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThan(Integer value) {
            addCriterion("`active` >", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("`active` >=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThan(Integer value) {
            addCriterion("`active` <", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThanOrEqualTo(Integer value) {
            addCriterion("`active` <=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveIn(List<Integer> values) {
            addCriterion("`active` in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotIn(List<Integer> values) {
            addCriterion("`active` not in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveBetween(Integer value1, Integer value2) {
            addCriterion("`active` between", value1, value2, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotBetween(Integer value1, Integer value2) {
            addCriterion("`active` not between", value1, value2, "active");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}