/*
 * CmsMtImageCreateFileModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * 
 */
public class CmsMtImageCreateFileModel extends BaseModel {
    /**
     * 请求参数生成的hashcode
     */
    protected Long hashCode;

    /**
     * 渠道id
     */
    protected String channelId;

    /**
     * 模板id
     */
    protected Long templateId;

    /**
     * 上传oss的的文件名
     */
    protected String file;

    /**
     * 本地文件路径
     */
    protected String filePath;

    /**
     * 模板参数
     */
    protected String vparam;

    /**
     * 阿里云oss 文件存放路径 不包含域名shenzhen-vo.oss-cn-shenzhen.aliyuncs.com
     */
    protected String ossFilePath;

    /**
     * 美国cdn 文件存放路径  仅channel:001  需要生成
     */
    protected String usCdnFilePath;

    /**
     * 1:生成成功
     */
    protected Integer state;

    /**
     * oss阿里云上传状态   1:上传成功
     */
    protected Integer ossState;

    /**
     * 美国cdn上传状态     1:上传成功
     */
    protected Integer uscdnState;

    /**
     * 错误信息
     */
    protected String errorMsg;

    /**
     * 错误码
     */
    protected Integer errorCode;

    /**
     * 是否上传美国cdn
     */
    protected Boolean isUploadUsCdn;

    public Long getHashCode() {
        return hashCode;
    }

    public void setHashCode(Long hashCode) {
        this.hashCode = hashCode;
    }

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    public Long getTemplateId() {
        return templateId;
    }

    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    public String getFile() {
        return file;
    }

    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    public String getVparam() {
        return vparam;
    }

    public void setVparam(String vparam) {
        this.vparam = vparam == null ? null : vparam.trim();
    }

    public String getOssFilePath() {
        return ossFilePath;
    }

    public void setOssFilePath(String ossFilePath) {
        this.ossFilePath = ossFilePath == null ? null : ossFilePath.trim();
    }

    public String getUsCdnFilePath() {
        return usCdnFilePath;
    }

    public void setUsCdnFilePath(String usCdnFilePath) {
        this.usCdnFilePath = usCdnFilePath == null ? null : usCdnFilePath.trim();
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getOssState() {
        return ossState;
    }

    public void setOssState(Integer ossState) {
        this.ossState = ossState;
    }

    public Integer getUscdnState() {
        return uscdnState;
    }

    public void setUscdnState(Integer uscdnState) {
        this.uscdnState = uscdnState;
    }

    public String getErrorMsg() {
        return errorMsg;
    }

    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    public Integer getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }

    public Boolean getIsUploadUsCdn() {
        return isUploadUsCdn;
    }

    public void setIsUploadUsCdn(Boolean isUploadUsCdn) {
        this.isUploadUsCdn = isUploadUsCdn;
    }
}