/*
 * CmsMtFeedCustomPropModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * 
 */
public class CmsMtFeedCustomPropModel extends BaseModel {
    protected String channelId;

    /**
     * 如果该店是渠道级属性一致，那么就设置为0
     */
    protected String feedCatPath;

    protected String feedPropOriginal;

    protected String feedPropTranslation;

    protected Integer displayOrder;

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    public String getFeedCatPath() {
        return feedCatPath;
    }

    public void setFeedCatPath(String feedCatPath) {
        this.feedCatPath = feedCatPath == null ? null : feedCatPath.trim();
    }

    public String getFeedPropOriginal() {
        return feedPropOriginal;
    }

    public void setFeedPropOriginal(String feedPropOriginal) {
        this.feedPropOriginal = feedPropOriginal == null ? null : feedPropOriginal.trim();
    }

    public String getFeedPropTranslation() {
        return feedPropTranslation;
    }

    public void setFeedPropTranslation(String feedPropTranslation) {
        this.feedPropTranslation = feedPropTranslation == null ? null : feedPropTranslation.trim();
    }

    public Integer getDisplayOrder() {
        return displayOrder;
    }

    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
}