/*
 * CmsMtColorMappingModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * 颜色对照表
 */
public class CmsMtColorMappingModel extends BaseModel {
    protected String channelId;

    protected Integer cartId;

    protected String colorEn;

    protected String colorCn;

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    public Integer getCartId() {
        return cartId;
    }

    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    public String getColorEn() {
        return colorEn;
    }

    public void setColorEn(String colorEn) {
        this.colorEn = colorEn;
    }

    public String getColorCn() {
        return colorCn;
    }

    public void setColorCn(String colorCn) {
        this.colorCn = colorCn;
    }
}