/*
 * CmsMtChannelConfigKeyModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * 
 */
public class CmsMtChannelConfigKeyModel extends BaseModel {
    /**
     * key
     */
    protected String configKey;

    /**
     * code
     */
    protected String configCode;

    /**
     * 是否启用config_value1
     */
    protected Boolean isConfigValue1;

    /**
     * 是否启用config_value2
     */
    protected Boolean isConfigValue2;

    /**
     * 是否启用config_value3
     */
    protected Boolean isConfigValue3;

    /**
     * 是否平台级别参数(jd,tm,jm等)
     */
    protected Boolean isPlatform;

    /**
     * 备注
     */
    protected String comment;

    protected String sample;

    protected String moddifier;

    public String getConfigKey() {
        return configKey;
    }

    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    public String getConfigCode() {
        return configCode;
    }

    public void setConfigCode(String configCode) {
        this.configCode = configCode == null ? null : configCode.trim();
    }

    public Boolean getIsConfigValue1() {
        return isConfigValue1;
    }

    public void setIsConfigValue1(Boolean isConfigValue1) {
        this.isConfigValue1 = isConfigValue1;
    }

    public Boolean getIsConfigValue2() {
        return isConfigValue2;
    }

    public void setIsConfigValue2(Boolean isConfigValue2) {
        this.isConfigValue2 = isConfigValue2;
    }

    public Boolean getIsConfigValue3() {
        return isConfigValue3;
    }

    public void setIsConfigValue3(Boolean isConfigValue3) {
        this.isConfigValue3 = isConfigValue3;
    }

    public Boolean getIsPlatform() {
        return isPlatform;
    }

    public void setIsPlatform(Boolean isPlatform) {
        this.isPlatform = isPlatform;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    public String getSample() {
        return sample;
    }

    public void setSample(String sample) {
        this.sample = sample == null ? null : sample.trim();
    }

    public String getModdifier() {
        return moddifier;
    }

    public void setModdifier(String moddifier) {
        this.moddifier = moddifier == null ? null : moddifier.trim();
    }
}