/*
 * CmsMtEtkHsCodeModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.cms;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * 
 */
public class CmsMtEtkHsCodeModel extends BaseModel {
    protected Integer cartId;

    protected String catPath;

    protected String etkHsCode;

    protected String etkDescription;

    protected String etkUnit;

    public Integer getCartId() {
        return cartId;
    }

    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    public String getCatPath() {
        return catPath;
    }

    public void setCatPath(String catPath) {
        this.catPath = catPath == null ? null : catPath.trim();
    }

    public String getEtkHsCode() {
        return etkHsCode;
    }

    public void setEtkHsCode(String etkHsCode) {
        this.etkHsCode = etkHsCode == null ? null : etkHsCode.trim();
    }

    public String getEtkDescription() {
        return etkDescription;
    }

    public void setEtkDescription(String etkDescription) {
        this.etkDescription = etkDescription == null ? null : etkDescription.trim();
    }

    public String getEtkUnit() {
        return etkUnit;
    }

    public void setEtkUnit(String etkUnit) {
        this.etkUnit = etkUnit == null ? null : etkUnit.trim();
    }
}