DELIMITER $$
USE `voyageone_cms2`$$
DROP PROCEDURE IF EXISTS `sp_channelConfigKeyAll`$$
CREATE  PROCEDURE `sp_channelConfigKeyAll`()
BEGIN
/*
SELECT CONCAT("insert  into `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)
 values ('",config_key,"','",config_code,"',",is_config_value1,",",is_config_value2,",",is_config_value3,",",is_platform,",'",TRIM(COMMENT),"','",sample,"',now(),'system','system');")
FROM `cms_mt_channel_config_key`
*/
DELETE FROM cms_mt_channel_config_key;
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('ALIAS','',1,0,0,0,'JD上新时,颜色别名使用项目(color:使用产品的color  空/color以外：先用产品code再用color)','29.color_alias / color',NOW(),'system','system');                                                                                                                                                                                                                                                                           
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('APP_SWITCH','',1,0,0,0,'feed->naster导入时, common.fields.appSwtch的默认值','',NOW(),'system','system');                                                                                                                                                                                                                                                                                                                                                  
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('AUTO_APPROVE_PRICE','',1,0,0,0,'价格计算公式使用, 该店铺是否自动同步价格（1：是，0：否），默认值为0；自动同步价格时商品的实际销售价格为用价格公式计算出的指导价；','',NOW(),'system','system');                                                                                                                                                                                                    
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('AUTO_SET_FEED_IMPORT_FLG','',1,0,0,0,'feed的新品导入时，是否自动导入到master（1：是，0：否）, 默认值是0','',NOW(),'system','system');                                                                                                                                                                                                                                                                                                   
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('AUTO_SET_IMAGES6_FLG','',1,0,0,0,'feed -> master导入时, 是否自动将产品原始商品图(images1)复制到PC端自拍商品图(images6), （1：是，0：否）, 默认值是0','',NOW(),'system','system');                                                                                                                                                                                                                                             
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('AUTO_SYNC_CARTS','',1,0,0,0,'feed->master导入时, 变更需要自动同步的平台列表(ALL全部平台，也可用逗号分隔指定平台(例：26,928,929), 默认值为不同步','23,26',NOW(),'system','system');                                                                                                                                                                                                                                      
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('AUTO_SYNC_PRICE_MSRP','',1,0,0,0,'价格计算公式使用, 该店铺是否自动同步MSRP价格（1：是，0：否），默认值为0；自动同步价格时商品的建议售价为用价格公式计算出的建议售价；','',NOW(),'system','system');                                                                                                                                                                                                 
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('CLIENT_PRICE_UNIT','',1,0,0,0,'供WMS的接口使用,和第三方提供的原始价格的单位','',NOW(),'system','system');                                                                                                                                                                                                                                                                                                                                    
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('DEFAULT_PACKAGE_WEIGHT','',1,0,0,0,'价格计算公式使用, 产品包装的默认重量, 默认值是0.5','0.5',NOW(),'system','system');                                                                                                                                                                                                                                                                                                                      
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('FEED_IMPORT_MAX','',1,0,0,0,'feed -> master导入时, 允许每次处理导入feed数据量, 最大不能超过2000, 如果配置超过2000，则按2000来处理','500',NOW(),'system','system');                                                                                                                                                                                                                                                               
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('IMAGE_COMPARE_RULE','',1,0,0,0,'图片生成逻辑, check该渠道feed图片已什么标准判断图片已存在的规则(1:OriginalURL, 2:OriginalImageName)','',NOW(),'system','system');                                                                                                                                                                                                                                                                      
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('IMAGE_UPLOAD_SERVICE','',1,0,0,0,'图片上传后回写product表时, 将images1的图片放到images6图片中的位置(1: images1 - images6, 2: images6 - images1)','',NOW(),'system','system');                                                                                                                                                                                                                                                               
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('LIKING_IMAGE_COPY_FLG','',1,0,0,0,'LIKING子店t同步数据到总店时, 更新时图片复制方式(不包含品牌方商品图images1)(空或0：不复制，1:以UNION方式复制，2：以主店优先方式复制)','',NOW(),'system','system');                                                                                                                                                                                                          
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('MANDATORY_BREAK_THRESHOLD','',1,0,0,0,'价格check时的强制击穿阀值, 即作为向上击穿也作为向下击穿的阀值','20',NOW(),'system','system');                                                                                                                                                                                                                                                                                                  
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('ONLY_UPDATE_PRICE_FLG','',1,0,0,0,'feed -> master导入时, 如果feed数据发生变化是否只同步价格的变化(0: 除了同步价格外还同步其他属性变化, 1: 只同步价格变化), 默认值是0','',NOW(),'system','system');                                                                                                                                                                                                               
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('PLATFORM_ACTIVE','',1,0,0,1,'feed -> master导入时, 生成对应平台的商品状态(ToInStock: 在库 ,ToOnSale: 在售)','',NOW(),'system','system');                                                                                                                                                                                                                                                                                                       
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('PLATFORM_IMAGE_DIRECTORY_ID','',1,0,0,1,'货架管理平台图片上传时, 上传到平台图片空间的目录ID','23 / 119811322689487000',NOW(),'system','system');                                                                                                                                                                                                                                                                                          
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('PRICE','.sx_price',1,0,0,1,'天猫平台上新时使用的哪个价格刷新','23.sx_price / priceSale',NOW(),'system','system');                                                                                                                                                                                                                                                                                                                                
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('PRICE_CALCULATOR','',1,0,0,0,'价格计算公式使用,  是使用何种公式计算价格的(SYSTEM: 按系统价格公式计算 , FORMULA: 按渠道自己的价格公式计算)','',NOW(),'system','system');                                                                                                                                                                                                                                                 
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('PRICE_MSRP_CALC_FORMULA','',1,0,0,0,'如果 PRICE_CALCULATOR = FORMULA时配置, 用于计算中国建议售价的价格','clientMsrpPrice * 1',NOW(),'system','system');                                                                                                                                                                                                                                                                                        
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('PRICE_RETAIL_CALC_FORMULA','',1,0,0,0,'如果 PRICE_CALCULATOR = FORMULA时配置, 用于计算中国指导售价及最终售价的第一次价格','clientNetPrice * 1',NOW(),'system','system');                                                                                                                                                                                                                                                               
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('PRICE_ROUND_UP_FLG','',1,0,0,0,'价格计算公式使用, 价格是否向上取整(1：向上取整，0：不向上取整), 默认值为1','',NOW(),'system','system');                                                                                                                                                                                                                                                                                          
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('PRODUCT_TYPE_FROM_FEED_FLG','',1,0,0,0,'feed -> master导入时, 产品分类是否从feed导入(1：从feed导入，0：不从feed导入运营手动添加), 默认值为0','',NOW(),'system','system');                                                                                                                                                                                                                                                        
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('SAME_ATTR','',1,0,0,0,'自定义属性编辑页面, 用于判断feed的属性是否是统一属性(1: 统一属性, 0: 非统一属性), 对于非统一属性将会根据选择不同的feed类目展示不同的属性内容','',NOW(),'system','system');                                                                                                                                                                                                     
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('SCITEM','',1,1,0,1,'天猫平台上新时， 是否使用全链路库存管理， value1是标示是否使用(1:是, 0:否)value2里是仓库id','23 / 1 / BABCMAXAZRIA001',NOW(),'system','system');                                                                                                                                                                                                                                                            
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('SHIPPING_TYPE','',1,1,0,0,'价格计算公式使用,  店铺发货方式/默认重量','BC / 2.5',NOW(),'system','system');                                                                                                                                                                                                                                                                                                                                      
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('SIZE_TYPE_FROM_FEED_FLG','',1,0,0,0,'feed -> master导入时, 适用人群是否从feed导入时自动创建(1: 是, 0: 否),默认为0：不从feed导入运营手动添加','',NOW(),'system','system');                                                                                                                                                                                                                                                       
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('SPLIT_QUARTER_BY_CODE','',1,0,0,0,'feed -> master导入时, 创建group时是否按照季度来创建(1: 是, 0: 否), 默认值是0','',NOW(),'system','system');                                                                                                                                                                                                                                                                                               
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('SX_SMART','',1,0,0,1,'京东平台智能上新, 对应的京东平台是否开启自动上新(1: 开启, 0: 关闭), 默认值为1','',NOW(),'system','system');                                                                                                                                                                                                                                                                                                 
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('TEJIABAO_ID','',1,1,0,1,'特价宝开启的时候设置','23 / 7 / 1234567',NOW(),'system','system');                                                                                                                                                                                                                                                                                                                                                            
INSERT  INTO `cms_mt_channel_config_key`(`config_key`,`config_code`,`is_config_value1`,`is_config_value2`,`is_config_value3`,`is_platform`,`comment`,`sample`,`created`,`creater`,`moddifier`)                                                                                                                                                                                                                                                                             
 VALUES ('FEED_UPDATE_FLG','0',1,0,0,0,'feed -> master导入时, 导入时如果feed的属性发生变化, 对应的product表中的feed属性是否也同步变化(1: 是, 0: 否), 默认值为0','',NOW(),'system','system');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    END$$

DELIMITER ;