/*
 * VmsBtFeedFileModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.vms;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * 
 */
public class VmsBtFeedFileModel extends BaseModel {
    /**
     * 渠道id
     */
    protected String channelId;

    /**
     * 导入文件名
     */
    protected String fileName;

    /**
     * 1:等待导入；2：导入完成；3：导入错误
     */
    protected String status;

    /**
     * 错误文件路径
     */
    protected String errorFilePath;

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public String getErrorFilePath() {
        return errorFilePath;
    }

    public void setErrorFilePath(String errorFilePath) {
        this.errorFilePath = errorFilePath == null ? null : errorFilePath.trim();
    }
}