/*
 * VmsBtClientAccessLogModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.vms;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * API ACCESS LOG Table
 */
public class VmsBtClientAccessLogModel extends BaseModel {

    /**
     * 客户API ID
     */
    protected String sellerId;

    /**
     * 访问URI
     */
    protected String accessUri;

    /**
     * 访问参数(JSON)
     */
    protected String accessParam;

    /**
     * 返回状态
     */
    protected String resStatus;

    /**
     * 返回数据(JSON)
     */
    protected String resResult;

    /**
     * 返回数据Exception
     */
    protected String resException;

    public String getSellerId() {
        return sellerId;
    }

    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    public String getAccessUri() {
        return accessUri;
    }

    public void setAccessUri(String accessUri) {
        this.accessUri = accessUri == null ? null : accessUri.trim();
    }

    public String getAccessParam() {
        return accessParam;
    }

    public void setAccessParam(String accessParam) {
        this.accessParam = accessParam == null ? null : accessParam.trim();
    }

    public String getResStatus() {
        return resStatus;
    }

    public void setResStatus(String resStatus) {
        this.resStatus = resStatus == null ? null : resStatus.trim();
    }

    public String getResResult() {
        return resResult;
    }

    public void setResResult(String resResult) {
        this.resResult = resResult == null ? null : resResult.trim();
    }

    public String getResException() {
        return resException;
    }

    public void setResException(String resException) {
        this.resException = resException == null ? null : resException.trim();
    }
}