/*
 * VmsBtOrderLogModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.vms;

import com.voyageone.base.dao.mysql.BaseModel;

/**
 * 
 */
public class VmsBtOrderLogModel extends BaseModel {
    /**
     * 渠道id
     */
    protected String channelId;

    /**
     * 物品订单id
     */
    protected String reservationId;

    /**
     * 1:Open；2：Package；3：Shipped；5：Recevied；6：Receive with Error；7：Cancel 
     */
    protected String status;

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    public String getReservationId() {
        return reservationId;
    }

    public void setReservationId(String reservationId) {
        this.reservationId = reservationId == null ? null : reservationId.trim();
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}