/*
 * CtCartDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.com;

import com.voyageone.service.model.com.CtCartModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface CtCartDao {
    List<CtCartModel> selectList(Map<String, Object> map);

    CtCartModel selectOne(Map<String, Object> map);

    int selectCount(Map<String, Object> map);

    CtCartModel select(Integer cartId);

    int insert(CtCartModel record);

    int update(CtCartModel record);

    int delete(Integer cartId);
}