define(function() {
    return {
        "TXT_REMINDER_WITH_COLON": "Reminder：",
        "TXT_LOGOUT": "Logout",
        "TXT_HOME": "Home",
        "TXT_CATEGORY_VIEWS": "-- Category Views --",
        "TXT_CATEGORY_MANAGER": "Categories",
        "TXT_PROMOTION_MANAGER": "Promotions",
        "TXT_PROMOTION_LIST": "Promotion List",
        "TXT_TASK_LIST": "Task List",
        "TXT_SEARCH": "Search",
        "TXT_ADVANCE_SEARCH": "Advance Search",
        "TXT_MAPPING_SETTING": "Mapping Setting",
        "TXT_FEED_CONNECTION_SETTING": "Feed Connection Setting",
        "TXT_PLATFORM_CONNECTION_SETTING": "Platform Connection Setting",
        "TXT_DICTIONARY_INDEX": "Dictionary List",
        "TXT_CHANNEL_MANAGER": "Channel Setting",
        "TXT_CUSTOM_ATTRIBUTE_MANAGER": "Custom Attributes",
        "TXT_COMMON_ATTRIBUTE_MANAGER": "Common Attributes",
        "TXT_FEED_IMPORT_RULE": "Feed Import Rule",
        "TXT_FEED_KEY": "key",
        "TXT_FEED_RULE": "Rule",
        "TXT_AUTHORITY_SETTING": "Authorities",
        "TXT_CONFIGURATION_SETTING": "Configurations",
        "TXT_TRANSLATION_MANAGER": "Translations",
        "TXT_TRANSLATION_INDEX": "Translation List",
        "TXT_SYSTEM_SETTING_MARKETING": "System Setting(Marketing)",
        "TXT_SYSTEM_SETTING_IT": "System Setting(Maintain)",
        "TXT_CATEGORY_INDEX": "Master Category List",
        "TXT_ERROR_MANAGER_MARKETING": "Error List(Marketing)",
        "TXT_ERROR_MANAGER_MAINTENANCE": "Error List(Maintenance)",
        "TXT_CHANNEL_LIST": "Channel List",
        "TXT_CART_LIST": "Cart List",
        "TXT_CATEGORY": "Category",
        "TXT_PRODUCT_STATUS": "Product Status",
        "TXT_PLATFORM_STATUS": "Platform Status",
        "TXT_PRICE": "Price",
        "TXT_CREATE_TIME": "Create Time",
        "TXT_PUBLISH_TIME": "Publish Time",
        "TXT_INVENTORY": "Inventory",
        "TXT_SELECT_NO_VALUE": "Select...",
        "TXT_SELECT_VALUE_1": "Category",
        "TXT_SELECT_VALUE_2": "Brand",
        "TXT_BRAND": "Brand",
        "TXT_FUZZY_SEARCH": "Fuzzy Search",
        "TXT_GROUP_LIST": "Group List",
        "TXT_PRODUCT_LIST": "Product List",
        "TXT_SELECT_ALL": "All",
        "TXT_SALE_PRICE": "Sale Price",
        "TXT_PRIMARY_PRODUCT": "Primary Product",
        "TXT_BASE_PROPERTY": "Base Property",
        "TXT_TIME": "Time",
        "TXT_NUMBER_IID_WITH_COLON": "Number IId:",
        "TXT_GROUP_NAME_WITH_COLON": "Group Name:",
        "TXT_CATEGORY_WITH_COLON": "Category:",
        "TXT_SIZE_TYPE": "Size Type",
        "TXT_SKU_COUNT": "SKU Count",
        "TXT_PRODUCT_CODE_WITH_COLON": "Product Code:",
        "TXT_PRODUCT_NAME_WITH_COLON": "Product Name:",
        "TXT_SKU_PLATFORM_INFO": "Sku Platform",
        "TXT_SKU_INVENTORY": "Sku Inventory",
        "TXT_PROMOTION_AND_TAG": "Promotion & Tags",
        "TXT_CHANNEL_WITH_COLON": "Channel:",
        "TXT_PROMOTION_NAME_WITH_COLON": "Promotion Name:",
        "TXT_PROMOTION_TIME_WITH_COLON": "Promotion Time:",
        "TXT_PROMOTION_TAG_WITH_COLON": "Promotion Tag:",
        "TXT_BULK_UPDATE_PROPERTY": "Bulk Update Product's Fields",
        "TXT_PROPERTY_NAME_WITH_COLON": "Attribute Name:",
        "TXT_PROPERTY_VALUE_WITH_COLON": "Attribute Value:",
        "TXT_FEED_OR_MASTER_CATEGORY_WITH_COLON": "Feed / Master Category:",
        "TXT_LEVEL_CATEGORY": "Level Category",
        "TXT_CURRENT_CATEGORY_WITH_COLON": "Current Category:",
        "TXT_GROUP_DETAIL": "Group Detail",
        "TXT_NUM_IID": "Number IId",
        "TXT_MODEL": "Model",
        "TXT_PLATFORM_CATEGORY": "Platform Category",
        "TXT_MASTER_CATEGORY": "Master Category",
        "TXT_MASTER_CATEGORY_COMMON_FLG": "COMMON",
        "TXT_MASTER_CATEGORY_WITH_COLON": "Master Category:",
        "TXT_FEED_CATEGORY": "Feed Category",
        "TXT_ON_SALE_TIME": "On Sale Time",
        "TXT_MSRP_WITH_COLON": "MSRP:",
        "TXT_RETAIL_PRICE_WITH_COLON": "Retail Price:",
        "TXT_CREATE_TIME_WITH_COLON": "Create Time:",
        "TXT_PUBLISH_TIME_WITH_COLON": "Publish Time:",
        "TXT_ON_SALE_TIME_WITH_COLON": "On Sale Time:",
        "TXT_ALERT": "Alert",
        "TXT_WARNING": "Warning",
        "TXT_CONFIRM": "Confirm",
        "TXT_ALERT_WITH_COLON": "Alert:",
        "TXT_PLATFORM_TYPE": "Platform Type",
        "TXT_TOP_FEED_CATEGORY": "Top Feed Category",
        "TXT_FILTER_CATEGORY": "Filter Category",
        "TXT_FILTER_ATTRIBUTE": "Filter Attribute",
        "TXT_SEQ": "Seq",
        "TXT_LEVEL": "Level",
        "TXT_MAPPING_CATEGORY_OR_FORWARD": "Mapping Category / Forward",
        "TXT_MAPPING_ATTRIBUTE_IS_FINISHED": "Mapping is Done?",
        "TXT_MAPPING_ATTRIBUTE": "Mapping Attributes",
        "TXT_MASTER_DATA_ATTRIBUTE_MAPPING": "Master Data Attribute Mapping",
        "TXT_PLATFORM_ATTRIBUTE_MAPPING": "Platform Attribute Mapping",
        "TXT_ATTRIBUTE_MAPPING": "Attribute Mapping",
        "TXT_ATTRIBUTE_MAPPING_VALUE_TYPE": "Value Type",
        "TXT_ATTRIBUTE_MAPPING_CONDITION_COUNT": "Condition Count",
        "TXT_SUB_LEVEL": "Lev.",
        "TXT_NORMAL_ATTRIBUTE": "Normal Attributes",
        "TXT_COMMON_ATTRIBUTE": "Common Attributes",
        "TXT_SKU_ATTRIBUTE": "SKU Attributes",
        "TXT_COMPLETE": "Done",
        "TXT_INCOMPLETE": "Undo",
        "TXT_MAPPING_CATEGORY_OR_OTHER_PLATFORM": "Mapping Category / Other Platform",
        "TXT_OTHER_PLATFORM": "Other Platform",
        "TXT_MAPPING_VALUE": "Map Value",
        "TXT_DICTIONARY_NAME": "Dictionary Name",
        "TXT_DICTIONARY_COMMENT": "Dictionary Comment",
        "TXT_ACTION": "Action",
        "TXT_UPDATE_TIME": "Update Time",
        "TXT_SHOWING_NO": "The",
        "TXT_PAGE": "Page",
        "TXT_SHOWING": "showing",
        "TXT_OF": "of",
        "TXT_ITEMS": "items",
        "TXT_DICTIONARY_DETAIL": "Dictionary Detail",
        "TXT_NAME": "Name",
        "TXT_IS_UPLOAD_TO_TMALL": "Is upload to TMall?",
        "TXT_TYPE": "Type",
        "TXT_VALUE": "Value",
        "TXT_MASTER_DATA": "Master Data",
        "TXT_FEED_DATA": "Feed Data",
        "TXT_DICTIONARY": "Dictionary",
        "TXT_TEXT": "Text",
        "TXT_CUSTOM": "Custom",
        "TXT_ABSTRACT": "Abstract",
        "TXT_DICTIONARY_CUSTOM": "Dictionary Custom",
        "TXT_DICTIONARY_VALUE": "Dictionary Value",
        "TXT_FORWARD_WITH_COLON": "Forward: ",
        "TXT_UN_SETTING": "[Not Set]",
        "TXT_CATEGORY_NAME": "Category Name",
        "TXT_CATEGORY_ID": "Category ID",
        "TXT_MASTER_CATEGORY_ATTRIBUTE_EDIT": "Edit Master Category Attributes",
        "TXT_PRODUCT_NAME": "Product Name",
        "TXT_ERROR_TYPE": "Error Type",
        "TXT_GROUP_NAME": "Group Name",
        "TXT_ERROR_CODE": "Error Code",
        "TXT_ERROR_MESSAGE": "Error Comment",
        "TXT_ERROR_CREATE_TIME": "Error Created Time",
        "TXT_ERROR_IS_FIX": "Fixed?",
        "TXT_ATTRIBUTE_ID": "Attribute ID",
        "TXT_ATTRIBUTE_NAME": "Attribute Name",
        "TXT_ATTRIBUTE_TYPE": "Attribute Type",
        "TXT_PROMOTION_HISTORY": "Promotion History",
        "TXT_PROMOTION_NAME": "Promotion Name",
        "TXT_PROMOTION_TIME": "Promotion Time",
        "TXT_PROMOTION_PC_ID":"Promotion PCId",
        "TXT_PROMOTION_APP_ID":"Promotion AppId",
        "TXT_MSRP": "MSRP",
        "TXT_PROMOTION_PRICE": "Promotion Price",
        "TXT_CODE_OR_SKU": "Code / Sku",
        "TXT_COMMENT": "Comment",
        "TXT_UPDATE_BY": "Update By",
        "TXT_PRODUCT_DETAIL": "Product Detail",
        "TXT_PRICE_HISTORY": "Price History",
        "TXT_IS_FIX_TRANSLATED": "Is Translation?",
        "TXT_PRODUCT_CODE": "Product Code",
        "TXT_PROMOTION_STATUS":"Promotion Status",
        "TXT_PRICE_TYPE": "Price Type",
        "TXT_DISCOUNT_WORD": "%",
        "TXT_PRODUCT_SKU_DETAIL": "Sku Detail",
        "TXT_PRODUCT_THIRD_PROPERTY": "3rd Custom Attributes",
        "TXT_FEED_ATTRIBUTE": "Feed Attribute",
        "TXT_SELECT_CONDITION": "Select Condition",
        "TXT_IS_WAITING_APPROVE": "Is Edit?",
        "TXT_IS_APPROVED": "Is Approve?",
        "TXT_STATUS": "Status",
        "TXT_PREHEATING_TIME": "preheat Time",
        "TXT_PRE_SALE_TIME": "Pre-sale Time",
        "TXT_IS_START_TE_JIA_BAO": "TeJiaBao?",
        "TXT_TE_JIA_BAO_ID": "TeJiaBao ID",
        "TXT_PROMOTION_DETAIL": "Promotion Detail",
        "TXT_PROMOTION_TAG": "TAG",
        "TXT_RETAIL_PRICE": "Retail Price",
        "TXT_FILE_IMPORT": "Import File",
        "TXT_FILE_WITH_COLON": "File Path:",
        "TXT_PRODUCT_TYPE": "Product Type",
        "TXT_PLATFORM_TYPE_WITH_COLON": "Platform Type:",
        "TXT_INPUT_ONLY_CHAR_AND_NUMBER": "Input Include:English numbers _ .",
        "TXT_REQUIRED": "Required",
        "TXT_TAG": "Tag",
        "TXT_SORT_1": "Sort Attribute 1",
        "TXT_SORT_2": "Sort Attribute 2",
        "TXT_SORT_3": "Sort Attribute 3",
        "TXT_SORT_ASC": "Asc",
        "TXT_SORT_DESC": "Desc",
        "TXT_BEAT_TASK": "Price Disclosure",
        "TXT_UNIQUE": "Unique",
        "TXT_TEMPLATE": "Template",
        "TXT_REVERT_TEMPLATE": "Revert Template",
        "TXT_NEED_VERTICAL": "Update Vertical Image",
        "TXT_VERTICAL_TEMPLATE": "Vertical Template",
        "TXT_VERTICAL_REVERT_TEMPLATE": "Vertical Revert Template",
        "TXT_TASK_DETAIL": "Task Detail",
        "TXT_BEAT_TASK_DETAIL": "Beat Task Detail",
        "TXT_IMPORT_GOOD": "Import Codes",
        "TXT_ADD_MOD_GOOD": "Add/Modify Code",
        "TXT_DOWNLOAD_TASK_DETAIL": "Download Details",
        "TXT_STARTUP_ALL": "Startup All !",
        "TXT_STOP_ALL": "Stop All !",
        "TXT_REVERT_ALL": "Revert All !",
        "TXT_SHOW_ALL": "Show All",
        "TXT_STARTUP": "Startup",
        "TXT_STOP": "Stop",
        "TXT_REVERT": "Revert",
        "TXT_NUMIID_FULL": "Model Platform ID",
        "TXT_CODE_FULL": "Product Code",
        "TXT_CUST_QUERY_ATTR": "Custom Query",
        "TXT_TASK_NAME": "Task Name",
        "TXT_TIME_START": "Start Time",
        "TXT_TIME_END": "End Time",
        "TXT_TASK_TYPE":"Task Type",
        "TXT_TASK_DATE":"Task Date",
        "TXT_TEJIABAO_DETAIL":"Tejiabao Detail",
        "TXT_PENDING":"Pending",
        "TXT_SUCCESS":"Success",
        "TXT_FAIL":"Fail",
        "TXT_PRICE_ATTRIBUTE": "Price Attribute",
        "TXT_SALES_ATTRIBUTE": "Sales Attribute",
        "TXT_USABLE_STOCK":"Usable Stock",
        "TXT_SHOW_FLG": "Show or Not",
        "TXT_OTHER": "Other",
        "TXT_ALL": "All",
        "TXT_READY": "Ready",
        "TXT_WAITING_SEPARATE": "Waiting Separate",
        "TXT_SEPARATING": "Separating",
        "TXT_STOCK_SEPARATE_SUCCESS": "Separate Success",
        "TXT_STOCK_SEPARATE_FAILURE": "Separate Failure",
        "TXT_WAITING_REVERT": "Waiting Revert",
        "TXT_REVERTING": "Reverting",
        "TXT_REVERT_SUCCESS": "Revert Success",
        "TXT_REVERT_FAILURE": "Revert Failure",
        "TXT_CHANGED": "Changed",
        "TXT_SET_ALL": "Set All",
        "TXT_PLEASE_SET_PERCENT": "Please Set Percent",
        "TXT_REAL_TIME_STOCK_STATUS":"Real Time Stock Status",
        "TXT_DYNAMIC":"Dynamic",
        "TXT_AVAILABLE_STOCK":"Available Stock",
        "TXT_ADD_NEW_STOCK_SEPARATE_DETAIL":"Add New Stock Separate Detail",
        "TXT_GET_USABLE_STOCK":"Get Usable Stock",
        "TXT_SEPARATE_QUANTITY":"Quantity",
        "TXT_STOCK_SEPARATE_DETAIL":"Stock Separate Detail",
        "TXT_SEPARATE_TYPE":"Separate Type",
        "TXT_SEPARATE_INCREMENT_QUANTITY":"Separate/Increment Quantity",
        "TXT_STOCK_INCREMENT_SEPARATE":"Stock Increment Separate",
        "TXT_STOCK_INCREMENT_SEPARATE_TASK":"Stock Increment Separate Task",
        "TXT_PLATFORM": "Platform",
        "TXT_ADD_NEW_STOCK_INCREMENT_SEPARATE_TASK":"Add New Stock Increment Separate Task",
        "TXT_PLATFORM_SALE_QUANTITY": "Platform Sale Quantity",
        "TXT_PLATFORM_STOCK_SEPARATE_QUANTITY": "Platform Stock Separate Quantity",
        "TXT_STOCK_INCREMENT_SEPARATE_DETAIL":"Stock Increment Separate Detail",
        "TXT_WAITING_INCREMENT":"Waiting Increment",
        "TXT_INCREASING":"Increasing",
        "TXT_INCREMENT_SUCCESS":"Increment Success",
        "TXT_INCREMENT_FAILURE":"Increment Failure",
        "TXT_UPDATE_FIX_VALUE":"Update Fix Value",
        "TXT_PERSONAL_FINISHED_TRANSLATION": "Per. Translated",
        "TXT_UN_TRANSLATION": "Untranslated",
        "TXT_TRANSLATED": "Translated",
        "TXT_DISTRIBUTION_RULE": "Distribution Rule",
        "TXT_MAIN_PRODUCT": "Main Product",
        "TXT_GET_TASK_COUNT": "Get Tasks Count",
        "TXT_PRODUCT_NAME_WITH_LONG_DESCRIPTION": "Product Name / Description",
        "TXT_LONG_TITLE_WITH_LONG_DESCRIPTION": "Long Title(CN)",
        "TXT_MID_TITLE_WITH_SHORT_DESCRIPTION": "Mid Title /<br> Long Description(CN)",
        "TXT_SHORT_TITLE_WITH_MORE_SHORT_DESCRIPTION": "Short Title /<br> Short Description(CN)",
        "TXT_TRANSLATOR_WIT_COLON": "Translator：",
        "TXT_BASE_ATTRIBUTE": "Common Attribute",
        "TXT_CUST_ATTRIBUTE": "Custmize Attribute",
        "TXT_INCREMENT_TYPE": "Increment Type",
        "TXT_INCREMENT_PERCENTAGE":"Increment percentage",
        "TXT_INCREMENT_CNT":"Increment count",
        "TXT_TRANSSTS_ATTRIBUTE": "Translation status",
        "TXT_IMAGE_MANAGER" : "Image Manage",
        "TXT_WAITING_UPLOAD": "Waiting Upload",
        "TXT_UPLOAD_SUCCESS": "Upload Success",
        "TXT_UPLOAD_FAILED": "Upload Failed",
        "TXT_DATA_TYPE": "Data Type",
        "TXT_SPECIAL_DESCRIPTION": "Special Description",
        "TXT_BRAND_STORY": "Brand Story Image",
        "TXT_SIZE_CHART": "Size Chart",
        "TXT_SHIPPING_DESCRIPTION": "Shipping Description",
        "TXT_INDEX": "Index",
        "TXT_ORIGIN_IMAGE_URL": "Original Image Url",
        "TXT_JM_IMAGE_URL": "JM Image Url",
        "TXT_SET_DEFAULT_VALUE": "Set Image Default Value",
        "TXT_SHIP_STOCK": "Shipping Stock",
        "TXT_RELEASE_DATE": "Release Date",
        "TXT_PRODUCTION_AREA": "Production Area",
        "TXT_SUIT_CROWDS": "Suit Crowds",
        "TXT_WHITE_SQUARE_MODEL": "White Square Model",
        "TXT_PRODUCT_REALLY_MODEL": "Product Really Model",
        "TXT_PRODUCT_UPRIGHT_MODEL": "Product Upright Model",
        "TXT_SPECIAL_NOTE": "Special Note",
        "TXT_ACTIVITY_IMAGE_SETTING": "JM Common Image Setting",
        "TXT_CHANNEL_ID": "Channel ID",
        "TXT_CART_ID": "Cart ID",
        "TXT_ALLOW_USJOI": "Allow USJOI",
        "TXT_FULL_NAME": "Full name",
        "TXT_SHORT_NAME": "short name",
        "TXT_COMPANY": "Company",
        "TXT_IMAGE_URL": "Image URL",


        "TXT_MSG_SEARCH": "Search...",
        "TXT_MSG_INVALID_FEILD": "Please check these fields [ <h4>{{fields}}</h4> ], then try SAVE. (。・`ω´・)",
        "TXT_MSG_PAGE_IS_BUILDING": "This page is building...",
        "TXT_MSG_SEARCH_INDEX_FUZZY_SEARCH": "Search include:Code(use enter to split),Model(use enter to split),Product Name(ZH),Product Name(EN),Long Description(ZH),Long Description(EN)",
        "TXT_MSG_SEARCH_INDEX_FUZZY_SEARCH_2": "Search include:Code(use enter to split),Model(use enter to split)",
        "TXT_MSG_INSERT_SUCCESS": "Insert is successful.",
        "TXT_MSG_INSERT_FAIL": "Insert is fail.",
        "TXT_MSG_UPDATE_SUCCESS": "Update is successful.",
        "TXT_MSG_UPDATE_FAIL": "Update is fail.",
        "TXT_MSG_SET_SUCCESS": "Set is successful.",
        "TXT_MSG_SET_FAIL": "Set is fail.",
        "TXT_MSG_SEPARATE_SUCCESS": "Separate is successful.",
        "TXT_MSG_SEPARATE_FAIL": "Separate is fail.",
        "TXT_MSG_INCREMENT_SUCCESS": "Increment is successful.",
        "TXT_MSG_INCREMENT_FAIL": "Increment is fail.",
        "TXT_MSG_REVERT_SUCCESS": "Revert is successful.",
        "TXT_MSG_REVERT_FAIL": "Revert is fail.",
        "TXT_MSG_NO_ROWS_SELECT": "No rows was selected.",
        "TXT_MSG_NO_PRODUCT_ROWS": "No products was in this table",
        "TXT_MSG_NO_CATEGORY_SELECT": "No leaf category was selected.",
        "TXT_MSG_IS_NOT_CHILE_CATEGORY": "Selected category is not leaf category.",
        "TXT_MSG_CONFIRM_CHANGE_MASTER_PRODUCT": "If you change the primary product,some changing will be happened in platform.<br>Are you sure to continue?",
        "TXT_MSG_CONFIRM_IS_CHANGE_CATEGORY": "If you change the master category,products' attributes will be reset.<br>Are you sure to continue?",
        "TXT_MSG_NO_DATE": "No Rows...",
        "TXT_MSG_PRODUCT_IS_PUBLISHING": "Some products are publishing,cannot change the master category.",
        "TXT_MSG_CONFIRM_FROWARD_PARENT_CATEGORY": "If you forward the parent category, has been mapped attributes will be lost.<br>Are you sure to continue?",
        "TXT_MSG_NO_FIND_FORWARD_CATEGORY": "No parent category can forward.",
        "TXT_MSG_DELETE_ITEM": "Are you sure to delete this item?",
        "TXT_MSG_STARTUP_ITEM": "Are you sure you want to start all?",
        "TXT_MSG_DELETE_SUCCESS": "Delete is successful.",
        "TXT_MSG_DELETE_FAIL": "Delete is fail.",
        "TXT_MSG_NO_DATA_WITH_SAVE": "Please make sure these required items and the table are not empty.",
        "TXT_MSG_NO_PLATFORM_CATEGORY": "Do not get any platform category, please change to another platform, and try again.",
        "TXT_MSG_VALUE_SETTING_COMMENT": "值设定说明：",
        "TXT_MSG_VALUE_SETTING_COMMENT_1": "如果不对属性进行任何值设定，则会使用默认值。",
        "TXT_MSG_VALUE_SETTING_COMMENT_2": "如果对属性进行了多个值设定，则会使用顺序验证可用性。即如果条件，则先验证条件，无条件的，直接为可用。一旦某一条设定生效（可用）",
        "TXT_MSG_CANNOT_GET": "无法取得 ",
        "TXT_MSG_TYPE_VALUE": " 类型的匹配值.",
        "TXT_MSG_MUST_GET_ONE_VALUE": "必须匹配一类值才能保存.",
        "TXT_MSG_NO_VALUE_IS_ON_THE_ATTRIBUTE": "没有匹配到任何属性或内容上.",
        "TXT_MSG_UNVALID_CONDITION": "Unvalid Condition.",
        "TXT_MSG_PRODUCT_CAN_NOT_EDIT": "该商品正在主类目切换中,请稍等...",
        "TXT_MSG_DO_DELETE": "Do you want to delete ",
        "TXT_MSG_DO_SEPARATE": "Do you want to Separate ",
        "TXT_MSG_DO_INCREASE": "Do you want to Increase ",
        "TXT_MSG_DO_REVERT": "Do you want to Revert ",
        "TXT_MSG_LONG_TITLE":"Long title",
        "TXT_MSG_MIDDLE_TITLE":"Middle title",
        "TXT_MSG_SHORT_TITLE":"Short title",
        "TXT_MSG_LONG_DESCRIPTION":"Long description",
        "TXT_MSG_SHORT_DESCRIPTION":"Short description",
        "TXT_MSG_UNVALID_URL": "Unvalid location.",
        "TXT_MSG_NO_UPLOAD": "Please choose your file.",
        "TXT_MSG_CODE_IN_OTHER": "The code you submit, already in other task. Go on ?",
        "TXT_MSG_REIMPORT_BEAT": "Reimport data, will clear last data. Go on (・ˍ・ ? )",
        "TXT_MSG_ERROR_BEAT_ITEM": "The data seems to be wrong. Are you sure you want to change the status of it (⊙＿⊙ ?)",
        "TXT_MSG_IMPORT_DELETE_UPDATE_MSGBOX": "When choosing reset mode, old data will be all deleted. Go on ?",
        "TXT_MSG_INPUT_WORD_LENCHK": "you can input",
        "TXT_MSG_INPUT_WORD_LENCHK2": "words",
        "TXT_MSG_FIELD_VAL_INVALID": "Invalid field (Text) `s value, please follow the prompts to modify.",
        "TXT_MSG_INPUT_WORD_LENLOWLIMIT": "Please enter at least ",
        "TXT_MSG_INPUT_WORD_LENLIMIT": "Maximum length limit of character",
        "TXT_MSG_HAVE_UN_TRANSLATED_TASK": "您还有未完成的翻译项目, 请完成后再获取新的任务!",
        "TXT_MSG_UPLOAD_IMAGE_SUCCESS": "Image upload/refresh success.",
        "TXT_MSG_ACTIVITIES": "Please select the corresponding promotion!",
        "TXT_MSG_IMPORT_MODE": "Import Mode",
        "TXT_MSG_IMPORT_UPDATE": "Update Mode",
        "TXT_MSG_IMPORT_ADD": "Add Mode",
        "TXT_MSG_IMPORT_DELETE_UPDATE": "Reset Mode",
        "TXT_MSG_IMPORT_STATUS_ERROR": "Exist being processed data, these are not saved.",
        "TXT_SEPARATE_PROPORTION":"Separation ratio",
        "TXT_REVERT_TIME":"Revert time",
        "TXT_INCREASING_PRIORITY":"Increase priority",
        "TXT_REDUCED_PRIORITY":"Reduce priority",
        "TXT_IMPORT_ONLY_SKU_AND_INVENTORY":"Import only SKU and inventory",
        "TXT_SEPARATE":"Separate",
        "TXT_SHARE":"Share",
        "TXT_SEPARATE_NEW_TASK":"New Separate Task",


        "BTN_CREATE_TASK": "New Task",
        "BTN_CREATE_BEAT_TASK": "New BEAT Task",
        "BTN_CREATE_TE_JIA_BAO_TASK": "New TeJiaBao Task",
        "BTN_ADD_CONDITION": "Add Condition",
        "BTN_CLEAR": "Clear",
        "BTN_CLOSE": "Close",
        "BTN_TODAY": "Today",
        "BTN_SAVE": "Save",
        "BTN_SEARCH": "Search",
        "BTN_ADD_TO_PROMOTION": "Join Promotion",
        "BTN_ADD_TO_JM_PROMOTION": "Join JM's Promotion",
        "BTN_BATCH_UPDATE_ATTRIBUTE": "Bulk Update",
        "BTN_CHANGE_MASTER_CATEGORY": "Change Master Category",
        "BTN_CANCEL": "Cancel",
        "BTN_EXPORT": "Export",
        "BTN_GO": "Go",
        "BTN_OK": "Ok",
        "BTN_CREATE": "Create",
        "BTN_NEW_DICT_VALUE": "Add dict value",
        "BTN_NEW_DICT_CUS_VALUE": "Add custom value",
        "BTN_NEW_DICTIONARY": "Create Dictionary",
        "BTN_NEW_DICTIONARY_VALUE": "Create Value",
        "BTN_NEW_DICTIONARY_DEFINE": "Create Custom",
        "BTN_SET_PARAM": "Set Param",
        "BTN_NEW_DICT": "New Dict",
        "BTN_NEW_PROMOTION": "Create Promotion",
        "BTN_MAPPING_CATEGORY": "Map Category",
        "BTN_FORWARD": "Forward",
        "BTN_MAPPING_ATTRIBUTE": "Map Attribute",
        "BTN_MAPPING_ATTRIBUTE_COMMON_MAIN": "Common Map Attribute",
        "BTN_OTHER_PLATFORM": "Other Platform",
        "BTN_NEW_ATTRIBUTE": "Add Attribute",
        "BTN_SAVE_ALL": "Save All",
        "BTN_EDIT": "Edit",
        "BTN_DELETE": "Delete",
        "BTN_ADD": "Add",
        "BTN_REFRESH": "Refresh",
        "BTN_PROMOTION_HISTORY": "Promotion History",
        "BTN_PRICE_HISTORY": "Price History",
        "BTN_DOWNLOAD": "Download",
        "BTN_DOWNLOAD_ERROR": "Error log",
        "BTN_IMPORT_PROMOTION_FILE": "Import Promotion File",
        "BTN_CHOOSE_FILE": "Choose File",
        "BTN_IMPORT_FILE": "Import File",
        "BTN_UPLOAD_FILE": "Upload File",
        "BTN_CUSTOMIZE_COLUMNS": "custmize columns",
        "BTN_SET": "Set",
        "BTN_IMPORT_ALL": "Import",
        "BTN_EXPORT_ALL": "Export",
        "BTN_START_REFRESH_ALL": "Start/RefreshAll",
        "BTN_REVERT_ALL": "RevertAll",
        "BTN_START_INCREMENT_ALL": "Start Increment All",
        "BTN_GET_TASK": "Get Tasks",
        "BTN_COMPLETE": "Done",
        "BTN_SET_DEFAULT_VALUE": "Set Default Value",
        "TXT_ACTIVITY_NAME": "Activity name",
        "TXT_PC_MODULE_ID": "PC module ID",
        "TXT_APP_MODULE_ID": "APP module ID",
        "TXT_PROMOTION_DISCOUNT": "Promotion discount",
         "TXT_Do_You_Want_To_Update_ All":"Do you want to  update all",
        "TXT_Do_You_Want_To_Selected":"Do you want to update the selected",
        // 枚举 com.voyageone.cms.enums.BeatFlag 的翻译
        "STOP": "Stop",
        "BEATING": "Running",
        "SUCCESS": "Success",
        "FAIL": "Fail",
        "REVERT": "Reverting",
        "RE_SUCCESS": "Revert Success",
        "RE_FAIL": "Revert Fail",
        "CANT_BEAT": "Info Error",

        /**分页显示*/
        "TXT_PAGER_SIZE": "page-size"
    };
});