define(function(){
    return {
        "TXT_NO_DATA": "没有任何数据。",
        "TXT_IMAGE_STATUS": "图片状态",
        "TXT_REMINDER_WITH_COLON": "温馨提示：",
        "TXT_EDIT_TASK": "编辑当前 Task ",
        "TXT_LOGOUT": "注销",
        "TXT_HOME": "首页",
        "TXT_CATEGORY_VIEWS": "-- 类目视图 --",
        "TXT_FEED_MANAGER": "Feed管理",
        "TXT_FEED_PRODUCT_LIST": "Feed商品一览",
        "TXT_FEED_CATEGORY_LIST": "Feed类目一览",
        "TXT_FEED_BRAND_LIST": "Feed品牌一览",
        "TXT_CATEGORY_MANAGER": "商品管理",
        "TXT_PROMOTION_MANAGER": "活动管理",
        "TXT_PROMOTION_LIST": "活动一览",
        "TXT_PROMOTION_LIST_ALL": "活动总览",
        "TXT_PROMOTION_TASK_LIST": "任务一览",
        "TXT_IMAGE_MANAGER": "素材管理",
        "TXT_IMAGE_DICTIONARY_LIST": "详情页模板一览",
        "TXT_IMAGE_TEMPLATE_LIST": "商品图片模板一览",
        "TXT_IMAGE_COMMON_LIST": "共通图片一览",
        "TXT_IMAGE_SIZE_CHART_LIST": "尺码对照表一览",
        "TXT_IMAGE_PRODUCT_LABEL_LIST": "自定义标签一览",
        "TXT_CHANNEL_MANAGER": "店铺管理",
        "TXT_CHANNEL_CART_CATEGORY_LIST":"店铺内分类一览",
        "TXT_CHANNEL_SALE_INFO_LIST": "店铺销售情况一览",
        "TXT_SEARCH": "检索",
        "TXT_ADVANCE_SEARCH": "高级检索",
        "TXT_MARKETING_ERROR_MANAGER": "运营错误管理",
        "TXT_MARKETING_ERROR_LIST_ALL": "上新错误总览",
        "TXT_MARKETING_ERROR_LIST": "上新错误一览",
        "TXT_MAINTAIN_ERROR_MANAGER": "维护错误管理",
        "TXT_MAINTAIN_ERROR_LIST_ALL": "导入错误总览",
        "TXT_MAINTAIN_ERROR_LIST": "导入错误一览",
        "TXT_MARKETING_SETTING_MANAGER": "运营设置管理",
        "TXT_MARKETING_SETTING_COMMON": "共通设置",
        "TXT_MARKETING_SETTING_COMMON_BLACK_LIST": "黑名单一览",
        "TXT_MARKETING_SETTING_COMMON_SIZE_TYPE_LIST": "使用人群一览",
        "TXT_MARKETING_SETTING_COMMON_STOP_WORDS_LIST": "禁用词一览",
        "TXT_MARKETING_SETTING_COMMON_CUSTOM_ATTRIBUTE_LIST": "自定义属性一览",
        "TXT_MARKETING_SETTING_COMMON_BRANCH_RIGHT_LIST": "子店权限一览",
        "TXT_MARKETING_SETTING_PLATFORM": "平台设置",
        "TXT_MARKETING_SETTING_PLATFORM_CATEGORY_LIST": "平台类目一览",
        "TXT_MARKETING_SETTING_PLATFORM_BRAND_LIST": "平台品牌一览",
        "TXT_MARKETING_SETTING_PLATFORM_DEFAULT_LIST": "平台默认属性一览",
        "TXT_MAINTAIN_SETTING_MANAGER": "维护设置管理",
        "TXT_MAINTAIN_SETTING_ROLE": "权限设置",
        "TXT_MAINTAIN_SETTING_ROLE_MAIN_CATEGORY": "主类目权限设置",
        "TXT_MAINTAIN_SETTING_ROLE_MAIN_BRAND":"主品牌权限设置",
        "TXT_MAINTAIN_SETTING_ROLE_TAX_NUMBER": "税号权限设置",
        "TXT_MAINTAIN_SETTING_ROLE_CART": "平台店权限设置",
        "TXT_MAINTAIN_SETTING_ROLE_CHANNEL": "集合店权限设置",
        "TXT_MAINTAIN_SETTING_ROLE_USER": "账号权限设置",
        "TXT_MAINTAIN_SETTING_CATEGORY": "类目设置",
        "TXT_MAINTAIN_SETTING_CATEGORY_MAIN_CATEGORY_LIST": "主类目一览",
        "TXT_MAINTAIN_SETTING_CATEGORY_PLATFORM_CATEGORY_LIST": "平台类目一览",
        "TXT_MAINTAIN_SETTING_COMMON": "共通设置",
        "TXT_MAINTAIN_SETTING_COMMON_MAIN_PROPERTY_SETTING": "主数据共通属性设置",
        "TXT_MAINTAIN_SETTING_CURRENT_CHANNEL": "当前店铺设置",
        "TXT_MAINTAIN_SETTING_CURRENT_CHANNEL_BLACK_LIST": "黑名单一览",
        "TXT_MAINTAIN_SETTING_CURRENT_CHANNEL_SIZE_TYPE_LIST": "适用人群一览",
        "TXT_MAINTAIN_SETTING_CURRENT_CHANNEL_STOP_WORDS_LIST": "禁用词一览",
        "TXT_MAINTAIN_SETTING_CURRENT_CHANNEL_CUSTOM_ATTRIBUTE_LIST": "自定义属性一览",
        "TXT_MAINTAIN_SETTING_CURRENT_CHANNEL_BRANCH_RIGHT_LIST": "子店权限一览",
        "TXT_MAINTAIN_SETTING_CURRENT_CHANNEL_DICTIONARY_LIST": "词典一览",
        "TXT_MAINTAIN_SETTING_CURRENT_CHANNEL_TOTAL_UPDATE": "全量处理一览",
        "TXT_MAINTAIN_SETTING_CURRENT_CHANNEL_SENIOR_SEARCH": "高权限检索处理",
        "TOOLS_MANAGER": "工具管理",
        "TOOLS_COMMON": "共通处理",
        "TOOLS_COMMON_MASTER_BRAND_MAPPING": "主商品品牌匹配",
        "TOOLS_COMMON_PLATFORM_BRAND_MAPPING": "平台品牌匹配",
        "TOOLS_COMMON_SIZE_TYPE_MAPPING": "使用人群匹配",
        "TOOLS_PRODUCT": "商品处理",
        "TOOLS_PRODUCT_MASTER_CATEGORY_SETTING": "商品类目设置",
        "TOOLS_PRODUCT_TRANSLATION_SETTING": "商品属性翻译",
        "TOOLS_PRODUCT_HSCODE_SETTING": "商品税号设置",
        "TOOLS_PRODUCT_CUSTOM_IMAGES_SETTING": "商品自定义图片任务",
        "TOOLS_PRODUCT_PLATFORM_ATTRIBUTE_SETTING": "平台属性设置",
        "TOOLS_CATEGORY": "类目处理",
        "TOOLS_CATEGORY_FEED_TO_MASTER_MAPPING": "Feed类目匹配主数据类目",
        "TOOLS_CATEGORY_MASTER_TO_PLATFORM_MAPPING": "主数据属性匹配平台属性",
        "TXT_MAPPING_SETTING": "匹配关系设置",
        "TXT_FEED_CONNECTION_SETTING": "Feed匹配关系设置",
        "TXT_PLATFORM_CONNECTION_SETTING": "平台匹配关系设置",
        "TXT_DICTIONARY_INDEX": "字典一览",
        "TXT_ATTRIBUTE":"属性",
        "TXT_CUSTOM_ATTRIBUTE_MANAGER": "自定义属性设置",
        "TXT_COMMON_ATTRIBUTE_MANAGER": "共通属性设置",
        "TXT_FEED_IMPORT_RULE": "Feed输入规则",
        "TXT_FEED_KEY": "key",
        "TXT_FEED_RULE": "Rule",
        "TXT_AUTHORITY_SETTING": "权限设置",
        "TXT_CONFIGURATION_SETTING": "配置设置",
        "TXT_TRANSLATION_MANAGER": "翻译管理",
        "TXT_TRANSLATION_INDEX": "翻译一览",
        "TXT_SYSTEM_SETTING_IT": "系统管理（维护）",
        "TXT_CATEGORY_INDEX": "主类目一览",
        "TXT_ERROR_MANAGER_MARKETING": "异常一览（运营）",
        "TXT_ERROR_MANAGER_MAINTENANCE": "异常一览（维护）",
        "TXT_CHANNEL_LIST": "渠道一览（维护）",
        "TXT_CART_LIST": "Cart一览（维护）",
        "TXT_CATEGORY": "类目",
        "TXT_PRODUCT_STATUS": "产品状态",
        "TXT_PLATFORM_STATUS": "商品平台状态",
        "TXT_MSRP_PRICE": "中国专柜售价",
        "TXT_CREATE_TIME": "创建时间",
        "TXT_PUBLISH_TIME": "发布时间",
        "TXT_INVENTORY": "库存",
        "TXT_SELECT_NO_VALUE": "请选择...",
        "TXT_SELECT_VALUE_1": "Category",
        "TXT_SELECT_VALUE_2": "Brand",
        "TXT_BRAND": "品牌",
        "TXT_FUZZY_SEARCH": "模糊查询",
        "TXT_GROUP_LIST": "GROUP一览",
        "TXT_PRODUCT_LIST": "PRODUCT一览",
        "TXT_EXPORT_LIST": "Export 一览",
        "TXT_SELECT_ALL": "全选",
        "TXT_SALE_PRICE": "最终售价",
        "TXT_PRIMARY_PRODUCT": "主产品",
        "TXT_BASE_PROPERTY": "基础属性",
        "TXT_TIME": "时间",
        "TXT_NUMBER_IID_WITH_COLON": "商品编号",
        "TXT_GROUP_NAME_WITH_COLON": "商品名称",
        "TXT_CATEGORY_WITH_COLON": "类目:",
        "TXT_SIZE_TYPE": "尺码类型",
        "TXT_SKU_COUNT": "SKU数",
        "TXT_PRODUCT_CODE_WITH_COLON": "产品Code:",
        "TXT_PRODUCT_NAME_WITH_COLON": "产品名称:",
        "TXT_SKU_PLATFORM_INFO": "Sku平台信息",
        "TXT_SKU_INVENTORY": "Sku库存",
        "TXT_PROMOTION_AND_TAG": "活动 & 标签",
        "TXT_CHANNEL_WITH_COLON": "渠道:",
        "TXT_PROMOTION_NAME_WITH_COLON": "活动名称:",
        "TXT_PROMOTION_TIME_WITH_COLON": "活动时间:",
        "TXT_PROMOTION_TAG_WITH_COLON": "活动标签:",
        "TXT_BULK_UPDATE_PROPERTY": "批量更新产品属性",
        "TXT_PROPERTY_NAME_WITH_COLON": "属性名",
        "TXT_PROPERTY_VALUE_WITH_COLON": "属性值",
        "TXT_FEED_OR_MASTER_CATEGORY_WITH_COLON": "Feed / 主类目:",
        "TXT_LEVEL_CATEGORY": "级类目",
        "TXT_CURRENT_CATEGORY_WITH_COLON": "当前选择的类目:",
        "TXT_GROUP_DETAIL": "商品详情",
        "TXT_NUM_IID": "商品编号",
        "TXT_MODEL": "款号",
        "TXT_PLATFORM_CATEGORY": "平台类目",
        "TXT_MASTER_CATEGORY": "主类目",
        "TXT_MASTER_CATEGORY_COMMON_FLG": "通用",
        "TXT_MASTER_CATEGORY_WITH_COLON": "主类目:",
        "TXT_FEED_CATEGORY": "Feed类目",
        "TXT_ON_SALE_TIME": "销售时间",
        "TXT_IN_STOCK_TIME": "在库时间",
        "TXT_MSRP_WITH_COLON": "官方售价",
        "TXT_RETAIL_PRICE_WITH_COLON": "指导售价",
        "TXT_CREATE_TIME_WITH_COLON": "创建时间:",
        "TXT_PUBLISH_TIME_WITH_COLON": "发布时间:",
        "TXT_ON_SALE_TIME_WITH_COLON": "销售时间:",
        "TXT_ALERT": "温馨提示",
        "TXT_WARNING": "警告",
        "TXT_CONFIRM": "确认",
        "TXT_ALERT_WITH_COLON": "温馨提示:",
        "TXT_PLATFORM_TYPE": "平台类型",
        "TXT_TOP_FEED_CATEGORY": "顶层Feed类目",
        "TXT_FILTER_CATEGORY": "类目匹配筛选",
        "TXT_FILTER_ATTRIBUTE": "属性匹配筛选",
        "TXT_SEQ": "编号",
        "TXT_LEVEL": "层级",
        "TXT_MAPPING_CATEGORY_OR_FORWARD": "类目匹配 / 继承",
        "TXT_MAPPING_ATTRIBUTE_IS_FINISHED": "属性匹配完成?",
        "TXT_MAPPING_ATTRIBUTE": "属性匹配",
        "TXT_MASTER_DATA_ATTRIBUTE_MAPPING": "主数据属性匹配",
        "TXT_PLATFORM_ATTRIBUTE_MAPPING": "平台属性匹配",
        "TXT_ATTRIBUTE_MAPPING": "属性匹配",
        "TXT_ATTRIBUTE_MAPPING_VALUE_TYPE": "值类型",
        "TXT_ATTRIBUTE_MAPPING_CONDITION_COUNT": "条件个数",
        "TXT_SUB_LEVEL": "级",
        "TXT_NORMAL_ATTRIBUTE": "普通属性",
        "TXT_COMMON_ATTRIBUTE": "共通属性",
        "TXT_SKU_ATTRIBUTE": "SKU属性",
        "TXT_COMPLETE": "已匹配",
        "TXT_INCOMPLETE": "未匹配",
        "TXT_MAPPING_CATEGORY_OR_OTHER_PLATFORM": "类目匹配 / 其他平台",
        "TXT_OTHER_PLATFORM": "其他平台",
        "TXT_MAPPING_VALUE": "值匹配",
        "TXT_DICTIONARY_NAME": "字典名称",
        "TXT_DICTIONARY_COMMENT": "字典内容",
        "TXT_ACTION": "操作",
        "TXT_UPDATE_TIME": "更新时间",
        "TXT_SHOWING_NO": "第",
        "TXT_PAGE": "页",
        "TXT_SHOWING": "显示",
        "TXT_OF": "之",
        "TXT_ITEMS": "件数",
        "TXT_DICTIONARY_DETAIL": "字典详情",
        "TXT_NAME": "名称",
        "TXT_IS_UPLOAD_TO_TMALL": "需要上传天猫 ?",
        "TXT_TYPE": "类型",
        "TXT_VALUE": "值",
        "TXT_MASTER_DATA": "主数据",
        "TXT_FEED_DATA": "品牌数据",
        "TXT_DICTIONARY": "字典",
        "TXT_TEXT": "文本",
        "TXT_CUSTOM": "自定义",
        "TXT_ABSTRACT": "摘要",
        "TXT_DICTIONARY_CUSTOM": "字典自定义设置",
        "TXT_DICTIONARY_VALUE": "字典值设置",
        "TXT_FORWARD_WITH_COLON": "可继承: ",
        "TXT_UN_SETTING": "[未设定]",
        "TXT_CATEGORY_NAME": "类目名称",
        "TXT_CATEGORY_ID": "类目ID",
        "TXT_MASTER_CATEGORY_ATTRIBUTE_EDIT": "主类目属性编辑",
        "TXT_PRODUCT_NAME": "产品名称",
        "TXT_ERROR_TYPE": "错误类型",
        "TXT_GROUP_NAME": "商品名称",
        "TXT_ERROR_CODE": "异常Code",
        "TXT_ERROR_MESSAGE": "异常消息",
        "TXT_ERROR_CREATE_TIME": "异常创建时间",
        "TXT_ERROR_IS_FIX": "已解决?",
        "TXT_ATTRIBUTE_ID": "属性ID",
        "TXT_ATTRIBUTE_NAME": "属性名称",
        "TXT_ATTRIBUTE_TYPE": "属性类型",
        "TXT_PROMOTION_HISTORY": "活动履历",
        "TXT_PROMOTION_NAME": "活动名称",
        "TXT_PROMOTION_TIME": "活动时间",
        "TXT_PROMOTION_COMMENTS":"活动备注",
        "TXT_PROMOTION_PC_ID":"聚美专场PC端ID",
        "TXT_PROMOTION_APP_ID":"聚美专场App端ID",
        "TXT_MSRP": "官方售价",
        "TXT_PROMOTION_PRICE": "活动售价",
        "TXT_SKU": "Sku",
        "TXT_COMMENT": "备注",
        "TXT_UPDATE_BY": "修改折",
        "TXT_PRODUCT_DETAIL": "产品详情",
        "TXT_PRICE": "价格",
        "TXT_PRICE_TYPE": "价格种类",
        "TXT_PRICE_HISTORY": "价格履历",
        "TXT_IS_FIX_TRANSLATED": "翻译完成?",
        "TXT_PRODUCT_CODE": "产品Code",
        "TXT_PROMOTION_STATUS":"活动状态",
        "TXT_SKU_LIST": "Sku列表",
        "TXT_DISCOUNT_WORD": "%",
        "TXT_PRODUCT_SKU_DETAIL": "Sku详情",
        "TXT_PRODUCT_THIRD_PROPERTY": "第三方自定义属性",
        "TXT_FEED_ATTRIBUTE": "Feed属性",
        "TXT_SELECT_CONDITION": "选择条件",
        "TXT_IS_WAITING_APPROVE": "等待审核?",
        "TXT_IS_APPROVED": "审核通过?",
        "TXT_STATUS": "状态",
        "TXT_PREHEATING_TIME": "预热时间",
        "TXT_PRE_SALE_TIME": "预售时间",
        "TXT_IS_START_TE_JIA_BAO": "特价宝？",
        "TXT_TE_JIA_BAO_ID": "特价宝ID",
        "TXT_PROMOTION_DETAIL": "活动详情",
        "TXT_PROMOTION_TAG": "活动标签",
        "TXT_RETAIL_PRICE": "指导售价",
        "TXT_FILE_IMPORT": "导入文件",
        "TXT_FILE_WITH_COLON": "文件路径:",
        "TXT_PRODUCT_TYPE": "产品类型",
        "TXT_PLATFORM_TYPE_WITH_COLON": "平台类型:",
        "TXT_INPUT_ONLY_CHAR_AND_NUMBER": "这里只能输入:英数字 _ .，别输火星文!",
        "TXT_TAG": "标签",
        "TXT_SORT_1": "排序属性1",
        "TXT_SORT_2": "排序属性2",
        "TXT_SORT_3": "排序属性3",
        "TXT_SORT_ASC": "升序",
        "TXT_SORT_DESC": "降序",
        "TXT_REQUIRED": "必填",
        "TXT_BEAT_TASK": "价格披露",
        "TXT_UNIQUE": "唯一",
        "TXT_LISTING":"列表",
        "TXT_TEMPLATE": "模板",
        "TXT_TEMPLATE_NAME": "模板名称",
        "TXT_TEMPLATE_TYPE": "模板类型",
        "TXT_TEMPLATE_CONTENT": "模板内容",
        "TXT_REPlACEMENT_SYMBOL_IS":"替换符是",
        "TXT_PREVIEW":"预览",
        "TXT_PREVIEW_IMAGE":"预览图片",
        "TXT_EDIT": "编辑",
        "TXT_REVERT_TEMPLATE": "还原模板",
        "TXT_NEED_VERTICAL": "是否更新竖图",
        "TXT_VERTICAL_TEMPLATE": "竖图模板",
        "TXT_VERTICAL_REVERT_TEMPLATE": "竖图还原模板",
        "TXT_TASK_DETAIL": "任务明细一览",
        "TXT_BEAT_TASK_DETAIL": "价格披露任务明细",
        "TXT_IMPORT_GOOD": "导入商品",
        "TXT_ADD_MOD_GOOD": "添加/修改 商品",
        "TXT_DOWNLOAD_TASK_DETAIL": "下载任务明细",
        "TXT_STARTUP_ALL": "启动所有",
        "TXT_STOP_ALL": "停止所有",
        "TXT_REVERT_ALL": "还原所有",
        "TXT_SHOW_ALL": "显示所有",
        "TXT_STARTUP": "启动",
        "TXT_STOP": "停止",
        "TXT_REVERT": "还原",
        "TXT_NUMIID_FULL": "商品的数字 ID ( num_iid )",
        "TXT_CODE_FULL": "商品的 Code",
        "TXT_CUST_QUERY_ATTR": "自定义查询条件",
        "TXT_TASK_NAME": "任务名",
        "TXT_TIME_START": "开始时间",
        "TXT_TIME_END": "结束时间",
        "TXT_TASK_TYPE":"任务类型",
        "TXT_TASK_DATE":"任务时间",
        "TXT_TEJIABAO_DETAIL":"特价宝明细一览",
        "TXT_PENDING":"等待",
        "TXT_SUCCESS":"成功",
        "TXT_FAIL":"失败",
        "TXT_PRICE_ATTRIBUTE": "价格属性",
        "TXT_SALES_ATTRIBUTE": "销售属性",
        "TXT_USABLE_STOCK":"可用库存",
        "TXT_SHOW_FLG": "是否显示",
        "TXT_OTHER": "其他",
        "TXT_ALL": "总数",
        "TXT_READY": "未进行",
        "TXT_WAITING_SEPARATE": "等待隔离",
        "TXT_SEPARATING": "隔离中",
        "TXT_STOCK_SEPARATE_SUCCESS": "隔离成功",
        "TXT_STOCK_SEPARATE_FAILURE": "隔离失败",
        "TXT_WAITING_REVERT": "等待还原",
        "TXT_REVERTING": "还原中",
        "TXT_REVERT_SUCCESS": "还原成功",
        "TXT_REVERT_FAILURE": "还原失败",
        "TXT_CHANGED": "再修正",
        "TXT_SET_ALL": "批量设定",
        "TXT_PLEASE_SET_PERCENT": "请填写百分比",
        "TXT_REAL_TIME_STOCK_STATUS":"实时库存状态",
        "TXT_DYNAMIC":"动态",
        "TXT_AVAILABLE_STOCK":"可调用库存",
        "TXT_ADD_NEW_STOCK_SEPARATE_DETAIL":"新增库存隔离明细",
        "TXT_GET_USABLE_STOCK":"取得可用库存",
        "TXT_SEPARATE_QUANTITY":"隔离库存",
        "TXT_STOCK_SEPARATE_DETAIL":"库存隔离明细",
        "TXT_SEPARATE_TYPE":"隔离种类",
        "TXT_SEPARATE_INCREMENT_QUANTITY":"隔离/增量数",
        "TXT_STOCK_INCREMENT_SEPARATE":"增量库存隔离",
        "TXT_STOCK_INCREMENT_SEPARATE_TASK":"增量库存隔离任务",
        "TXT_PLATFORM": "平台",
        "TXT_ADD_NEW_STOCK_INCREMENT_SEPARATE_TASK":"新建增量库存隔离任务",
        "TXT_PLATFORM_SALE_QUANTITY": "平台销售量",
        "TXT_PLATFORM_STOCK_SEPARATE_QUANTITY": "平台库存隔离数量",
        "TXT_STOCK_INCREMENT_SEPARATE_DETAIL":"增量库存隔离明细",
        "TXT_WAITING_INCREMENT":"等待增量",
        "TXT_INCREASING":"增量中",
        "TXT_INCREMENT_SUCCESS":"增量成功",
        "TXT_INCREMENT_FAILURE":"增量失败",
        "TXT_UPDATE_FIX_VALUE":"更新固定值",
        "TXT_INCREMENT_TYPE":"增量类型",
        "TXT_INCREMENT_PERCENTAGE":"增量百分比",
        "TXT_INCREMENT_CNT":"增量数量",
        "TXT_TAG_STORE_CLASSIFY":"店铺内分类",
        "TXT_TAG_PROMOTION":"活动标签",
        "TXT_TAG_GOODS":"货位标签",
        "TXT_TAG_FREE":"自由标签",
        "TXT_TAG_MANAGEMENT":"标签管理",
        "TXT_TAG_TYPE":"标签类型",
        "TXT_TAG_ONE":"一级标签",
        "TXT_TAG_TWO":"二级标签",
        "TXT_TAG_THREE":"三级标签",

        "TXT_SEPARATE_PROPORTION":"隔离比例",
        "TXT_REVERT_TIME":"还原时间",
        "TXT_INCREASING_PRIORITY":"增优先顺序",
        "TXT_REDUCED_PRIORITY":"减优先顺序",
        "TXT_IMPORT_ONLY_SKU_AND_INVENTORY":"只导入SKU和库存",
        "TXT_SEPARATE":"隔离",
        "TXT_SHARE":"共享",
        "TXT_SEPARATE_NEW_TASK":"新建隔离任务",
        "TXT_PERSONAL_FINISHED_TRANSLATION": "个人完成翻译数",
        "TXT_UN_TRANSLATION": "未分配总数",
        "TXT_DISTRIBUTE_UN_TRANSLATION": "已分配但未完成总数",
        "TXT_TRANSLATED": "完成翻译总数",
        "TXT_DISTRIBUTION_RULE": "优先规则",
        "TXT_MAIN_PRODUCT": "主商品",
        "TXT_GET_TASK_COUNT": "获取任务数量",
        "TXT_PRODUCT_NAME_WITH_LONG_DESCRIPTION": "产品标题 / 长描述",
        "TXT_LONG_TITLE_WITH_LONG_DESCRIPTION": "长标题中文",
        "TXT_MID_TITLE_WITH_SHORT_DESCRIPTION": "中标题 / 长描述中文",
        "TXT_SHORT_TITLE_WITH_MORE_SHORT_DESCRIPTION": "短标题标题 / 短描述中文",
        "TXT_TRANSLATOR_WIT_COLON": "译者：",
        "TXT_BASE_ATTRIBUTE": "共通属性",
        "TXT_CUST_ATTRIBUTE": "自定义属性",
        "TXT_TRANSSTS_ATTRIBUTE": "翻译状态",
        "TXT_WAITING_UPLOAD": "待上传",
        "TXT_UPLOAD_SUCCESS": "上传成功",
        "TXT_UPLOAD_FAILED": "上传失败",
        "TXT_DATA_TYPE": "数据类型",
        "TXT_SPECIAL_DESCRIPTION": "特殊说明",
        "TXT_BRAND_STORY": "品牌故事图",
        "TXT_SHIPPING_DESCRIPTION": "物流介绍",
        "TXT_INDEX": "编号",
        "TXT_ORIGIN_IMAGE_URL": "原始图片地址",
        "TXT_JM_IMAGE_URL": "聚美图片地址",
        "TXT_SET_DEFAULT_VALUE": "设定图片默认项",
        "TXT_SHIP_STOCK": "发货仓库",
        "TXT_RELEASE_DATE": "保质期限",
        "TXT_PRODUCTION_AREA": "生产地区",
        "TXT_SUIT_CROWDS": "适合人群",
        "TXT_WHITE_SQUARE_MODEL": "白底方图模板",
        "TXT_PRODUCT_REALLY_MODEL": "商品实拍图模板",
        "TXT_PRODUCT_UPRIGHT_MODEL": "商品竖图模板",
        "TXT_SPECIAL_NOTE": "特殊说明",
        "TXT_ACTIVITY_IMAGE_SETTING": "聚美共通图片设定",
        "TXT_SIZE_CHART_IMAGE": "尺码图",
        "TXT_BRAND_STORY_IMAGE": "品牌故事图",
        "TXT_SHIPPING_DESCRIPTION_IMAGE": "物流介绍图",
        "TXT_IMAGE_UPLOAD_NOTICE": "只支持jpg图片",
        "TXT_CART_NAME": "店铺渠道名称",

        "TXT_CHANNEL_ID": "渠道ID",
        "TXT_CART_ID": "Cart ID",
        "TXT_ALLOW_USJOI": "Allow USJOI",
        "TXT_FULL_NAME": "渠道全称",
        "TXT_SHORT_NAME": "短名称",
        "TXT_COMPANY": "公司",
        "TXT_IMAGE_URL": "图片地址",
        "TXT_MSG_SEARCH": "检索...",
        "TXT_MSG_INVALID_FEILD": "请检查这些属性 [ <h4>{{fields}}</h4> ], 然后重新尝试保存. (。・`ω´・)",
        "TXT_MSG_PAGE_IS_BUILDING": "该页面正在建设中...",
        "TXT_MSG_SEARCH_INDEX_FUZZY_SEARCH": "查询包括:产品Code(多项换行分割),款号(多项换行分割),SKU(多项换行分割),产品名称(中文),产品名称(英文),详情描述(中文),详情描述(英文)",
        "TXT_MSG_SEARCH_INDEX_FUZZY_SEARCH_2": "查询包括:产品Code(多项换行分割),款号(多项换行分割)",
        "TXT_MSG_INSERT_SUCCESS": "新建操作成功.",
        "TXT_MSG_INSERT_FAIL": "新建操作失败.",
        "TXT_MSG_UPDATE_SUCCESS": "更新操作成功.",
        "TXT_MSG_UPDATE_FAIL": "更新操作失败.",
        "TXT_MSG_SET_SUCCESS": "设定操作成功.",
        "TXT_MSG_SET_FAIL": "设定操作失败.",
        "TXT_MSG_SEPARATE_SUCCESS": "隔离操作成功",
        "TXT_MSG_SEPARATE_FAIL": "隔离操作失败",
        "TXT_MSG_INCREMENT_SUCCESS": "增量操作成功",
        "TXT_MSG_INCREMENT_FAIL": "增量操作失败.",
        "TXT_MSG_REVERT_SUCCESS": "还原操作成功",
        "TXT_MSG_REVERT_FAIL": "还原操作失败",
        "TXT_MSG_NO_ROWS_SELECT": "请至少选择一条数据.",
        "TXT_MSG_NO_PRODUCT_ROWS": "请至少保证有一条产品数据",
        "TXT_MSG_NO_CATEGORY_SELECT": "请选择一个子类目.",
        "TXT_MSG_NO_SELECT_CATEGORY": "请选择一个类目.",
        "TXT_MSG_NO_APPLY_CATEGORY": "未申请此类目",
        "TXT_MSG_IS_NOT_CHILE_CATEGORY": "选择的类目不是一个子类目.",
        "TXT_MSG_CONFIRM_CHANGE_MASTER_PRODUCT": "如果您变更主商品,将会对平台的商品信息产生一些影响.<br>您确定要执行这个操作吗?",
        "TXT_MSG_CONFIRM_IS_CHANGE_CATEGORY": "如果您切换主类目,产品的属性将会被重置.<br>您确定要执行这个操作吗?",
        "TXT_MSG_NO_DATE": "当前数据为空...",
        "TXT_MSG_PRODUCT_IS_PUBLISHING": "所操作的产品处于上新中,不能切换主类目.",
        "TXT_MSG_CONFIRM_FROWARD_PARENT_CATEGORY": "如果您继承父类目,以前设置的属性将会被替换点.<br>您确定要执行这个操作吗?",
        "TXT_MSG_NO_FIND_FORWARD_CATEGORY": "没有可继承的父类目.",
        "TXT_MSG_DELETE_ITEM": "您确定要删除这条数据吗?",
        "TXT_MSG_STARTUP_ITEM": "您确定要全部启动吗?",
        "TXT_MSG_DELETE_SUCCESS": "删除操作成功",
        "TXT_MSG_DELETE_FAIL": "删除操作失败.",
        "TXT_MSG_ADD_ITEM": "您确定要更新这条数据吗?",
        "TXT_MSG_ADD_SUCCESS": "更新操作成功",
        "TXT_MSG_ADD_FAIL": "更新操作失败.",
        "TXT_MSG_NO_DATA_WITH_SAVE": "请确保必填项,以及列表中不为空",
        "TXT_MSG_NO_PLATFORM_CATEGORY": "没有取到任何平台类目... 尝试换一个平台试试 ?",
        "TXT_MSG_VALUE_SETTING_COMMENT": "值设定说明：",
        "TXT_MSG_VALUE_SETTING_COMMENT_1": "如果不对属性进行任何值设定，则会使用默认值。",
        "TXT_MSG_VALUE_SETTING_COMMENT_2": "如果对属性进行了多个值设定，则会使用顺序验证可用性。即如果条件，则先验证条件，无条件的，直接为可用。一旦某一条设定生效（可用）",
        "TXT_MSG_CANNOT_GET": "无法取得 ",
        "TXT_MSG_TYPE_VALUE": " 类型的匹配值.",
        "TXT_MSG_MUST_GET_ONE_VALUE": "必须匹配一类值才能保存.",
        "TXT_MSG_NO_VALUE_IS_ON_THE_ATTRIBUTE": "没有匹配到任何属性或内容上.",
        "TXT_MSG_UNVALID_CONDITION": "无效的条件.",
        "TXT_MSG_PRODUCT_CAN_NOT_EDIT": "该商品正在主类目切换中,请稍等...",
        "TXT_MSG_PROMOTION_DELETE": "您确定要删除活动[%s]吗？",
        "TXT_MSG_DO_DELETE": "您确定要删除 ",
        "TXT_MSG_DO_SEPARATE": "您确定要隔离 ",
        "TXT_MSG_DO_INCREASE": "您确定要增量 ",
        "TXT_MSG_DO_REVERT": "您确定要还原 ",
        "TXT_MSG_LONG_TITLE":"长标题",
        "TXT_MSG_MIDDLE_TITLE":"中标题",
        "TXT_MSG_SHORT_TITLE":"短标题",
        "TXT_MSG_LONG_DESCRIPTION":"长描述",
        "TXT_MSG_SHORT_DESCRIPTION":"短描述",
        "TXT_MSG_UNVALID_URL": "无效的地址.",
        "TXT_MSG_NO_UPLOAD": "请选择要提交的文件",
        "TXT_MSG_CODE_IN_OTHER": "你提交的商品,已经在其他任务中.你确定要继续?",
        "TXT_MSG_REIMPORT_BEAT": "从新上传会覆盖原数据, 意味着之前的数据将被清空. 你确定要继续么?",
        "TXT_MSG_ERROR_BEAT_ITEM": "这个任务的商品信息好像有问题? 你确定要修改它的状态?",
        "TXT_MSG_IMPORT_DELETE_UPDATE_MSGBOX": "重置方式导入时,原数据会全部被删除.你确定要继续?",
        "TXT_MSG_INPUT_WORD_LENCHK": "你还可以输入",
        "TXT_MSG_INPUT_WORD_LENCHK2": "个文字",
        "TXT_MSG_FIELD_VAL_INVALID": "属性(字段)的值无效, 请根据提示修改.",
        "TXT_MSG_INPUT_WORD_LENLOWLIMIT": "请至少输入 ",
        "TXT_MSG_INPUT_WORD_LENLIMIT": "已经达到最大长度字符数限制",
        "TXT_MSG_IMPORT_MODE": "导入方式",
        "TXT_MSG_IMPORT_UPDATE": "变更方式",
        "TXT_MSG_IMPORT_ADD": "增量方式",
        "TXT_MSG_IMPORT_DELETE_UPDATE": "重置方式",
        "TXT_MSG_IMPORT_STATUS_ERROR": "存在正在处理中的数据，这些没有被更新",
        "TXT_MSG_IMPORT":"请输入",
        "TXT_MSG_HAVE_UN_TRANSLATED_TASK": "您还有未完成的翻译项目, 请完成后再获取新的任务!",
        "TXT_MSG_ACTIVITIES": "请选择对应的活动!",
        "TXT_MSG_TAG": "请正确选择和填写标签!",
        "TXT_MSG_TAG_EDITOR": "标签编辑页!",
        "TXT_MSG_TAG_PATH": "标签路径!",
        "TXT_MSG_TAG_NAME": "标签名",
        "TXT_MSG_TAG_IMAGE": "标签名称小于50字节!",
        "TXT_MSG_UPLOAD_IMAGE_SUCCESS": "图片上传/刷新成功.",
        "TXT_ACTIVITY_NAME": "活动名称",
        "TXT_PC_MODULE_ID": "PC端模块ID",
        "TXT_APP_MODULE_ID": "APP端模块ID",
        "TXT_PROMOTION_DISCOUNT": "是否有活动折扣",
        "TXT_IMAGE_TYPE":"图片类型",
        "TXT_IMAGE_GROUP_LIST":"图片管理",
        "TXT_RELATED_BRAND_NAME":"相关品牌",
        "TXT_RELATED_PRODUCT_TYPE":"相关产品类型",
        "TXT_RELATED_SIZE_TYPE":"相关尺码",
        "TXT_IMAGE_GROUP_NAME":"图片组别名称",
        "TXT_VIEW_TYPE":"客户端类型",
        "TXT_IMAGE_COUNT":"图片数",
        "TXT_IMAGE_DETAIL":"图片详细",
        "TXT_IMAGE":"图片",
        "TXT_ORIGIN_URL":"原始Url",
        "TXT_PLATFORM_URL":"平台Url",
        "TXT_SEQUENCE":"顺序",
        "TXT_IMAGE_GROUP_ADD":"新增图片组别",
        "TXT_COMMON_IMAGE_SET":"图片设定",
        "TXT_ORIGIN_IMAGE":"原始图片",
        "TXT_MSG_DO_REFRESH_IMAGE": "您确定要刷图",
        "TXT_MSG_REFRESH_IMAGE_SUCCESS": "刷图操作成功",
        "TXT_MSG_REFRESH_IMAGE_FAIL": "刷图操作失败",
        "TXT_IMPORT_TEXT": "导入内容",
        "TXT_FeedStatus_New": "新产品",
        "TXT_FeedStatus_WaitingForImport": "等待导入",
        "TXT_FeedStatus_FinishImport": "导入成功",
        "TXT_FeedStatus_Error": "导入失败",
        "TXT_FeedStatus_NotImport": "不导入",
        "TXT_FeedStatus_DateError": "Feed数据异常错误",


        "BTN_CREATE_TASK": "新建任务",
        "BTN_CREATE_BEAT_TASK": "新建价格披露任务",
        "BTN_CREATE_TE_JIA_BAO_TASK": "新建特价宝任务",
        "BTN_ADD_CONDITION": "新增条件",
        "BTN_CANCEL": "取消",
        "BTN_CLOSE": "关闭",
        "BTN_TODAY": "今日",
        "BTN_SAVE": "保存",
        "BTN_SEARCH": "检索",
        "BTN_ADD_TO_PROMOTION": "参加活动",
        "BTN_ADD_TO_JM_PROMOTION": "参加聚美专场活动",
        "BTN_BATCH_UPDATE_ATTRIBUTE": "批量更新",
        "BTN_UPDATE_COMMON_ATTRIBUTE": "更新共通属性",
        "BTN_CHANGE_MASTER_CATEGORY": "切换主类目",
        "BTN_OK": "确定",
        "BTN_CLEAR": "清空",
        "BTN_EXPORT": "导出",
        "BTN_GO": "Go",
        "BTN_CREATE": "新建",
        "BTN_NEW_DICT_VALUE": "新增字典值",
        "BTN_NEW_DICT_CUS_VALUE": "新增自定义",
        "BTN_SET_PARAM": "修改参数",
        "BTN_NEW_DICT": "新字典项",
        "BTN_NEW_PROMOTION": "新建活动",
        "BTN_MAPPING_CATEGORY": "类目匹配",
        "BTN_NEW_DICTIONARY": "新增字典",
        "BTN_NEW_DICTIONARY_VALUE": "新增字典值",
        "BTN_NEW_DICTIONARY_DEFINE": "新增自定义",
        "BTN_FORWARD": "继承",
        "BTN_MAPPING_ATTRIBUTE": "属性匹配",
        "BTN_MAPPING_ATTRIBUTE_COMMON_MAIN": "属性通用匹配",
        "BTN_OTHER_PLATFORM": "其他平台",
        "BTN_NEW_ATTRIBUTE": "新增属性",
        "BTN_SAVE_ALL": "全部保存",
        "BTN_EDIT": "编辑",
        "BTN_DELETE": "删除",
        "BTN_ADD": "追加",
        "BTN_REFRESH": "刷新",
        "BTN_PROMOTION_HISTORY": "活动履历",
        "BTN_PRICE_HISTORY": "价格履历",
        "BTN_DOWNLOAD": "下载",
        "BTN_DOWNLOAD_ERROR": "Error日志",
        "BTN_IMPORT_PROMOTION_FILE": "导入活动文件",
        "BTN_CHOOSE_FILE": "选择文件",
        "BTN_IMPORT_FILE": "Import File",
        "BTN_UPLOAD_FILE": "Upload File",
        "BTN_CUSTOMIZE_COLUMNS": "自定义列设置",
        "BTN_GET_TASK": "获取任务",
        "BTN_COMPLETE": "完成",
        "BTN_SET": "设定",
        "BTN_IMPORT_ALL": "批量导入",
        "BTN_EXPORT_ALL": "批量导出",
        "BTN_START_REFRESH_ALL": "启动/重刷所有",
        "BTN_REVERT_ALL": "还原所有",
        "BTN_START_INCREMENT_ALL": "启动增量所有",
        "BTN_SET_DEFAULT_VALUE": "设定默认项",
        "BTN_RESET":"重置",
        "BTN_REFRESH_PAGE": "刷新画面",
        // 枚举 com.voyageone.cms.enums.BeatFlag 的翻译
        "STOP": "已停止",
        "BEATING": "正在执行",
        "SUCCESS": "更新成功",
        "FAIL": "更新失败",
        "REVERT": "正在还原",
        "RE_SUCCESS": "还原成功",
        "RE_FAIL": "还原失败",
        "CANT_BEAT": "信息错误",

        "None": "无图",
        "Waiting": "等待取图",
        "Error": "取图错误",
        "Exists": "取图成功",

        /**分页显示*/
        "TXT_PAGER_SIZE": "每页显示",
        /**尺码表*/
        "TXT_SIZE_CHART":"尺码表",
        "TXT_SIZE_CHART_DETAIL":"尺码表明细",
        "TXT_SIZE_CHART_ADD":"新增尺码表",
        "TXT_SIZE_CHART_IMPORT":"导入尺码表",
        "TXT_SIZE_CHART_NAME":"尺码表名称",
        "TXT_SIZE_CHART_FINISH":"是否完成",
        "TXT_SIZE_CHART_UPDATE_TIME":"更新时间",
        "TXT_SIZE_CHART_BRAND_NAME":"品牌名称",
        "TXT_SIZE_CHART_PRODUCT_TYPE":"品牌类别",
        "TXT_SIZE_CHART_SIZE_TYPE":"适用尺码",
        "TXT_SIZE_CHART_ORIGINAL_SIZE":"原始尺码",
        "TXT_SIZE_CHART_ADJUST_SIZE":"平台尺码",
        "TXT_SIZE_CHART_COMMON_SIZE":"是否普通尺码",
        "TXT_SIZE_CHART_NOTICE":" 尺码表存在疑问请选择No，上新依然会使用这个尺码表",
        "TXT_SIZE_CHART_NOTICE_REQUIED":"请输入尺码表名称",
        "TXT_SIZE_CHART_NOTICE_REPEAT":"原始尺码不能重复",
        "TXT_SIZE_CHART_NOTICE_NULL":"原始尺码或者平台尺码不能为空",
        "TXT_SIZE_CHART_NOTICE_third":"请检查导入格式，第三位数据为0或者1",
        "TXT_SIZE_CHART_NOTICE_PS":"请按照示例数据格式导入（分隔符是Tab符）",
        "TXT_SIZE_CHART_COMMON_ADD":"普通尺码表编辑",

        /**店铺分类*/
        "TXT_STORE_CATEGORY_NAME":"店铺",
        "MAX_SELLER_CAT_DEPTH":"最大层数",
        "MAX_SELLER_CAT_CNT":"可设置最大标签数应小于",
        "TXT_STORE_CATEGORY_SELECT":"请选择一个店铺",
        "INVALID_OPERATION_IN_CURRENT_CART_PATH":"当前店铺路径下操作无效",
        "CATEGORY_EDIT":"分类类目编辑",

        /**工具管理*/
        "TXT_TOOLS_MANAGEMENT":"工具管理",
        "TXT_TOOLS_MANAGEMENT_HS_CODE_SETTING_STATUS": "商品税号设置状态",
        "TXT_TOOLS_MANAGEMENT_HS_CODE_SETTING":"商品税号设置",
        "TXT_NUMBER_OF_WAITED_FOR_SETTED":"等待设置税号数",
        "TXT_NUMBER_OF_SETTED":"设置税号商品总数",
        "TXT_NUMBER_OF_SETTED_BY_PERSONAL": "个人设置税号商品译数",
        "TXT_HS_CODE_STATUS":"税号状态",
        "TXT_PRODUCT_CODE_MATERIAL": "product code/材质",
        "TXT_HSCODE_PRODUCT_NAME_UNIT":"税号/品名/单位",
        "TXT_RULE_OF_PRE":"优先规则",
        "TXT_GROUP_NAME_FEED_CAT_WITH_COLON":"商品名称/Feed类目/主类目",
        "TXT_HS_CODE_SETTED_SEARCH":"个人设置税号成果搜索",

        /**高级检索*/
        "TXT_ADVANCE_SEARCH_NEW":"高级搜索",
        "TXT_COMMON_SEARCH":"共通搜索条件",
        "TXT_PLATFORM_SEARCH":"平台搜索条件",
        "TXT_DIY_SEARCH":"自定义搜索条件",
        "TXT_CATEGORY_STATUS":"主类目状态",
        "TXT_TAX_NO_STATUS":"税号设置状态",
        "TXT_MAIN_CATEGORY":"主类目",
        "TXT_LIST_ERROR":"错误列表",
        "TXT_ERROR":"错误",
        "TXT_PROPERTY_STATUS":"Property status",
        "TXT_IMAGE_DOWNLOAD":"图片下载",
        "TXT_CUS_TAGS_SETTING":"设置自定义标签",
        "TXT_COMMON_EXCHANGE":"共通级变更",
        "TXT_CHANGE_FOR_TG_PLATFORM":"天猫国际平台级变更",
        "TXT_CHANGE_FOR_JD_PLATFORM":"京东国际平台级变更",
        "TXT_CHANGE_FOR_JM_PLATFORM":"聚美国际平台级变更",
        "TXT_BULK_APPROVAL":"开始进行批量审批处理，是否继续？",
        "TXT_NONE":"none",
        "TXT_EXPRESSION":"表达式",
        "TXT_SALES_SORT":"销量排序",
        "TXT_7_DAYS":"7天",
        "TXT_30_DAYS":"30天",
        "TXT_ROUND_UP":"四舍五入",
        "TXT_ALL_PUT_ON|OFF":"全店铺上下架",
        "TXT_PUT_ON/PUT_OFF":"上下架",
        "TXT_PUT_ON":"上架",
        "TXT_PUT_OFF":"下架",
        "TXT_ALL_CHANNEL_APPROVAL":"全店铺商品审批",
        "TXT_PRODUCTS_APPROVAL":"商品审批",
        "TXT_PRODUCTS_PROPERTY_CHANGE":"商品属性变更",

        /**页面价格*/
        "TXT_FINAL_SALE_PRICE_SETTING":"中国最终售价设置",
        "TXT_BASE_PRICE":"Base price",
        "TXT_FINAL_SALE_PRICE":"中国最终售价",
        "TXT_CHINA_PROMOTION_PRICE":"中国促销价",
        "TXT_CHINA_RETAIL_PRICE":"中国指导价",
        "TXT_CHINA_MSRP_PRICE":"中国建议零售价",
        "TXT_CLIENT_NET_PRICE":"客户成本价",
        "TXT_CLIENT_RETAIL_PRICE":"客户指导价",
        "TXT_CLIENT_MSRP_PRICE":"客户建议零售价",
        "TXT_CLIENT_PROMOTION_PRICE":"客户促销价",

        "INVALID_EMAIL": "请输入正确的E-Mail地址",
        "INVALID_URL": "请输入正确的URL地址",
        "INVALID_DATE": "请输入正确的日期",
        "INVALID_DATETIMELOCAL": "请输入正确的日期时间",
        "INVALID_COLOR": "请输入正确的颜色",
        "INVALID_RANGE": "请输入正确的排列",
        "INVALID_MONTH": "请输入正确的月份",
        "INVALID_TIME": "请输入正确的时间",
        "INVALID_WEEK": "请输入正确的星期",
        "INVALID_NUMBER": "请输入正确的数字",
        "INVALID_REQUIRED": "请输入数据",
        "INVALID_MAXLENGTH": "请输入的数据长度不能超过:{{value}}",
        "INVALID_MINLENGTH": "请输入的数据长度不能短于:{{value}}",
        "INVALID_MAX": "请输入的数据不能大于:{{value}}",
        "INVALID_MIN": "请输入的数据不能小于:{{value}}",
        "INVALID_PATTERN": "请输入的数据必须满足规则:{{value}}",

        /**平台schema*/
        "TXT_BAR_CODE":"条形码",

        /**上下架*/
        "TXT_COMMIT_ERROR": "提交请求时出现错误",
        "TXT_NO_PRODUCT_CHOOSED":"未选择商品，请选择后再操作",
        "TXT_NO_OPPERATION":"没有设置上下架操作，请选择后重试",
        "TXT_CONFIRM_ALL_STORE_PUT_ON":"此操作将会导致全店铺商品上下架，确认无误",
        "TXT_ITEM_CODE": "商品Code",

        /** 翻译页面相关 **/
        "TXT_TRANSLATION_STATUS": "商品翻译状态",
        "TXT_TRANSLATION_TASK_GET": "获取任务",
        "TXT_TRANSLATION_SEARCH": "个人翻译成果搜索",
        "TXT_TRANSLATION_SEARCH_SELECT_ALL": "全部",
        "TXT_TRANSLATION_SEARCH_SELECT_NOT_TRANSLATED": "未翻译",
        "TXT_TRANSLATION_SEARCH_SELECT_TRANSLATED": "已翻译",
        "TXT_FUZZY_SEARCH_PLACE_HOLDER": "模糊查询(ProductCode，商品名称)",
        "TXT_PRODUCT_EN_NAME": "商品名称(英文)",
        "TXT_PRODUCT_CN_NAME": "商品名称(中文)",
        "TXT_PRODUCT_EN_MATERIAL": "材质(英文)",
        "TXT_PRODUCT_CN_MATERIAL": "材质(中文)",
        "TXT_PRODUCT_EN_SHORT_DESCRIPTION": "简短描述(英文)",
        "TXT_PRODUCT_CN_SHORT_DESCRIPTION": "简短描述(中文)",
        "TXT_PRODUCT_EN_LONG_DESCRIPTION": "详情描述(英文)",
        "TXT_PRODUCT_CN_LONG_DESCRIPTION": "详情描述(中文)",
        "TXT_PRODUCT_EN_INSTRUCTIONS": "使用方法(英文)",
        "TXT_PRODUCT_CN_INSTRUCTIONS": "使用方法(中文)",
        
        /**聚美专场*/
        "TXT_JM_PROMOTION_NAME":"聚美专场名称",
        "TXT_JM_PROMOTION_CHANGED_COUNT":"有变更产品数",
        "TXT_JOIN_JM_PROMOTION_PRESALE_TIME":"预热时间",
        "TXT_PROMOTION_PRODUCT_STATUS":"产品活动状态",
        "TXT_JOIN_JM_CODE_SKU_SEARCH":"Code/SKU"
    };
});