define(function(){
    return {
        "TXT_REMINDER_WITH_COLON": "温馨提示：",
        "TXT_LOGOUT": "注销",
        "TXT_HOME": "首页",
        "TXT_CATEGORY_VIEWS": "-- 类目视图 --",
        "TXT_CATEGORY_MANAGER": "类目管理",
        "TXT_PROMOTION_MANAGER": "活动管理",
        "TXT_PROMOTION_LIST": "活动一览",
        "TXT_TASK_LIST": "任务一览",
        "TXT_SEARCH": "检索",
        "TXT_ADVANCE_SEARCH": "高级检索",
        "TXT_MAPPING_SETTING": "匹配关系设置",
        "TXT_FEED_CONNECTION_SETTING": "Feed匹配关系设置",
        "TXT_PLATFORM_CONNECTION_SETTING": "平台匹配关系设置",
        "TXT_DICTIONARY_INDEX": "字典一览",
        "TXT_CHANNEL_MANAGER": "店铺管理",
        "TXT_CUSTOM_ATTRIBUTE_MANAGER": "自定义属性设置",
        "TXT_COMMON_ATTRIBUTE_MANAGER": "共通属性设置",
        "TXT_AUTHORITY_SETTING": "权限设置",
        "TXT_CONFIGURATION_SETTING": "配置设置",
        "TXT_TRANSLATION_MANAGER": "翻译管理",
        "TXT_TRANSLATION_INDEX": "翻译一览",
        "TXT_SYSTEM_SETTING": "系统管理",
        "TXT_CATEGORY_INDEX": "主类目一览",
        "TXT_ERROR_MANAGER_MARKETING": "异常一览（运营）",
        "TXT_ERROR_MANAGER_MAINTENANCE": "异常一览（维护）",
        "TXT_CATEGORY": "类目",
        "TXT_PRODUCT_STATUS": "产品状态",
        "TXT_PLATFORM_STATUS": "商品平台状态",
        "TXT_PRICE": "价格",
        "TXT_CREATE_TIME": "创建时间",
        "TXT_PUBLISH_TIME": "发布时间",
        "TXT_INVENTORY": "库存",
        "TXT_SELECT_NO_VALUE": "请选择...",
        "TXT_BRAND": "品牌",
        "TXT_FUZZY_SEARCH": "模糊查询",
        "TXT_GROUP_LIST": "商品一览",
        "TXT_PRODUCT_LIST": "产品一览",
        "TXT_SELECT_ALL": "全选",
        "TXT_SALE_PRICE": "最终售价",
        "TXT_PRIMARY_PRODUCT": "主产品",
        "TXT_BASE_PROPERTY": "基础属性",
        "TXT_TIME": "时间",
        "TXT_NUMBER_IID_WITH_COLON": "商品编号:",
        "TXT_GROUP_NAME_WITH_COLON": "商品名称:",
        "TXT_CATEGORY_WITH_COLON": "类目:",
        "TXT_SIZE_TYPE": "尺码类型",
        "TXT_SKU_COUNT": "SKU数",
        "TXT_PRODUCT_CODE_WITH_COLON": "产品Code:",
        "TXT_PRODUCT_NAME_WITH_COLON": "产品名称:",
        "TXT_SKU_PLATFORM_INFO": "Sku平台信息",
        "TXT_SKU_INVENTORY": "Sku库存",
        "TXT_PROMOTION_AND_TAG": "活动 & 标签",
        "TXT_CHANNEL_WITH_COLON": "渠道:",
        "TXT_PROMOTION_NAME_WITH_COLON": "活动名称:",
        "TXT_PROMOTION_TIME_WITH_COLON": "活动时间:",
        "TXT_PROMOTION_TAG_WITH_COLON": "活动标签:",
        "TXT_BULK_UPDATE_PROPERTY": "批量更新产品属性",
        "TXT_PROPERTY_NAME_WITH_COLON": "属性名",
        "TXT_PROPERTY_VALUE_WITH_COLON": "属性值",
        "TXT_FEED_OR_MASTER_CATEGORY_WITH_COLON": "Feed / 主类目:",
        "TXT_LEVEL_CATEGORY": "级类目",
        "TXT_CURRENT_CATEGORY_WITH_COLON": "当前选择的类目:",
        "TXT_GROUP_DETAIL": "商品详情",
        "TXT_NUM_IID": "商品编号",
        "TXT_MODEL": "款号",
        "TXT_PLATFORM_CATEGORY": "平台类目",
        "TXT_MASTER_CATEGORY": "主类目",
        "TXT_MASTER_CATEGORY_COMMON_FLG": "通用",
        "TXT_MASTER_CATEGORY_WITH_COLON": "主类目:",
        "TXT_FEED_CATEGORY": "Feed类目",
        "TXT_ON_SALE_TIME": "销售时间",
        "TXT_MSRP_WITH_COLON": "官方售价:",
        "TXT_RETAIL_PRICE_WITH_COLON": "指导售价:",
        "TXT_CREATE_TIME_WITH_COLON": "创建时间:",
        "TXT_PUBLISH_TIME_WITH_COLON": "发布时间:",
        "TXT_ON_SALE_TIME_WITH_COLON": "销售时间:",
        "TXT_ALERT": "温馨提示",
        "TXT_WARNING": "警告",
        "TXT_CONFIRM": "确认",
        "TXT_ALERT_WITH_COLON": "温馨提示:",
        "TXT_PLATFORM_TYPE": "平台类型",
        "TXT_TOP_FEED_CATEGORY": "顶层Feed类目",
        "TXT_FILTER_CATEGORY": "类目匹配筛选",
        "TXT_FILTER_ATTRIBUTE": "属性匹配筛选",
        "TXT_SEQ": "编号",
        "TXT_LEVEL": "层级",
        "TXT_MAPPING_CATEGORY_OR_FORWARD": "类目匹配 / 继承",
        "TXT_MAPPING_ATTRIBUTE_IS_FINISHED": "属性匹配完成?",
        "TXT_MAPPING_ATTRIBUTE": "属性匹配",
        "TXT_MASTER_DATA_ATTRIBUTE_MAPPING": "主数据属性匹配",
        "TXT_PLATFORM_ATTRIBUTE_MAPPING": "平台属性匹配",
        "TXT_ATTRIBUTE_MAPPING": "属性匹配",
        "TXT_ATTRIBUTE_MAPPING_VALUE_TYPE": "值类型",
        "TXT_ATTRIBUTE_MAPPING_CONDITION_COUNT": "条件个数",
        "TXT_SUB_LEVEL": "级",
        "TXT_NORMAL_ATTRIBUTE": "普通属性",
        "TXT_COMMON_ATTRIBUTE": "共通属性",
        "TXT_SKU_ATTRIBUTE": "SKU属性",
        "TXT_COMPLETE": "已匹配",
        "TXT_INCOMPLETE": "未匹配",
        "TXT_MAPPING_CATEGORY_OR_OTHER_PLATFORM": "类目匹配 / 其他平台",
        "TXT_OTHER_PLATFORM": "其他平台",
        "TXT_MAPPING_VALUE": "值匹配",
        "TXT_DICTIONARY_NAME": "字典名称",
        "TXT_DICTIONARY_COMMENT": "字典内容",
        "TXT_ACTION": "操作",
        "TXT_UPDATE_TIME": "更新时间",
        "TXT_SHOWING_NO": "第",
        "TXT_PAGE": "页",
        "TXT_SHOWING": "显示",
        "TXT_OF": "之",
        "TXT_ITEMS": "件数",
        "TXT_DICTIONARY_DETAIL": "字典详情",
        "TXT_NAME": "名称",
        "TXT_IS_UPLOAD_TO_TMALL": "需要上传天猫 ?",
        "TXT_TYPE": "类型",
        "TXT_VALUE": "值",
        "TXT_MASTER_DATA": "主数据",
        "TXT_FEED_DATA": "品牌数据",
        "TXT_DICTIONARY": "字典",
        "TXT_TEXT": "文本",
        "TXT_CUSTOM": "自定义",
        "TXT_ABSTRACT": "摘要",
        "TXT_DICTIONARY_CUSTOM": "字典自定义设置",
        "TXT_DICTIONARY_VALUE": "字典值设置",
        "TXT_FORWARD_WITH_COLON": "可继承: ",
        "TXT_UN_SETTING": "[未设定]",
        "TXT_CATEGORY_NAME": "类目名称",
        "TXT_CATEGORY_ID": "类目ID",
        "TXT_MASTER_CATEGORY_ATTRIBUTE_EDIT": "主类目属性编辑",
        "TXT_PRODUCT_NAME": "产品名称",
        "TXT_ERROR_TYPE": "错误类型",
        "TXT_GROUP_NAME": "商品名称",
        "TXT_ERROR_CODE": "异常Code",
        "TXT_ERROR_MESSAGE": "异常消息",
        "TXT_ERROR_CREATE_TIME": "异常创建时间",
        "TXT_ERROR_IS_FIX": "已解决?",
        "TXT_ATTRIBUTE_ID": "属性ID",
        "TXT_ATTRIBUTE_NAME": "属性名称",
        "TXT_ATTRIBUTE_TYPE": "属性类型",
        "TXT_PROMOTION_HISTORY": "活动履历",
        "TXT_PROMOTION_NAME": "活动名称",
        "TXT_PROMOTION_TIME": "活动时间",
        "TXT_PROMOTION_PC_ID":"聚美专场PC端ID",
        "TXT_PROMOTION_APP_ID":"聚美专场App端ID",
        "TXT_MSRP": "官方售价",
        "TXT_PROMOTION_PRICE": "活动售价",
        "TXT_CODE_OR_SKU": "产品Code / SKU",
        "TXT_COMMENT": "备注",
        "TXT_UPDATE_BY": "修改折",
        "TXT_PRODUCT_DETAIL": "产品详情",
        "TXT_PRICE_HISTORY": "价格履历",
        "TXT_IS_FIX_TRANSLATED": "翻译完成?",
        "TXT_PRODUCT_CODE": "产品Code",
        "TXT_PROMOTION_STATUS":"活动状态",
        "TXT_PRICE_TYPE": "价格类型",
        "TXT_DISCOUNT_WORD": "%",
        "TXT_PRODUCT_SKU_DETAIL": "Sku详情",
        "TXT_PRODUCT_THIRD_PROPERTY": "第三方自定义属性",
        "TXT_FEED_ATTRIBUTE": "Feed属性",
        "TXT_SELECT_CONDITION": "选择条件",
        "TXT_IS_WAITING_APPROVE": "等待审核?",
        "TXT_IS_APPROVED": "审核通过?",
        "TXT_STATUS": "状态",
        "TXT_PREHEATING_TIME": "预热时间",
        "TXT_PRE_SALE_TIME": "预售时间",
        "TXT_IS_START_TE_JIA_BAO": "特价宝？",
        "TXT_TE_JIA_BAO_ID": "特价宝ID",
        "TXT_PROMOTION_DETAIL": "活动详情",
        "TXT_PROMOTION_TAG": "活动标签",
        "TXT_RETAIL_PRICE": "指导售价",
        "TXT_FILE_IMPORT": "导入文件",
        "TXT_FILE_WITH_COLON": "文件路径:",
        "TXT_PRODUCT_TYPE": "产品类型",
        "TXT_PLATFORM_TYPE_WITH_COLON": "平台类型:",
        "TXT_INPUT_ONLY_CHAR_AND_NUMBER": "这里只能输入:英数字 _ .，别输火星文!",
        "TXT_TAG": "标签",
        "TXT_SORT_1": "排序属性1",
        "TXT_SORT_2": "排序属性2",
        "TXT_SORT_3": "排序属性3",
        "TXT_SORT_ASC": "升序",
        "TXT_SORT_DESC": "降序",
        "TXT_REQUIRED": "(必填)",
        "TXT_BEAT_TASK": "价格披露",
        "TXT_UNIQUE": "唯一",
        "TXT_TEMPLATE": "模板",
        "TXT_REVERT_TEMPLATE": "还原模板",
        "TXT_NEED_VERTICAL": "是否更新竖图",
        "TXT_VERTICAL_TEMPLATE": "竖图模板",
        "TXT_VERTICAL_REVERT_TEMPLATE": "竖图还原模板",
        "TXT_TASK_DETAIL": "任务明细一览",
        "TXT_BEAT_TASK_DETAIL": "价格披露任务明细",
        "TXT_IMPORT_GOOD": "导入商品",
        "TXT_ADD_MOD_GOOD": "添加/修改 商品",
        "TXT_DOWNLOAD_TASK_DETAIL": "下载任务明细",
        "TXT_STARTUP_ALL": "启动所有",
        "TXT_STOP_ALL": "停止所有",
        "TXT_REVERT_ALL": "还原所有",
        "TXT_SHOW_ALL": "显示所有",
        "TXT_STARTUP": "启动",
        "TXT_STOP": "停止",
        "TXT_REVERT": "还原",
        "TXT_NUMIID_FULL": "商品的数字 ID ( num_iid )",
        "TXT_CODE_FULL": "商品的 Code",
        "TXT_CUST_QUERY_ATTR": "自定义查询条件",
        "TXT_TASK_NAME": "任务名",
        "TXT_TIME_START": "开始时间",
        "TXT_TIME_END": "结束时间",
        "TXT_TASK_TYPE":"任务类型",
        "TXT_TASK_DATE":"任务时间",
        "TXT_TEJIABAO_DETAIL":"特价宝明细一览",
        "TXT_PENDING":"等待",
        "TXT_SUCCESS":"成功",
        "TXT_FAIL":"失败",
        "TXT_PRICE_ATTRIBUTE": "价格属性",
        "TXT_SALES_ATTRIBUTE": "销售属性",
        "TXT_PERSONAL_FINISHED_TRANSLATION": "个人完成翻译数",
        "TXT_UN_TRANSLATION": "待翻译总数",
        "TXT_TRANSLATED": "完成翻译总数",
        "TXT_DISTRIBUTION_RULE": "分发规则",
        "TXT_MAIN_PRODUCT": "主商品",
        "TXT_GET_TASK_COUNT": "获取任务数量",
        "TXT_PRODUCT_NAME_WITH_LONG_DESCRIPTION": "产品标题 / 长描述",
        "TXT_LONG_TITLE_WITH_LONG_DESCRIPTION": "长标题中文",
        "TXT_MID_TITLE_WITH_SHORT_DESCRIPTION": "中标题 / 长描述中文",
        "TXT_SHORT_TITLE_WITH_MORE_SHORT_DESCRIPTION": "短标题标题 / 短描述中文",
        "TXT_TRANSLATOR_WIT_COLON": "译者：",
        "TXT_BASE_ATTRIBUTE": "共通属性",
        "TXT_CUST_ATTRIBUTE": "自定义属性",
        "TXT_TRANSSTS_ATTRIBUTE": "翻译状态",
        "TXT_IMAGE_MANAGER" : "图片管理",
        "TXT_WAITING_UPLOAD": "待上传",
        "TXT_UPLOAD_SUCCESS": "上传成功",
        "TXT_UPLOAD_FAILED": "上传失败",
        "TXT_DATA_TYPE": "数据类型",
        "TXT_SPECIAL_DESCRIPTION": "特殊说明",
        "TXT_BRAND_STORY": "品牌故事图",
        "TXT_SIZE_CHART": "尺码图",
        "TXT_SHIPPING_DESCRIPTION": "物流介绍",
        "TXT_INDEX": "编号",
        "TXT_ORIGIN_IMAGE_URL": "原始图片地址",
        "TXT_JM_IMAGE_URL": "聚美图片地址",
        "TXT_SET_DEFAULT_VALUE": "设定图片默认项",
        "TXT_SHIP_STOCK": "发货仓库",
        "TXT_RELEASE_DATE": "保质期限",
        "TXT_PRODUCTION_AREA": "生产地区",
        "TXT_SUIT_CROWDS": "适合人群",
        "TXT_WHITE_SQUARE_MODEL": "白底方图模板",
        "TXT_PRODUCT_REALLY_MODEL": "商品实拍图模板",
        "TXT_PRODUCT_UPRIGHT_MODEL": "商品竖图模板",
        "TXT_SPECIAL_NOTE": "特殊说明",
        "TXT_ACTIVITY_IMAGE_SETTING": "聚美共通图片设定",




        "TXT_MSG_SEARCH": "检索...",
        "TXT_MSG_INVALID_FEILD": "请检查这些属性 [ <h4>{{fields}}</h4> ], 然后重新尝试保存. (。・`ω´・)",
        "TXT_MSG_PAGE_IS_BUILDING": "该页面正在建设中...",
        "TXT_MSG_SEARCH_INDEX_FUZZY_SEARCH": "查询包括:产品Code(多项换行分割),款号(多项换行分割),产品名称（中文）,产品名称（英文）,详情描述（中文）,详情描述（英文）",
        "TXT_MSG_SEARCH_INDEX_FUZZY_SEARCH_2": "查询包括:产品Code(多项换行分割),款号(多项换行分割)",
        "TXT_MSG_UPDATE_SUCCESS": "更新操作成功.",
        "TXT_MSG_UPDATE_FAIL": "更新操作失败.",
        "TXT_MSG_NO_ROWS_SELECT": "请至少选择一条数据.",
        "TXT_MSG_NO_PRODUCT_ROWS": "请至少保证有一条产品数据",
        "TXT_MSG_NO_CATEGORY_SELECT": "请选择一个子类目.",
        "TXT_MSG_IS_NOT_CHILE_CATEGORY": "选择的类目不是一个子类目.",
        "TXT_MSG_CONFIRM_CHANGE_MASTER_PRODUCT": "如果您变更主商品,将会对平台的商品信息产生一些影响.<br>您确定要执行这个操作吗?",
        "TXT_MSG_CONFIRM_IS_CHANGE_CATEGORY": "如果您切换主类目,产品的属性将会被重置.<br>您确定要执行这个操作吗?",
        "TXT_MSG_NO_DATE": "当前数据为空...",
        "TXT_MSG_PRODUCT_IS_PUBLISHING": "所操作的产品处于上新中,不能切换主类目.",
        "TXT_MSG_CONFIRM_FROWARD_PARENT_CATEGORY": "如果您继承父类目,以前设置的属性将会被替换点.<br>您确定要执行这个操作吗?",
        "TXT_MSG_NO_FIND_FORWARD_CATEGORY": "没有可继承的父类目.",
        "TXT_MSG_DELETE_ITEM": "您确定要删除这条数据吗?",
        "TXT_MSG_DELETE_SUCCESS": "删除操作成功",
        "TXT_MSG_NO_DATA_WITH_SAVE": "请确保必填项,以及列表中不为空",
        "TXT_MSG_NO_PLATFORM_CATEGORY": "没有取到任何平台类目... 尝试换一个平台试试 ?",
        "TXT_MSG_VALUE_SETTING_COMMENT": "值设定说明：",
        "TXT_MSG_VALUE_SETTING_COMMENT_1": "如果不对属性进行任何值设定，则会使用默认值。",
        "TXT_MSG_VALUE_SETTING_COMMENT_2": "如果对属性进行了多个值设定，则会使用顺序验证可用性。即如果条件，则先验证条件，无条件的，直接为可用。一旦某一条设定生效（可用）",
        "TXT_MSG_CANNOT_GET": "无法取得 ",
        "TXT_MSG_TYPE_VALUE": " 类型的匹配值.",
        "TXT_MSG_MUST_GET_ONE_VALUE": "必须匹配一类值才能保存.",
        "TXT_MSG_NO_VALUE_IS_ON_THE_ATTRIBUTE": "没有匹配到任何属性或内容上.",
        "TXT_MSG_UNVALID_CONDITION": "无效的条件.",
        "TXT_MSG_PRODUCT_CAN_NOT_EDIT": "该商品正在主类目切换中,请稍等...",
        "TXT_MSG_DO_DELETE": "您确定要删除: ",
        "TXT_MSG_LONG_TITLE":"长标题",
        "TXT_MSG_MIDDLE_TITLE":"中标题",
        "TXT_MSG_SHORT_TITLE":"短标题",
        "TXT_MSG_LONG_DESCRIPTION":"长描述",
        "TXT_MSG_SHORT_DESCRIPTION":"短描述",
        "TXT_MSG_UNVALID_URL": "无效的地址.",
        "TXT_MSG_NO_UPLOAD": "请选择要提交的文件",
        "TXT_MSG_CODE_IN_OTHER": "你提交的商品,已经在其他任务中.你确定要继续?",
        "TXT_MSG_REIMPORT_BEAT": "从新上传会覆盖原数据, 意味着之前的数据将被清空. 你确定要继续么?",
        "TXT_MSG_ERROR_BEAT_ITEM": "这个任务的商品信息好像有问题? 你确定要修改它的状态?",
        "TXT_MSG_INPUT_WORD_LENCHK": "你还可以输入 ",
        "TXT_MSG_INPUT_WORD_LENCHK2": " 个文字",
        "TXT_MSG_FIELD_VAL_INVALID": "属性(字段)的值无效, 请根据提示修改.",
        "TXT_MSG_INPUT_WORD_LENLOWLIMIT": "请至少输入 ",
        "TXT_MSG_INPUT_WORD_LENLIMIT": "已经达到最大长度字符数限制",
        "TXT_MSG_HAVE_UN_TRANSLATED_TASK": "您还有未完成的翻译项目, 请完成后再获取新的任务!",
        "TXT_MSG_UPLOAD_IMAGE_SUCCESS": "图片上传/刷新成功.",


        "BTN_CREATE_TASK": "新建任务",
        "BTN_CREATE_BEAT_TASK": "新建价格披露任务",
        "BTN_CREATE_TE_JIA_BAO_TASK": "新建特价宝任务",
        "BTN_ADD_CONDITION": "新增条件",
        "BTN_CANCEL": "取消",
        "BTN_CLOSE": "关闭",
        "BTN_TODAY": "今日",
        "BTN_SAVE": "保存",
        "BTN_SEARCH": "检索",
        "BTN_ADD_TO_PROMOTION": "参加活动",
        "BTN_BATCH_UPDATE_ATTRIBUTE": "批量更新",
        "BTN_CHANGE_MASTER_CATEGORY": "切换主类目",
        "BTN_OK": "确定",
        "BTN_CLEAR": "清空",
        "BTN_EXPORT": "导出",
        "BTN_GO": "Go",
        "BTN_CREATE": "新建",
        "BTN_NEW_DICT_VALUE": "新增字典值",
        "BTN_NEW_DICT_CUS_VALUE": "新增自定义",
        "BTN_SET_PARAM": "修改参数",
        "BTN_NEW_DICT": "新字典项",
        "BTN_NEW_PROMOTION": "新建活动",
        "BTN_MAPPING_CATEGORY": "类目匹配",
        "BTN_NEW_DICTIONARY": "新增字典",
        "BTN_NEW_DICTIONARY_VALUE": "新增字典值",
        "BTN_NEW_DICTIONARY_DEFINE": "新增自定义",
        "BTN_FORWARD": "继承",
        "BTN_MAPPING_ATTRIBUTE": "属性匹配",
        "BTN_MAPPING_ATTRIBUTE_COMMON_MAIN": "属性通用匹配",
        "BTN_OTHER_PLATFORM": "其他平台",
        "BTN_NEW_ATTRIBUTE": "新增属性",
        "BTN_SAVE_ALL": "全部保存",
        "BTN_EDIT": "编辑",
        "BTN_DELETE": "删除",
        "BTN_ADD": "追加",
        "BTN_REFRESH": "刷新",
        "BTN_PROMOTION_HISTORY": "活动履历",
        "BTN_PRICE_HISTORY": "价格履历",
        "BTN_DOWNLOAD": "下载",
        "BTN_IMPORT_PROMOTION_FILE": "导入活动文件",
        "BTN_CHOOSE_FILE": "选择文件",
        "BTN_IMPORT_FILE": "Import File",
        "BTN_CUSTOMIZE_COLUMNS": "自定义列设置",
        "BTN_GET_TASK": "获取任务",
        "BTN_COMPLETE": "完成",
        "BTN_SET_DEFAULT_VALUE": "设定默认项",

        // 枚举 com.voyageone.cms.enums.BeatFlag 的翻译
        "STOP": "已停止",
        "BEATING": "正在执行",
        "SUCCESS": "更新成功",
        "FAIL": "更新失败",
        "REVERT": "正在还原",
        "RE_SUCCESS": "还原成功",
        "RE_FAIL": "还原失败",
        "CANT_BEAT": "信息错误"
    };
});