define(function () {
    return {
        // normal texts
        "TXT_ACTION": "Action",
        "TXT_ALERT": "Alert",
        "TXT_ALL": "All",
        "TXT_CATEGORY": "Category",
        "TXT_COMMENTS": "Comments",
        "TXT_CONFIRM": "Confirm",
        "TXT_CONFIRM_TO_CANCEL_ORDER": "Do you confirm to cancel this order?",
        "TXT_CONFIRM_TO_CANCEL_SKU": "Do you confirm to cancel this SKU?",
        "TXT_CURRENT_SHIPMENT": "Current Shipment",
        "TXT_DESCRIPTION": "Description",
        "TXT_EXPORT_ERROR_FILE": "Export Error File",
        "TXT_EXPRESS_COMPANY": "Express",
        "TXT_FEED": "Feed",
        "TXT_FEED_IMPORT_RESULT": "Feed Import Result",
        "TXT_FEED_INFO_SEARCH": "Feed Info Search",
        "TXT_FEED_INFO_UPLOAD": "Feed File Upload",
        "TXT_FILE_NAME": "File Name",
        "TXT_FROM": "From",
        "TXT_HOME": "Home",
        "TXT_IMAGE": "Image",
        "TXT_IMAGE_PREVIEW":"Image Preview",
        "TXT_ITEMS": "Items",
        "TXT_MISSING_REQUIRED_CHANNEL_CONFIG": "Missing required configures for this channel, please contact with the system administrator for help.",
        "TXT_MSG_NO_DATA": "No Data...",
        "TXT_MSG_NO_UPLOAD": "Please choose a file",
        "TXT_MSG_UPLOAD_SUCCESS": "Upload feed file success",
        "TXT_NAME": "Name",
        "TXT_NEW_SHIPMENT": "New Shipment",
        "TXT_NO_CURRENT_SHIPMENT": "No Current Shipment",
        "TXT_OF": "of",
        "TXT_OPEN": "Open",
        "TXT_ORDER_BY_ORDER": "Order by Order",
        "TXT_ORDER_BY_SKU": "Order by SKU",
        "TXT_ORDER_DATE": "Order Date",
        "TXT_ORDER_ID": "Order ID",
        "TXT_PAGE": "Page",
        "TXT_PAGER_SIZE": "Page Size",
        "TXT_PARENT_SKU": "Parent SKU",
        "TXT_PLEASE_INPUT_A_VALID_DATE": "Please input a valid date.",
        "TXT_PRICE": "Price",
        "TXT_REPORT_ID": "Report ID",
        "TXT_SEARCH": "Search",
        "TXT_SELECT_EXPRESS_COMPANY": "Express Company",
        "TXT_SELECT_NO_VALUE": "Select...",
        "TXT_SHIPMENT_HAVE_BEEN_EDITED": "FAILED: Shipment have changed before your action!",
        "TXT_SHIPMENT_NAME": "Shipment Name",
        "TXT_SHIPPED": "Shipped",
        "TXT_SHIPPED_DATE": "Shipped Date",
        "TXT_SHOWING": "Showing",
        "TXT_SHOWING_NO": "The",
        "TXT_SKU": "SKU",
        "TXT_SKU_NUMBER": "SKU Number",
        "TXT_STATUS": "Status",
        "TXT_TO": "To",
        "TXT_TRACKING_NO_": "Tracking No.",
        "TXT_UPLOAD_DATE": "Upload Date",
        "TXT_UPLOAD_USER": "Upload User",
        "TXT_SUCCESS": "Success",
        "TXT_ITEM_NOT_FOUND": "Scanned item not found in this order.",
        "TXT_ITEM_NOT_FOUND_SKU": "Scanned item not found in OPEN orders.",
        "TXT_VO_PRICE": "VoPrice",
        "TXT_SALE_PRICE": "SalePrice",
        "TXT_SCANNED_ORDER_NOT_FINISHED": "SKUs in the orders [%s] have not been scanned completely, do you want to continue with these orders ignored?",
        "TXT_COMPLETE": "Complete",
        "TXT_BARCODE": "Barcode",
        "TXT_NO_": "No.",
        "TXT_ORDER_INFO": "Order Info",
        "TXT_ORDER": "Order",
        "TXT_SHIPMENT": "Shipment",
        "TXT_SHIPMENT_INFO": "Shipment Info",
        "TXT_ORDER_TOTAL": "Order Total",
        "TXT_SKU_TOTAL": "SKU Total",
        "TXT_SHIPMENT_DETAIL": "Shipment Detail",
        "TXT_NO_SHIPMENT_SELECTED": "No Shipment selected.",

        // buttons
        "BTN_ADD_TO_SHIPMENT": "ADD TO SHIPMENT",
        "BTN_CANCEL": "CANCEL",
        "BTN_DOWNLOAD_PICKING_LIST": "DOWNLOAD PICKING LIST",
        "BTN_END_SHIPMENT": "END SHIPMENT",
        "BTN_GO": "GO",
        "BTN_NEW_SHIPMENT": "NEW SHIPMENT",
        "BTN_OK": "OK",
        "BTN_SEARCH": "SEARCH",
        "BTN_UPLOAD": "UPLOAD",
        "BTN_CLOSE": "CLOSE",
        "BTN_SUBMIT": "SUBMIT",
        "BTN_CREATE": "CREATE",
        "BTN_CONFIRM": "CONFIRM",
        "BTN_BACK": "BACK",
        "BTN_SHIPPED": "SHIPPED",
        "BTN_SCAN": "SCAN"
    }
});