define(function () {
    return {
        // normal texts
        "TXT_ACTION": "Action",
        "TXT_ALERT": "Alert",
        "TXT_ALL": "All",
        "TXT_BARCODE": "Barcode",
        "TXT_CATEGORY": "Category",
        "TXT_CHOOSE_FILE": "Choose File",
        "TXT_COMMENTS": "Comments",
        "TXT_COMPLETE": "Complete",
        "TXT_COMPLETED": "Completed",
        "TXT_CONFIRM": "Confirm",
        "TXT_CONFIRM_FINANCIAL_REPORT": "Do you want to confirm this financial report?",
        "TXT_CONFIRM_SHIPPED": "Confirm shipped?",
        "TXT_CONFIRM_TO_CANCEL_ORDER": "Do you confirm to cancel this order?",
        "TXT_CONFIRM_TO_CANCEL_SKU": "Do you confirm to cancel this SKU?",
        "TXT_CONTAINERIZING_TIME": "Scanned Time",
        "TXT_CONTAINERIZING_USER": "Scanned User",
        "TXT_CURRENT_SHIPMENT": "Current Shipment",
        "TXT_DESCRIPTION": "Description",
        "TXT_DETAIL": "Detail",
        "TXT_EDIT": "Edit",
        "TXT_ERROR": "Error",
        "TXT_ERROR_SHIPMENTS": "#Error Shipments",
        "TXT_EXPORT_ERROR_FILE": "Export Error Detail File",
        "TXT_EXPORT_REPORT": "Export Report",
        "TXT_EXPRESS_COMPANY": "Delivery",
        "TXT_FAIL_TO_UPLOAD_FILE": "Fail to upload file.",
        "TXT_FEED": "Feed",
        "TXT_FILE_NAME": "File Name",
        "TXT_FINANCIAL": "Financial",
        "TXT_FINANCIAL_REPORT": "Financial Report",
        "TXT_FROM": "From",
        "TXT_FULFILLMENT_STATUS": "Fulfillment Status",
        "TXT_HOME": "Home",
        "TXT_IMAGE": "Image",
        "TXT_IMAGE_PREVIEW":"Image Preview",
        "TXT_INVENTORY": "Inventory",
        "TXT_INVENTORY_FEED_UPLOAD": "Inventory Feed Upload",
        "TXT_ITEM_NOT_FOUND": "Barcode can not be found in this order, please check and try again later.",
        "TXT_ITEM_NOT_FOUND_SKU": "Barcode can not be found in OPEN orders, please check and try again later.",
        "TXT_ITEMS": "Items",
        "TXT_MISSING_REQUIRED_CHANNEL_CONFIG": "Missing required configures for this channel, please contact the system administrator for help.",
        "TXT_MSG_NO_DATA": "No Data...",
        "TXT_MSG_NO_UPLOAD": "Please choose a file",
        "TXT_NAME": "Name",
        "TXT_NEW_SHIPMENT": "New Shipment",
        "TXT_NO_": "No.",
        "TXT_NO_CURRENT_SHIPMENT": "No Current Shipment",
        "TXT_NO_SHIPMENT_SELECTED": "No Shipment selected.",
        "TXT_NOTHING_TO_SHIP": "End shipment failure, shipment can not be empty.",
        "TXT_OF": "of",
        "TXT_OPEN": "Open",
        "TXT_ORDER": "Order",
        "TXT_ORDER_BY_ORDER_ID": "Order by Order ID",
        "TXT_ORDER_BY_SKU": "Order by SKU",
        "TXT_ORDER_DATE": "Order Date",
        "TXT_ORDER_ID": "Order ID",
        "TXT_ORDER_INFO": "Order Info",
        "TXT_ORDER_TOTAL": "Total #Orders",
        "TXT_ORDERS_TO_BE_FULFILLED": "#Orders to be fulfilled",
        "TXT_PAGE": "Page",
        "TXT_PAGER_SIZE": "Page Size",
        "TXT_PARENT_SKU": "Parent SKU",
        "TXT_PENDING": "Pending",
        "TXT_PLEASE_INPUT_A_VALID_DATE": "Please input a valid date.",
        "TXT_PRICE": "Price",
        "TXT_PRODUCT_FEED_IMPORT_STATUS": "Product Feed Import Status",
        "TXT_PRODUCT_FEED_SEARCH": "Product Feed Search",
        "TXT_PRODUCT_FEED_UPLOAD": "Product Feed Upload",
        "TXT_REPORT_ID": "Report ID",
        "TXT_REPORT_PERIOD": "Report Period",
        "TXT_SALE_PRICE": "Retail Price",
        "TXT_SCANNED": "Scanned",
        "TXT_SCANNED_ORDER_NOT_FINISHED": "SKUs in the orders [%s] have not been scanned completely, do you want to continue with these orders ignored?",
        "TXT_SEARCH": "Search",
        "TXT_SELECT_EXPRESS_COMPANY": "Delivery Company",
        "TXT_SELECT_NO_VALUE": "Select...",
        "TXT_SHIPMENT": "Shipment",
        "TXT_SHIPMENT_DETAIL": "Shipment Detail",
        "TXT_SHIPMENT_HAVE_BEEN_EDITED": "FAILED: Shipment has been modified before your action!",
        "TXT_SHIPMENT_INFO": "Shipment Info",
        "TXT_SHIPMENT_NAME": "Shipment Name",
        "TXT_SHIPMENT_NOT_FOUND": "Shipment not found.",
        "TXT_SHIPMENT_STATUS": "Shipment Status",
        "TXT_SHIPPED": "Shipped",
        "TXT_SHIPPED_DATE": "Shipped Date",
        "TXT_SHOWING": "Showing",
        "TXT_SHOWING_NO": "The",
        "TXT_SKU": "SKU",
        "TXT_SKU_LIST": "SKU List",
        "TXT_SKU_NUMBER": "#SKU",
        "TXT_SKU_S_TO_BE_FULFILLED": "#SKUs to be fulfilled",
        "TXT_SKU_TOTAL": "Total #SKUs",
        "TXT_STATUS": "Status",
        "TXT_SUCCESS": "Success",
        "TXT_TO": "To",
        "TXT_TOTAL_PRICE": "Total Price",
        "TXT_TRACKING_NO_": "Tracking No.",
        "TXT_UPLOAD_DATE": "Upload Date",
        "TXT_UPLOAD_FEED_FILE_SUCCESS": "Upload feed file success",
        "TXT_UPLOAD_INVENTORY_FILE_SUCCESS": "Upload inv file success",
        "TXT_UPLOAD_USER": "Upload User",
        "TXT_VO_PRICE": "VO Price",
        "TXT_WELCOME": "Welcome",
        "TXT_YEAR_MONTH": "Year-Month",

        // buttons
        "BTN_ADD_TO_SHIPMENT": "ADD TO SHIPMENT",
        "BTN_BACK": "BACK",
        "BTN_CANCEL": "CANCEL",
        "BTN_CLOSE": "CLOSE",
        "BTN_CONFIRM": "CONFIRM",
        "BTN_CREATE": "CREATE",
        "BTN_DOWNLOAD_PICKING_LIST": "DOWNLOAD PICKING LIST",
        "BTN_END_SHIPMENT": "END SHIPMENT",
        "BTN_GO": "GO",
        "BTN_NEW_SHIPMENT": "NEW SHIPMENT",
        "BTN_OK": "OK",
        "BTN_SCAN": "SCAN",
        "BTN_SEARCH": "SEARCH",
        "BTN_SHIPPED": "SHIP",
        "BTN_SUBMIT": "SUBMIT",
        "BTN_UPLOAD": "UPLOAD"
    }
});