define(function () {
    return {
        // normal texts
        "TXT_ACTION": "Action",
        "TXT_ALERT": "Alert",
        "TXT_ALL": "All",
        "TXT_CONFIRM": "Confirm",
        "TXT_CONFIRM_TO_CANCEL_ORDER": "Do you confirm to cancel this order?",
        "TXT_CONFIRM_TO_CANCEL_SKU": "Do you confirm to cancel this SKU?",
        "TXT_CURRENT_SHIPMENT": "Current Shipment",
        "TXT_DESCRIPTION": "Description",
        "TXT_EXPORT_ERROR_FILE": "Export Error File",
        "TXT_EXPRESS_COMPANY": "Express Company",
        "TXT_FEED": "Feed",
        "TXT_FEED_IMPORT_RESULT": "Feed Import Result",
        "TXT_FILE_NAME": "File Name",
        "TXT_FROM": "From",
        "TXT_HOME": "Home",
        "TXT_ITEMS": "Items",
        "TXT_MISSING_REQUIRED_CHANNEL_CONFIG": "Missing required configures for this channel, please contact with the system administrator for help.",
        "TXT_MSG_NO_DATA": "No Data...",
        "TXT_MSG_NO_UPLOAD": "Please choose a file",
        "TXT_MSG_UPLOAD_SUCCESS": "Upload feed file success",
        "TXT_NO_CURRENT_SHIPMENT": "No Current Shipment",
        "TXT_OF": "of",
        "TXT_ORDER_BY_ORDER": "Order by Order",
        "TXT_ORDER_BY_SKU": "Order by SKU",
        "TXT_ORDER_DATE": "Order Date",
        "TXT_ORDER_ID": "Order ID",
        "TXT_PAGE": "Page",
        "TXT_PAGER_SIZE": "Page Size",
        "TXT_PLEASE_INPUT_A_VALID_DATE": "Please input a valid date.",
        "TXT_PRICE": "Price",
        "TXT_SEARCH": "Search",
        "TXT_SELECT_NO_VALUE": "Select...",
        "TXT_SHIPMENT_NAME": "Shipment Name",
        "TXT_SHOWING": "Showing",
        "TXT_SHOWING_NO": "The",
        "TXT_SKU": "SKU",
        "TXT_STATUS": "Status",
        "TXT_TO": "To",
        "TXT_UPLOAD_DATE": "Upload Date",
        "TXT_UPLOAD_USER": "Upload User",

        // buttons
        "BTN_ADD_TO_SHIPMENT": "ADD TO SHIPMENT",
        "BTN_CANCEL": "CANCEL",
        "BTN_DOWNLOAD_PICKING_LIST": "DOWNLOAD PICKING LIST",
        "BTN_END_SHIPMENT": "END SHIPMENT",
        "BTN_GO": "GO",
        "BTN_NEW_SHIPMENT": "NEW SHIPMENT",
        "BTN_OK": "OK",
        "BTN_SEARCH": "SEARCH",
        "BTN_UPLOAD": "UPLOAD"
    }
});