/*
 * VmsBtClientOrdersDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.vms;

import com.voyageone.service.model.vms.VmsBtClientOrdersModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface VmsBtClientOrdersDao {
    List<VmsBtClientOrdersModel> selectList(Object map);

    VmsBtClientOrdersModel selectOne(Object map);

    int selectCount(Object map);

    VmsBtClientOrdersModel select(Integer id);

    int insert(VmsBtClientOrdersModel record);

    int update(VmsBtClientOrdersModel record);

    int delete(Integer id);
}