/*
 * VmsBtFeedInfoTempDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.vms;

import com.voyageone.service.model.vms.VmsBtFeedInfoTempModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface VmsBtFeedInfoTempDao {
    List<VmsBtFeedInfoTempModel> selectList(Map<String, Object> map);

    VmsBtFeedInfoTempModel selectOne(Map<String, Object> map);

    VmsBtFeedInfoTempModel select(Integer id);

    int insert(VmsBtFeedInfoTempModel record);

    int update(VmsBtFeedInfoTempModel record);

    int delete(Integer id);
}