/*
 * TmOrderChannelConfigDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.admin;

import com.voyageone.service.model.admin.TmOrderChannelConfigModel;
import org.springframework.stereotype.Repository;

@Repository
public interface TmOrderChannelConfigDao {
    int insert(TmOrderChannelConfigModel record);
}