/*
 * TmPortConfigDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.admin;

import com.voyageone.service.model.admin.TmPortConfigModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface TmPortConfigDao {
    List<TmPortConfigModel> selectList(Map<String, Object> map);

    TmPortConfigModel selectOne(Map<String, Object> map);

    int selectCount(Map<String, Object> map);

    TmPortConfigModel select(Integer seq);

    int insert(TmPortConfigModel record);

    int update(TmPortConfigModel record);

    int delete(Integer seq);
}