/*
 * ComLogDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.dao.user;


import java.util.List;

import com.voyageone.service.model.user.ComLogModel;
import org.springframework.stereotype.Repository;

@Repository
public interface ComLogDao {
    List<ComLogModel> selectList(Object map);

    ComLogModel selectOne(Object map);

    int selectCount(Object map);

    ComLogModel select(Integer id);

    int insert(ComLogModel record);

    int update(ComLogModel record);

    int delete(Integer id);
}