/*
 * BiReportSalesSku010Model.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.report;

import java.math.BigDecimal;

/**
 * 
 */
public class BiReportSalesSku010Model extends BiReportSalesSku010Key {
    protected Integer productId;

    protected Integer modelId;

    /**
     * 销售数量
     */
    protected Integer qty;

    /**
     * 销售金额
     */
    protected BigDecimal amt;

    /**
     * 买家数
     */
    protected Integer buyers;

    /**
     * 访客数
     */
    protected Integer uv;

    /**
     * 浏览量
     */
    protected Integer pv;

    /**
     * 收藏件数
     */
    protected Integer addFavorite;

    /**
     * 加购件数
     */
    protected Integer addCart;

    /**
     * 平均访问时间
     */
    protected BigDecimal visitTimeAvg;

    /**
     * 跳失率
     */
    protected BigDecimal bounceRate;

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getModelId() {
        return modelId;
    }

    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    public Integer getQty() {
        return qty;
    }

    public void setQty(Integer qty) {
        this.qty = qty;
    }

    public BigDecimal getAmt() {
        return amt;
    }

    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    public Integer getBuyers() {
        return buyers;
    }

    public void setBuyers(Integer buyers) {
        this.buyers = buyers;
    }

    public Integer getUv() {
        return uv;
    }

    public void setUv(Integer uv) {
        this.uv = uv;
    }

    public Integer getPv() {
        return pv;
    }

    public void setPv(Integer pv) {
        this.pv = pv;
    }

    public Integer getAddFavorite() {
        return addFavorite;
    }

    public void setAddFavorite(Integer addFavorite) {
        this.addFavorite = addFavorite;
    }

    public Integer getAddCart() {
        return addCart;
    }

    public void setAddCart(Integer addCart) {
        this.addCart = addCart;
    }

    public BigDecimal getVisitTimeAvg() {
        return visitTimeAvg;
    }

    public void setVisitTimeAvg(BigDecimal visitTimeAvg) {
        this.visitTimeAvg = visitTimeAvg;
    }

    public BigDecimal getBounceRate() {
        return bounceRate;
    }

    public void setBounceRate(BigDecimal bounceRate) {
        this.bounceRate = bounceRate;
    }
}