/*
 * BiReportDownloadTaskModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.report;

import com.voyageone.base.dao.mysql.BaseModel;
import java.util.Date;

/**
 * 报告下载任务表
 */
public class BiReportDownloadTaskModel extends BaseModel {
    /**
     * 文件名称
     */
    protected String fileName;

    /**
     * 文件路径
     */
    protected String filePath;

    /**
     * 任务状态 1为失败，2 位任务正在进行，3为成功完成
     */
    protected Integer taskStatus;

    /**
     * 任务完成时间
     */
    protected Date finishTime;

    /**
     * 是否有效（1:有效；0：无效）
     */
    protected Boolean active;

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    public Integer getTaskStatus() {
        return taskStatus;
    }

    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    public Date getFinishTime() {
        return finishTime;
    }

    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }
}