/*
 * BiReportDownloadTaskModel.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.model.report;

import com.voyageone.base.dao.mysql.BaseModel;
import java.util.Date;

/**
 * 
 */
public class BiReportDownloadTaskModel extends BaseModel {
    public BiReportDownloadTaskModel(){}
    public BiReportDownloadTaskModel(Integer creatorId,String fileName, Date createTime,Integer taskStatus,String creatorName)
    {
        this.creatorId=creatorId;
        this.creatorName=creatorName;
        this.taskStatus=taskStatus;
        this.fileName=fileName;
    }
    /**
     * 创建者id
     */
    protected Integer creatorId;

    /**
     * 文件名称
     */
    protected String fileName;

    /**
     * 创建时间
     */
    protected Date createTime;

    /**
     * 文件路径
     */
    protected String filePath;

    /**
     * 任务状态 1为失败，2 位任务正在进行，3为成功完成
     */
    protected Integer taskStatus;

    /**
     * 任务完成时间
     */
    protected Date finishTime;

    protected Integer attr1;

    protected Integer attr2;

    protected Integer attr3;

    protected String attr4;

    protected String attr5;

    protected String attr6;

    protected String creatorName;

    public Integer getCreatorId() {
        return creatorId;
    }

    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    public Integer getTaskStatus() {
        return taskStatus;
    }

    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    public Date getFinishTime() {
        return finishTime;
    }

    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    public Integer getAttr1() {
        return attr1;
    }

    public void setAttr1(Integer attr1) {
        this.attr1 = attr1;
    }

    public Integer getAttr2() {
        return attr2;
    }

    public void setAttr2(Integer attr2) {
        this.attr2 = attr2;
    }

    public Integer getAttr3() {
        return attr3;
    }

    public void setAttr3(Integer attr3) {
        this.attr3 = attr3;
    }

    public String getAttr4() {
        return attr4;
    }

    public void setAttr4(String attr4) {
        this.attr4 = attr4 == null ? null : attr4.trim();
    }

    public String getAttr5() {
        return attr5;
    }

    public void setAttr5(String attr5) {
        this.attr5 = attr5 == null ? null : attr5.trim();
    }

    public String getAttr6() {
        return attr6;
    }

    public void setAttr6(String attr6) {
        this.attr6 = attr6 == null ? null : attr6.trim();
    }

    public String getCreatorName() {
        return creatorName;
    }

    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }
}