/*
 * ComResourceDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.security.dao;

import com.voyageone.security.model.ComResourceModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface ComResourceDao {
    List<ComResourceModel> selectList(Map<String, Object> map);

    ComResourceModel selectOne(Map<String, Object> map);

    int selectCount(Map<String, Object> map);

    ComResourceModel select(Integer id);

    int insert(ComResourceModel record);

    int update(ComResourceModel record);

    int delete(Integer id);

    List<ComResourceModel> selectListByUserChannel(Integer userId, String channelId);
}