/*
 * ComRoleStoreDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.security.dao;

import com.voyageone.security.model.ComRoleStoreModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface ComRoleStoreDao {
    List<ComRoleStoreModel> selectList(Map<String, Object> map);

    ComRoleStoreModel selectOne(Map<String, Object> map);

    int selectCount(Map<String, Object> map);

    ComRoleStoreModel select(Integer id);

    int insert(ComRoleStoreModel record);

    int update(ComRoleStoreModel record);

    int delete(Integer id);
}