/*
 * ComUserDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.security.dao;

import com.voyageone.security.model.ComUserModel;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public interface ComUserDao {
    List<ComUserModel> selectList(Map<String, Object> map);

    ComUserModel selectOne(Map<String, Object> map);

    int selectCount(Map<String, Object> map);

    ComUserModel select(Integer id);

    int insert(ComUserModel record);

    int update(ComUserModel record);

    int delete(Integer id);
}