
define(function(){
    return {
        data:[
            {
                id:1,
                name:'运动鞋',
                checked:1,
                oldChecked:1,
                children:[]
            },
            {
                id:2,
                name:'厨具',
                checked:1,
                oldChecked:1,
                children:[
                    {
                        id:21,
                        name:'刀子',
                        checked:2,
                        oldChecked:2,
                        children:[]
                    },
                    {
                        id:22,
                        name:'铲子',
                        checked:0,
                        oldChecked:0,
                        children:[]
                    }
                ]
            },
            {
                id:3,
                name:'母婴',
                checked:0,
                oldChecked:0,
                children:[
                    {
                        id:31,
                        name:'婴儿车',
                        checked:0,
                        oldChecked:0,
                        children:[]
                    },
                    {
                        id:32,
                        name:'尿不湿',
                        checked:1,
                        oldChecked:1,
                        children:[]
                    }
                ]
            },
            {
                id:4,
                name:'裤子',
                checked:0,
                oldChecked:0,
                children:[
                    {
                        id:41,
                        name:'喇叭裤',
                        checked:0,
                        oldChecked:0,
                        children:[]
                    },
                    {
                        id:42,
                        name:'牛仔裤',
                        checked:1,
                        oldChecked:1,
                        children:[]
                    }
                ]
            }
        ]
    }
});
