define(function () {
    return {
        /**渠道管理-渠道信息一览*/
        "TXT_CART_MANAGEMENT": "渠道管理",
        "TXT_CART_INFO_MANAGEMENT": "渠道信息管理",
        "TXT_CART_INFO_MANAGEMENT_CONFIG": "渠道信息管理-配置",
        "TXT_CART_COMPANY_NAME": "公司名",
        "TXT_CART_FULL_NAME": "渠道(全)名",
        "TXT_CART_SEND_NAME": "发送名",
        "TXT_CART_SEND_TEL": "发送电话",
        "TXT_CART_SEND_ZIP": "发送邮编",
        "TXT_CART_SEND_ADDRESS": "发送地址",
        "TXT_SELECT_ALL": "全选",
        "TXT_CART_CHANNEL_ID": "渠道ID",
        "TXT_CART_CHANNEL_NAME": "渠道名",
        "TXT_CART_CHANNEL_FULL_NAME": "渠道全名",
        "TXT_CART_IS_USJOI": "是否为集合店",
        "TXT_CART_CHANNEL_CART": "渠道店铺",
        "TXT_CART_CHANNEL_CART_NAME": "渠道店铺名",
        "TXT_STATUS": "状态",
        "TXT_CART_UPDATE_TIME": "更新时间",
        "TXT_UPDATER": "更新人",
        "TXT_POP_CONFIG": "配置",
        "TXT_CART_NAME": "渠道名",
        "TXT_PROPERTY_NAME": "属性名",
        "TXT_PROPERTY_VALUE": "属性值",
        "TXT_COMMENTS": "备注",
        "TXT_SELECT_NO_VALUE": "请选择...",
        "TXT_YES":"是",
        "TXT_NO":"否",
        "TXT_POP_EDIT": "编辑",
        "TXT_ICON_ADDRESS":"图标地址",
        "TXT_SHIPPER":"发货人",
        "TXT_SHIPPER_TEL":"发货人电话",
        "TXT_SHIPPER_ZIP":"发货人邮编",
        "TXT_SHIPPER_ADDRESS":"发货人地址",
        "TXT_SECRET_KEY":"Secret Key",
        "TXT_SESSION_KEY":"Session Key",
        "TXT_CHOOSED":"已选择",
        "TXT_CHOOSE":"可选择",

        /**按钮组*/
        "TXT_LOGOUT": "注销",
        "BTN_CANCEL": "取消",
        "BTN_SAVE": "保存",
        "BTN_OK":"确认",
        "BTN_GO": "Go",
        "BTN_ACTIVE":"启用",
        "BTN_INACTIVE": "禁用",


        /**分页显示*/
        "TXT_PAGER_SIZE": "每页显示",
        "TXT_SHOWING_NO": "第",
        "TXT_PAGE": "页",
        "TXT_SHOWING": "显示",
        "TXT_OF": "之",
        "TXT_ITEMS": "件数",
        "TXT_MSG_NO_DATE": "当前数据为空...",

        /**确认框*/
        "TXT_CONFIRM":"确认",
        "TXT_POP_ADD":"添加",
        "TXT_CONFIRM_DELETE_MSG":"您确定要删除选定的渠道信息吗?",
        "TXT_MSG_NO_ROWS_SELECT": "请至少选择一条数据.",

        /**警告框*/
        "TXT_ALERT": "温馨提示",
        "TXT_WARNING": "警告",
        "TXT_COMPLETE_INFO": "请完善当前页面的输入内容",

        "INVALID_EMAIL": "请输入正确的E-Mail地址",
        "INVALID_URL": "请输入正确的URL地址",
        "INVALID_DATE": "请输入正确的日期",
        "INVALID_DATETIMELOCAL": "请输入正确的日期时间",
        "INVALID_COLOR": "请输入正确的颜色",
        "INVALID_RANGE": "请输入正确的排列",
        "INVALID_MONTH": "请输入正确的月份",
        "INVALID_TIME": "请输入正确的时间",
        "INVALID_WEEK": "请输入正确的星期",
        "INVALID_NUMBER": "请输入正确的数字",
        "INVALID_REQUIRED": "请输入数据",
        "INVALID_MAXLENGTH": "请输入的数据长度不能超过:{{value}}",
        "INVALID_MINLENGTH": "请输入的数据长度不能短于:{{value}}",
        "INVALID_MAX": "请输入的数据不能大于:{{value}}",
        "INVALID_MIN": "请输入的数据不能小于:{{value}}",
        "INVALID_PATTERN": "请输入的数据必须满足规则:{{value}}",
    };
});