define(function () {
    return {
        /**渠道管理-渠道信息一览*/
        "TXT_CART_MANAGEMENT": "渠道管理",
        "TXT_CART_INFO_MANAGEMENT": "渠道信息管理",
        "TXT_CART_INFO_MANAGEMENT_CONFIG": "渠道信息管理-配置",
        "TXT_CART_COMPANY_NAME": "公司名",
        "TXT_CART_FULL_NAME": "渠道(全)名",
        "TXT_CART_SEND_NAME": "发送名",
        "TXT_CART_SEND_TEL": "发送电话",
        "TXT_CART_SEND_ZIP": "发送邮编",
        "TXT_CART_SEND_ADDRESS": "发送地址",
        "TXT_SELECT_ALL": "全选",
        "TXT_CART_CHANNEL_ID": "渠道ID",
        "TXT_CART_CHANNEL_NAME": "渠道名",
        "TXT_CART_CHANNEL_FULL_NAME": "渠道全名",
        "TXT_CART_IS_USJOI": "是否为集合店",
        "TXT_CART_CHANNEL_CART": "渠道店铺",
        "TXT_CART_CHANNEL_CART_NAME": "渠道店铺名",
        "TXT_STATUS": "状态",
        "TXT_ACTION": "操作",
        "TXT_CART_UPDATE_TIME": "更新时间",
        "TXT_UPDATER": "更新人",
        "TXT_POP_CONFIG": "配置",
        "TXT_CHANNEL_NAME": "渠道名",
        "TXT_PROPERTY_NAME": "属性名",
        "TXT_PROPERTY_VALUE": "属性值",
        "TXT_COMMENTS": "备注",
        "TXT_SELECT_NO_VALUE": "请选择...",
        "TXT_YES": "是",
        "TXT_NO": "否",
        "TXT_POP_EDIT": "编辑",
        "TXT_ICON_ADDRESS": "图标地址",
        "TXT_SHIPPER": "发货人",
        "TXT_SHIPPER_TEL": "发货人电话",
        "TXT_SHIPPER_ZIP": "发货人邮编",
        "TXT_SHIPPER_ADDRESS": "发货人地址",
        "TXT_SECRET_KEY": "Secret Key",
        "TXT_SESSION_KEY": "Session Key",
        "TXT_CHOOSED": "已选择",
        "TXT_CHOOSE": "可选择",
        "TXT_MSG_SEARCH": "检索...",

        /**渠道类型属性管理一览*/
        "TXT_CHANNEL_TYPE_ATTR_MANAGEMENT": "渠道类型属性管理",
        "TXT_CHANNEL_TYPE_NAME": "类型名",
        "TXT_CHANNEL_LANGUAGE_TYPE": "语言类型",
        "TXT_CHANNEL_ADD_NAME": "添加名",
        "TXT_DISPLAY_SORT": "显示顺序",

        /**第三方配置信息管理*/
        "TXT_CHANNEL_THIRD_PARTY_CONFIG": "第三方配置信息管理",
        "TXT_THIRD_COG_INFO": "第三方配置信息",

        /**短信配置管理*/
        "TXT_CHANNEL_SMS_CONFIG": "短信配置管理",
        "TXT_CHANNEL_SMS_TYPE": "短信类型",
        "TXT_CHANNEL_SMS_CONTENT": "短信内容",
        "TXT_CHANNEL_SMS_CODE": "短信码",
        "TXT_CHANNEL_SMS_DESC": "短信描述",
        "TXT_CHANNEL_SNS_DEL_TARGET": "删除标识",
        "TXT_SMS_COG_INFO": "短信配置信息",

        /**快递信息管理*/
        "TXT_CHANNEL_CARRIER_MANAGEMENT": "快递信息管理",
        "TXT_CARRIER_COG_INFO": "快递配置信息",
        "TXT_CHANNEL_CARRIER_NAME": "快递名",
        "TXT_CHANNEL_CARRIER_ISEBUY": "使用快递100",
        "TXT_CHANNEL_CARRIER_ISEBUY_ID": "使用快递100标识",
        "TXT_CHANNEL_CARRIER_DELETE_ALLOW": "允许删除标识",
        "TXT_API_KEY": "API Key",
        "TXT_API_USER": "API User",
        "TXT_API_PASS": "API Password",
        "TXT_API_URL": "API URL",
        "TXT_CARD_NUMBER": "卡号",
        "TXT_EMS_USER_NAME": "EMS客户名",
        "TXT_CUSTOMER_WEB_SITE": "客户网点",
        "TXT_CUSTOMER_NAME": "客户名",
        "TXT_DELETE_ALLOWED": "允许删除",

        /**cart管理-信息一览*/
        "TXT_CART_MANAGE": "Cart管理",
        "TXT_CART_INFO_MANAGE": "Cart信息管理",
        "TXT_CART_ID": "Cart ID",
        "TXT_NAME_CART": "Cart名",
        "TXT_CART_NAME_(SHORT)": "Cart名（缩写）",
        "TXT_CART_SHORT_NAME": "Cart名缩写",
        "TXT_CART_TYPE": "Cart类型",
        "TXT_CART_DESC": "Cart描述",
        "TXT_PLATFORM_NAME": "平台名",

        /**cart管理-渠道Cart管理*/
        "TXT_CART_CHANNEL_SHOP": "渠道Cart管理",
        "TXT_SHOP_NAME": "商店名",
        "TXT_CART_TRACKING_INFO": "Cart物流信息管理",
        "TXT_CART_SHOP_NAME": "店铺名",
        "TXT_TRACKING_STATE": "物流状态",
        "TXT_TRACKING_LOCATION": "物流位置",
        "TXT_TRACKING_AREA": "物流区域",
        "TXT_TRACKING_INFO": "物流信息",
        "TXT_IS_DISPLAY": "显示标识",
        "TXT_TRACKING_IS_EXPAND": "物流展开标识",
        "TXT_APP_URL": "App URL",
        "TXT_APP_KEY": "App KEY",
        "TXT_APP_SECRET": "App Secret",

        /**仓库管理-信息一览*/
        "TXT_STORE_MANAGE": "仓库管理",
        "TXT_STORE_NAME": "仓库名",
        "TXT_MAIN_STORE_NAME": "主仓库名",
        "TXT_SALE_STATE": "在售状态",
        "TXT_STORE_TYPE": "仓库类型",
        "TXT_STORE_MANAGE_STATE": "库存管理状态",
        "TXT_STORE_REMAINED": "库存保留量",
        "TXT_STORE_REMAINED_NUMBER": "保留量",
        "TXT_STORE_TAG_TYPE": "标签类型",
        "TXT_STORE_AREA": "仓库位置",
        "TXT_STORE_EXCT_TYPE": "仓库类别",
        "TXT_INVENTORY_ASC_TYPE": "库存同步类型",
        "TXT_INVENTORY_ASSIGN_PRE": "库存分配优先级",
        "TXT_TOGETHER_ZONE": "拼单区域",
        "TXT_STORE_ADDRESS": "仓库地址",

        /**task管理-信息一览*/
        "TXT_TASK_MANAGEMENT": "任务管理",
        "TXT_TASK_TYPE": "任务类型",
        "TXT_TASK_NAME": "任务名",
        "TXT_TASK_COMMENT": "任务备注",
        "TXT_TASK_TIME": "任务频次",

        /**系统管理-信息一览*/
        "TXT_SYSTEM_CONFIG": "系统配置管理",
        "TXT_TYPE_ID": "类型ID",
        "TXT_TYPE_NAME": "类型名",
        "TXT_TYPE_INFO_MANAGEMENT": "类型信息管理",
        "TXT_TYPE_ATTRIBUTE_MANAGEMENT": "类型属性信息管理",
        "TXT_PROPERTY_UNIFIED_CONFIG": "属性统一配置管理",
        "TXT_CONFIG_TYPE": "配置类别",
        "TXT_CODE_ATTRIBUTE": "Code属性管理",
        "TXT_CODE": "Code",
        "TXT_CODE_NAME": "Code名",
        "TXT_CODE_DESC": "Code描述",
        "TXT_CODE_ID": "Code ID",
        "TXT_TYPE_ATTR_COG_INFO": "类型属性配置信息",

        /**权限管理一览*/
        "TXT_USER_ADMIN": "用户 / 权限管理",
        "TXT_USER_MANAGEMENT": "用户管理",
        "TXT_ACCOUNT": "账号",
        "TXT_USER_NAME": "用户名",
        "TXT_ORGANIZE": "组织",
        "TXT_SYSTEM": "系统",
        "TXT_ROLE": "角色",
        "TXT_CHANNEL": "渠道",
        "TXT_STORE": "仓库",
        "TXT_EMAIL": "邮箱",
        "TXT_PASSWORD": "密码",
        "TXT_INSTRUCTION": "说明",
        "TXT_ORG_MANAGE": "组织管理",
        "TXT_ORG_NAME": "组织名",
        "TXT_ORG_NAMES": "组织名称",
        "TXT_UPPER_ORG": "上级组织",
        "TXT_SORT_PRE": "排序权重",
        "TXT_ICON": "图标",
        "TXT_ROLE_MANAGEMENT": "角色管理",
        "TXT_ROLE_NAME": "角色名",
        "TXT_NEW_ROLE_COPY": "复制的角色名",
        "TXT_ROLE_TYPE": "角色类型",
        "TXT_ROLE_SYSTEM": "授权系统",
        "TXT_ROLE_CHANNEL": "授权渠道",
        "TXT_ROLE_STORE": "授权仓库",
        "TXT_MENU_MANAGEMENT": "菜单资源管理",
        "TXT_MENU_NAME": "资源名称",
        "TXT_URL": "URL",
        "TXT_TYPE": "类型",
        "TXT_MENU_KEY": "资源 key",
        "TXT_MENU_URL": "资源 URL",
        "TXT_UPPER_MENU": "上级菜单",
        "TXT_RES_TYPE": "资源类型",

        "TXT_LOG_SEARCH": "日志查询",
        "TXT_LOGIN_LOG": "登录日志",
        "TXT_ACT_LOG": "操作日志",
        "TXT_IP_ADDRESS": "IP地址",
        "TXT_LOGED_IN_TIME": "登录时间",
        "TXT_METHOD": "方法",
        "TXT_START_TIME": "开始时间",
        "TXT_WASTE_TIME": "耗时(ms)",
        "TXT_REQUEST_PARAMETER": "请求参数",
        "TXT_RESPONSE": "返回结果",
        "TXT_NEW_SHOP_MANAGEMENT": "开新店管理",
        "TXT_NEWSHOP_GUIDE_TYPE": "向导式开新店",
        "TXT_NEWSHOP_HISTORY": "开新店脚本历史",

        /**按钮组*/
        "TXT_LOGOUT": "注销",
        "TXT_CHANGEPASS": "修改密码",
        "TXT_RESET_PASS": "重置密码",
        "BTN_CANCEL": "取消",
        "BTN_SAVE": "保存",
        "BTN_OK": "确认",
        "BTN_GO": "Go",
        "BTN_ACTIVE": "启用",
        "BTN_INACTIVE": "禁用",
        "TXT_TIME_END": "结束时间",
        "TXT_STATE_RUN": "运行状态",
        "TXT_DISPLAY_STATE": "显示状态",


        /**分页显示*/
        "TXT_PAGER_SIZE": "每页显示",
        "TXT_SHOWING_NO": "第",
        "TXT_PAGE": "页",
        "TXT_SHOWING": "显示",
        "TXT_OF": "之",
        "TXT_ITEMS": "件数",
        "TXT_MSG_NO_DATE": "当前数据为空...",


        /**确认框*/
        "TXT_CONFIRM": "确认",
        "TXT_POP_ADD": "添加",
        "TXT_CONFIRM_DELETE_MSG": "您确定要删除当前选定的信息吗?",
        "TXT_CONFIRM_INACTIVE_MSG": "您确定要禁用当前选定的信息吗?",
        "TXT_MSG_NO_ROWS_SELECT": "请至少选择一条数据.",

        /**警告框*/
        "TXT_ALERT": "温馨提示",
        "TXT_WARNING": "警告",
        "TXT_COMPLETE_INFO": "请完善当前页面的输入内容",
        "TXT_REQUIRED": "(必填)",

        /**输入验证消息*/
        "INVALID_EMAIL": "请输入正确的E-Mail地址",
        "INVALID_URL": "请输入正确的URL地址",
        "INVALID_DATE": "请输入正确的日期",
        "INVALID_DATETIMELOCAL": "请输入正确的日期时间",
        "INVALID_COLOR": "请输入正确的颜色",
        "INVALID_RANGE": "请输入正确的排列",
        "INVALID_MONTH": "请输入正确的月份",
        "INVALID_TIME": "请输入正确的时间",
        "INVALID_WEEK": "请输入正确的星期",
        "INVALID_NUMBER": "请输入正确的数字",
        "INVALID_REQUIRED": "请输入数据",
        "INVALID_MAXLENGTH": "请输入的数据长度不能超过:{{value}}",
        "INVALID_MINLENGTH": "请输入的数据长度不能短于:{{value}}",
        "INVALID_MAX": "请输入的数据不能大于:{{value}}",
        "INVALID_MIN": "请输入的数据不能小于:{{value}}",
        "INVALID_PATTERN": "请输入的数据必须满足规则:{{value}}"

    };
});