/*
 * CmsBtPriceConfirmLogDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.daoext.cms;

import com.voyageone.service.model.cms.CmsBtPriceConfirmLogModel;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface CmsBtPriceConfirmLogDaoExt {
    int updateCodeForMove(@Param("channelId") String channelId, @Param("itemCodeOld") String itemCodeOld, @Param("skuList") List<String> skuList, @Param("itemCodeNew") String itemCodeNew, @Param("modifier") String modifier);
}