/*
 * CmsBtUsWorkloadDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.daoext.cms;

import com.voyageone.service.model.cms.CmsBtUsWorkloadModel;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

@Repository
public interface CmsBtUsWorkloadDaoExt {
    List<CmsBtUsWorkloadModel> selectListUsWorkload(@Param("channelId") String channelId,
                                                    @Param("cartId") int cartId,
                                                    @Param("publishTime") Date publishTime,
                                                    @Param("recordCount") int recordCount);
}