/*
 * CmsFeedLiveSkuDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.daoext.cms;

import com.voyageone.service.model.cms.CmsFeedLiveSkuKey;
import com.voyageone.service.model.cms.CmsFeedLiveSkuModel;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
public interface CmsFeedLiveSkuDaoExt {
    List<CmsFeedLiveSkuModel> selectList(Object map);

    CmsFeedLiveSkuModel selectOne(Object map);

    int selectCount(Object map);

    CmsFeedLiveSkuModel select(CmsFeedLiveSkuKey key);

    int insert(CmsFeedLiveSkuModel record);

    int insertList(List<CmsFeedLiveSkuModel> record);

    int update(CmsFeedLiveSkuModel record);

    int delete(CmsFeedLiveSkuKey key);
}