/*
 * CmsMtMasterBrandDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.daoext.cms;

import com.voyageone.service.bean.cms.CmsBtBrandMappingBean;
import com.voyageone.service.model.cms.CmsMtMasterBrandModel;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface CmsMtMasterBrandDaoExt {
    /**
     * 检索已匹配品牌分页
     */
    List<CmsMtMasterBrandModel> searchBrandsByPage(Map<String, Object> params);

    /**
     * 检索匹配品牌个数
     */
    int searchBrandsCount(Map<String, Object> params);
}