/*
 * CmsZzFeedOverstockPriceDao.java
 * Copyright(C) 2001-2016 VoyageOne Group Inc.
 * All rights reserved.
 * This class was generated by code generator, please don't modify it.
 * -----------------------------------------------
 */
package com.voyageone.service.daoext.cms;

import com.voyageone.service.model.cms.CmsZzFeedOverstockPriceModel;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface CmsZzFeedOverstockPriceDaoExt {
    List<CmsZzFeedOverstockPriceModel> selectList(Map<String, Object> map);

    CmsZzFeedOverstockPriceModel selectOne(Map<String, Object> map);

    int selectCount(Map<String, Object> map);

    CmsZzFeedOverstockPriceModel select(Integer id);

    int insert(CmsZzFeedOverstockPriceModel record);

    int update(CmsZzFeedOverstockPriceModel record);

    int delete(Integer id);

    int deleteBySku(String sku);
}