package com.voyageone.components.channeladvisor.webservice;

import com.voyageone.components.channeladvisor.bean.orders.OrderCriteria;
import com.voyageone.components.channeladvisor.bean.orders.OrderSubmit;
import com.voyageone.components.channeladvisor.bean.orders.RefundOrderRequest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "OrderServiceSoap", targetNamespace = "http://api.channeladvisor.com/webservices/")
public interface OrderServiceSoap {

	/**
	 * 
	 * @param accountID
	 * @param markAsExported
	 * @param clientOrderIdentifierList
	 * @param orderIDList
	 * @return returns com.channeladvisor.api.webservices.
	 *         APIResultOfArrayOfSetExportStatusResponse
	 */
	@WebMethod(operationName = "SetOrdersExportStatus", action = "http://api.channeladvisor.com/webservices/SetOrdersExportStatus")
	@WebResult(name = "SetOrdersExportStatusResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "SetOrdersExportStatus", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.SetOrdersExportStatus")
	@ResponseWrapper(localName = "SetOrdersExportStatusResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.SetOrdersExportStatusResponse")
	public APIResultOfArrayOfSetExportStatusResponse setOrdersExportStatus(
			@WebParam(name = "accountID", targetNamespace = "http://api.channeladvisor.com/webservices/") String accountID,
			@WebParam(name = "orderIDList", targetNamespace = "http://api.channeladvisor.com/webservices/") ArrayOfInt orderIDList,
			@WebParam(name = "clientOrderIdentifierList", targetNamespace = "http://api.channeladvisor.com/webservices/") ArrayOfString clientOrderIdentifierList,
			@WebParam(name = "markAsExported", targetNamespace = "http://api.channeladvisor.com/webservices/") boolean markAsExported);

	/**
	 * 
	 * @param accountID
	 * @param request
	 * @return returns
	 *         com.channeladvisor.api.webservices.APIResultOfRefundOrderResponse
	 */
	@WebMethod(operationName = "SubmitOrderRefund", action = "http://api.channeladvisor.com/webservices/SubmitOrderRefund")
	@WebResult(name = "SubmitOrderRefundResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "SubmitOrderRefund", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.SubmitOrderRefund")
	@ResponseWrapper(localName = "SubmitOrderRefundResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.SubmitOrderRefundResponse")
	public APIResultOfRefundOrderResponse submitOrderRefund(
			@WebParam(name = "accountID", targetNamespace = "http://api.channeladvisor.com/webservices/") String accountID,
			@WebParam(name = "request", targetNamespace = "http://api.channeladvisor.com/webservices/") RefundOrderRequest request);

	/**
	 * 
	 * @param accountID
	 * @param sellerOrderIDList
	 * @param orderIDList
	 * @return returns
	 *         com.channeladvisor.api.webservices.APIResultOfArrayOfInt32
	 */
	@WebMethod(operationName = "SetSellerOrderID", action = "http://api.channeladvisor.com/webservices/SetSellerOrderID")
	@WebResult(name = "SetSellerOrderIDResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "SetSellerOrderID", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.SetSellerOrderID")
	@ResponseWrapper(localName = "SetSellerOrderIDResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.SetSellerOrderIDResponse")
	public APIResultOfArrayOfInt32 setSellerOrderID(
			@WebParam(name = "accountID", targetNamespace = "http://api.channeladvisor.com/webservices/") String accountID,
			@WebParam(name = "orderIDList", targetNamespace = "http://api.channeladvisor.com/webservices/") ArrayOfInt orderIDList,
			@WebParam(name = "sellerOrderIDList", targetNamespace = "http://api.channeladvisor.com/webservices/") ArrayOfString sellerOrderIDList);

	/**
	 * 
	 * @param accountID
	 * @param lineItemIDList
	 * @param sellerOrderItemIDList
	 * @param orderID
	 * @return returns
	 *         com.channeladvisor.api.webservices.APIResultOfArrayOfBoolean
	 */
	@WebMethod(operationName = "SetSellerOrderItemIDList", action = "http://api.channeladvisor.com/webservices/SetSellerOrderItemIDList")
	@WebResult(name = "SetSellerOrderItemIDListResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "SetSellerOrderItemIDList", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.SetSellerOrderItemIDList")
	@ResponseWrapper(localName = "SetSellerOrderItemIDListResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.SetSellerOrderItemIDListResponse")
	public APIResultOfArrayOfBoolean setSellerOrderItemIDList(
			@WebParam(name = "accountID", targetNamespace = "http://api.channeladvisor.com/webservices/") String accountID,
			@WebParam(name = "orderID", targetNamespace = "http://api.channeladvisor.com/webservices/") int orderID,
			@WebParam(name = "lineItemIDList", targetNamespace = "http://api.channeladvisor.com/webservices/") ArrayOfInt lineItemIDList,
			@WebParam(name = "sellerOrderItemIDList", targetNamespace = "http://api.channeladvisor.com/webservices/") ArrayOfString sellerOrderItemIDList);

	/**
	 * 
	 * @param accountID
	 * @param orderID
	 * @return returns com.channeladvisor.api.webservices.
	 *         APIResultOfOrderRefundHistoryResponse
	 */
	@WebMethod(operationName = "GetOrderRefundHistory", action = "http://api.channeladvisor.com/webservices/GetOrderRefundHistory")
	@WebResult(name = "GetOrderRefundHistoryResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "GetOrderRefundHistory", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.GetOrderRefundHistory")
	@ResponseWrapper(localName = "GetOrderRefundHistoryResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.GetOrderRefundHistoryResponse")
	public APIResultOfOrderRefundHistoryResponse getOrderRefundHistory(
			@WebParam(name = "accountID", targetNamespace = "http://api.channeladvisor.com/webservices/") String accountID,
			@WebParam(name = "orderID", targetNamespace = "http://api.channeladvisor.com/webservices/") int orderID);

	/**
	 * 
	 * @param accountID
	 * @param updateOrderSubmitList
	 * @return returns com.channeladvisor.api.webservices.
	 *         APIResultOfArrayOfOrderUpdateResponse
	 */
	@WebMethod(operationName = "UpdateOrderList", action = "http://api.channeladvisor.com/webservices/UpdateOrderList")
	@WebResult(name = "UpdateOrderListResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "UpdateOrderList", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.UpdateOrderList")
	@ResponseWrapper(localName = "UpdateOrderListResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.UpdateOrderListResponse")
	public APIResultOfArrayOfOrderUpdateResponse updateOrderList(
			@WebParam(name = "accountID", targetNamespace = "http://api.channeladvisor.com/webservices/") String accountID,
			@WebParam(name = "updateOrderSubmitList", targetNamespace = "http://api.channeladvisor.com/webservices/") ArrayOfOrderUpdateSubmit updateOrderSubmitList);

	/**
	 * 
	 * @param accountID
	 * @param orderIDMergeList
	 * @param primaryOrderID
	 * @return returns com.channeladvisor.api.webservices.APIResultOfBoolean
	 */
	@WebMethod(operationName = "OrderMerge", action = "http://api.channeladvisor.com/webservices/OrderMerge")
	@WebResult(name = "OrderMergeResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "OrderMerge", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.OrderMerge")
	@ResponseWrapper(localName = "OrderMergeResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.OrderMergeResponse")
	public APIResultOfBoolean orderMerge(
			@WebParam(name = "accountID", targetNamespace = "http://api.channeladvisor.com/webservices/") String accountID,
			@WebParam(name = "primaryOrderID", targetNamespace = "http://api.channeladvisor.com/webservices/") int primaryOrderID,
			@WebParam(name = "orderIDMergeList", targetNamespace = "http://api.channeladvisor.com/webservices/") ArrayOfInt orderIDMergeList);

	/**
	 * 
	 * @param accountID
	 * @param lineItemIDList
	 * @param orderID
	 * @return returns com.channeladvisor.api.webservices.APIResultOfBoolean
	 */
	@WebMethod(operationName = "OrderSplit", action = "http://api.channeladvisor.com/webservices/OrderSplit")
	@WebResult(name = "OrderSplitResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "OrderSplit", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.OrderSplit")
	@ResponseWrapper(localName = "OrderSplitResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.OrderSplitResponse")
	public APIResultOfBoolean orderSplit(
			@WebParam(name = "accountID", targetNamespace = "http://api.channeladvisor.com/webservices/") String accountID,
			@WebParam(name = "orderID", targetNamespace = "http://api.channeladvisor.com/webservices/") int orderID,
			@WebParam(name = "lineItemIDList", targetNamespace = "http://api.channeladvisor.com/webservices/") ArrayOfInt lineItemIDList);

	/**
	 * 
	 * @param accountID
	 * @param order
	 * @return returns com.channeladvisor.api.webservices.APIResultOfInt32
	 */
	@WebMethod(operationName = "SubmitOrder", action = "http://api.channeladvisor.com/webservices/SubmitOrder")
	@WebResult(name = "SubmitOrderResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "SubmitOrder", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.SubmitOrder")
	@ResponseWrapper(localName = "SubmitOrderResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.SubmitOrderResponse")
	public APIResultOfInt32 submitOrder(
			@WebParam(name = "accountID", targetNamespace = "http://api.channeladvisor.com/webservices/") String accountID,
			@WebParam(name = "order", targetNamespace = "http://api.channeladvisor.com/webservices/") OrderSubmit order);

	/**
	 * 
	 * @param accountID
	 * @param orderCriteria
	 * @return returns
	 *         com.channeladvisor.api.webservices.APIResultOfArrayOfOrderResponseItem
	 */
	@WebMethod(operationName = "GetOrderList", action = "http://api.channeladvisor.com/webservices/GetOrderList")
	@WebResult(name = "GetOrderListResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "GetOrderList", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.GetOrderList")
	@ResponseWrapper(localName = "GetOrderListResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.GetOrderListResponse")
	public APIResultOfArrayOfOrderResponseItem getOrderList(
			@WebParam(name = "accountID", targetNamespace = "http://api.channeladvisor.com/webservices/") String accountID,
			@WebParam(name = "orderCriteria", targetNamespace = "http://api.channeladvisor.com/webservices/") OrderCriteria orderCriteria);

	/**
	 * 
	 * @return returns com.channeladvisor.api.webservices.APIResultOfString
	 */
	@WebMethod(operationName = "Ping", action = "http://api.channeladvisor.com/webservices/Ping")
	@WebResult(name = "PingResult", targetNamespace = "http://api.channeladvisor.com/webservices/")
	@RequestWrapper(localName = "Ping", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.Ping")
	@ResponseWrapper(localName = "PingResponse", targetNamespace = "http://api.channeladvisor.com/webservices/", className = "com.channeladvisor.api.webservices.PingResponse")
	public APIResultOfString ping();

}
